openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Display & Video 360 API
  description: >-
    Display & Video 360 API allows users to automate complex Display & Video 360
    workflows, such as creating insertion orders and setting targeting options
    for individual line items.
  version: v1
  x-discovery-doc-revision: '20230615'
  x-generated-date: '2023-06-25'
servers:
  - url: https://displayvideo.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/display-video: >-
              Create, see, edit, and permanently delete your Display & Video 360
              entities and reports
            https://www.googleapis.com/auth/doubleclickbidmanager: View and manage your reports in DoubleClick Bid Manager
            https://www.googleapis.com/auth/display-video-user-management: >-
              Private Service:
              https://www.googleapis.com/auth/display-video-user-management
            https://www.googleapis.com/auth/display-video-mediaplanning: >-
              Create, see, and edit Display & Video 360 Campaign entities and
              see billing invoices
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /media/{resourceName}:
    post:
      description: >-
        Uploads media. Upload is supported on the URI
        `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload
        requests will not be successful without including `upload_type=media`
        query string.
      operationId: displayvideo.media.upload
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/doubleclickbidmanager
          Oauth2c:
            - https://www.googleapis.com/auth/doubleclickbidmanager
      x-stackQL-resource: media
      x-stackQL-verb: exec
  /download/{resourceName}:
    get:
      description: >-
        Downloads media. Download is supported on the URI
        `/download/{resource_name=**}?alt=media.` **Note**: Download requests
        will not be successful without including `alt=media` query string.
      operationId: displayvideo.media.download
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/doubleclickbidmanager
          Oauth2c:
            - https://www.googleapis.com/auth/doubleclickbidmanager
      x-stackQL-resource: media
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/assets:
    post:
      description: >-
        Uploads an asset. Returns the ID of the newly uploaded asset if
        successful. The asset file size should be no more than 10 MB for images,
        200 MB for ZIP files, and 1 GB for videos. Must be used within the
        [multipart media upload
        process](/display-video/api/guides/how-tos/upload#multipart). Examples
        using provided client libraries can be found in our [Creating Creatives
        guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).
      operationId: displayvideo.advertisers.assets.upload
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assets
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:
    patch:
      description: >-
        Updates an existing line item. Returns the updated line item if
        successful. Requests to this endpoint cannot be made concurrently with
        the following requests updating the same line item: *
        BulkEditAssignedTargetingOptions * BulkUpdateLineItems *
        CreateLineItemAssignedTargetingOption *
        DeleteLineItemAssignedTargetingOption
      operationId: displayvideo.advertisers.lineItems.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: line_items
      x-stackQL-verb: exec
    get:
      description: Gets a line item.
      operationId: displayvideo.advertisers.lineItems.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: line_items
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a line item. Returns error code `NOT_FOUND` if the line item
        does not exist. The line item should be archived first, i.e. set
        entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.
      operationId: displayvideo.advertisers.lineItems.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: line_items
      x-stackQL-verb: delete
  /v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkListLineItemAssignedTargetingOptions:
    get:
      description: Lists assigned targeting options of a line item across targeting types.
      operationId: >-
        displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: line_items
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/lineItems:generateDefault:
    post:
      description: >-
        Creates a new line item with settings (including targeting) inherited
        from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status.
        Returns the newly created line item if successful. There are default
        values based on the three fields: * The insertion order's
        insertion_order_type * The insertion order's automation_type * The given
        line_item_type
      operationId: displayvideo.advertisers.lineItems.generateDefault
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: line_items
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/lineItems:
    post:
      description: >-
        Creates a new line item. Returns the newly created line item if
        successful.
      operationId: displayvideo.advertisers.lineItems.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: line_items
      x-stackQL-verb: insert
    get:
      description: >-
        Lists line items in an advertiser. The order is defined by the order_by
        parameter. If a filter by entity_status is not specified, line items
        with `ENTITY_STATUS_ARCHIVED` will not be included in the results.
      operationId: displayvideo.advertisers.lineItems.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: line_items
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkEditLineItemAssignedTargetingOptions:
    post:
      description: >-
        Bulk edits targeting options under a single line item. The operation
        will delete the assigned targeting options provided in
        BulkEditLineItemAssignedTargetingOptionsRequest.delete_requests and then
        create the assigned targeting options provided in
        BulkEditLineItemAssignedTargetingOptionsRequest.create_requests.
        Requests to this endpoint cannot be made concurrently with the following
        requests updating the same line item: * UpdateLineItem *
        CreateLineItemAssignedTargetingOption *
        DeleteLineItemAssignedTargetingOption
      operationId: >-
        displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: line_items
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to a line item.
      operationId: >-
        displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
    post:
      description: >-
        Assigns a targeting option to a line item. Returns the assigned
        targeting option if successful. Requests to this endpoint cannot be made
        concurrently with the following requests updating the same line item: *
        BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem *
        DeleteLineItemAssignedTargetingOption
      operationId: >-
        displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: insert
  /v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}:
    get:
      description: Gets a single targeting option assigned to a line item.
      operationId: >-
        displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes an assigned targeting option from a line item. Requests to this
        endpoint cannot be made concurrently with the following requests
        updating the same line item: * BulkEditAssignedTargetingOptions *
        BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetingOption
      operationId: >-
        displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: delete
  /v1/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency:
    get:
      description: Retrieves the invoice currency used by an advertiser in a given month.
      operationId: displayvideo.advertisers.invoices.lookupInvoiceCurrency
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-mediaplanning
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-mediaplanning
      x-stackQL-resource: invoices
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/invoices:
    get:
      description: >-
        Lists invoices posted for an advertiser in a given month. Invoices
        generated by billing profiles with a "Partner" invoice level are not
        retrievable through this method.
      operationId: displayvideo.advertisers.invoices.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-mediaplanning
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-mediaplanning
      x-stackQL-resource: invoices
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/manualTriggers:
    post:
      description: >-
        Creates a new manual trigger. Returns the newly created manual trigger
        if successful. **Warning:** Line Items using manual triggers no longer
        serve in Display & Video 360. This method will sunset on August 1, 2023.
        Read our [feature deprecation
        announcement](/display-video/api/deprecations#features.manual_triggers)
        for more information.
      operationId: displayvideo.advertisers.manualTriggers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: manual_triggers
      x-stackQL-verb: insert
    get:
      description: >-
        Lists manual triggers that are accessible to the current user for a
        given advertiser ID. The order is defined by the order_by parameter. A
        single advertiser_id is required. **Warning:** Line Items using manual
        triggers no longer serve in Display & Video 360. This method will sunset
        on August 1, 2023. Read our [feature deprecation
        announcement](/display-video/api/deprecations#features.manual_triggers)
        for more information.
      operationId: displayvideo.advertisers.manualTriggers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: manual_triggers
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:
    get:
      description: >-
        Gets a manual trigger. **Warning:** Line Items using manual triggers no
        longer serve in Display & Video 360. This method will sunset on August
        1, 2023. Read our [feature deprecation
        announcement](/display-video/api/deprecations#features.manual_triggers)
        for more information.
      operationId: displayvideo.advertisers.manualTriggers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: manual_triggers
      x-stackQL-verb: select
    patch:
      description: >-
        Updates a manual trigger. Returns the updated manual trigger if
        successful. **Warning:** Line Items using manual triggers no longer
        serve in Display & Video 360. This method will sunset on August 1, 2023.
        Read our [feature deprecation
        announcement](/display-video/api/deprecations#features.manual_triggers)
        for more information.
      operationId: displayvideo.advertisers.manualTriggers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: manual_triggers
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate:
    post:
      description: >-
        Activates a manual trigger. Each activation of the manual trigger must
        be at least 5 minutes apart, otherwise an error will be returned.
        **Warning:** Line Items using manual triggers no longer serve in Display
        & Video 360. This method will sunset on August 1, 2023. Read our
        [feature deprecation
        announcement](/display-video/api/deprecations#features.manual_triggers)
        for more information.
      operationId: displayvideo.advertisers.manualTriggers.activate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: manual_triggers
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate:
    post:
      description: >-
        Deactivates a manual trigger. **Warning:** Line Items using manual
        triggers no longer serve in Display & Video 360. This method will sunset
        on August 1, 2023. Read our [feature deprecation
        announcement](/display-video/api/deprecations#features.manual_triggers)
        for more information.
      operationId: displayvideo.advertisers.manualTriggers.deactivate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: manual_triggers
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}:
    get:
      description: Gets a single targeting option assigned to an insertion order.
      operationId: >-
        displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to an insertion order.
      operationId: >-
        displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/insertionOrders:
    get:
      description: >-
        Lists insertion orders in an advertiser. The order is defined by the
        order_by parameter. If a filter by entity_status is not specified,
        insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in
        the results.
      operationId: displayvideo.advertisers.insertionOrders.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: insertion_orders
      x-stackQL-verb: select
    post:
      description: >-
        Creates a new insertion order. Returns the newly created insertion order
        if successful.
      operationId: displayvideo.advertisers.insertionOrders.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: insertion_orders
      x-stackQL-verb: insert
  /v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:bulkListInsertionOrderAssignedTargetingOptions:
    get:
      description: >-
        Lists assigned targeting options of an insertion order across targeting
        types.
      operationId: >-
        displayvideo.advertisers.insertionOrders.bulkListInsertionOrderAssignedTargetingOptions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: insertion_orders
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:
    patch:
      description: >-
        Updates an existing insertion order. Returns the updated insertion order
        if successful.
      operationId: displayvideo.advertisers.insertionOrders.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: insertion_orders
      x-stackQL-verb: exec
    delete:
      description: >-
        Deletes an insertion order. Returns error code `NOT_FOUND` if the
        insertion order does not exist. The insertion order should be archived
        first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to
        delete it.
      operationId: displayvideo.advertisers.insertionOrders.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: insertion_orders
      x-stackQL-verb: delete
    get:
      description: >-
        Gets an insertion order. Returns error code `NOT_FOUND` if the insertion
        order does not exist.
      operationId: displayvideo.advertisers.insertionOrders.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: insertion_orders
      x-stackQL-verb: select
  /v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:
    post:
      description: Creates a negative keyword in a negative keyword list.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keywords
      x-stackQL-verb: insert
  /v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}:
    delete:
      description: Deletes a negative keyword from a negative keyword list.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keywords
      x-stackQL-verb: delete
  /v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace:
    post:
      description: >-
        Replaces all negative keywords in a single negative keyword list. The
        operation will replace the keywords in a negative keyword list with
        keywords provided in
        ReplaceNegativeKeywordsRequest.new_negative_keywords.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keywords
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:
    get:
      description: Lists negative keywords in a negative keyword list.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keywords
      x-stackQL-verb: select
  /v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit:
    post:
      description: >-
        Bulk edits negative keywords in a single negative keyword list. The
        operation will delete the negative keywords provided in
        BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then
        create the negative keywords provided in
        BulkEditNegativeKeywordsRequest.created_negative_keywords. This
        operation is guaranteed to be atomic and will never result in a partial
        success or partial failure.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keywords
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/negativeKeywordLists:
    post:
      description: >-
        Creates a new negative keyword list. Returns the newly created negative
        keyword list if successful.
      operationId: displayvideo.advertisers.negativeKeywordLists.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keyword_lists
      x-stackQL-verb: insert
    get:
      description: Lists negative keyword lists based on a given advertiser id.
      operationId: displayvideo.advertisers.negativeKeywordLists.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keyword_lists
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}:
    delete:
      description: >-
        Deletes a negative keyword list given an advertiser ID and a negative
        keyword list ID.
      operationId: displayvideo.advertisers.negativeKeywordLists.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keyword_lists
      x-stackQL-verb: delete
    get:
      description: >-
        Gets a negative keyword list given an advertiser ID and a negative
        keyword list ID.
      operationId: displayvideo.advertisers.negativeKeywordLists.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keyword_lists
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}:
    patch:
      description: >-
        Updates a negative keyword list. Returns the updated negative keyword
        list if successful.
      operationId: displayvideo.advertisers.negativeKeywordLists.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: negative_keyword_lists
      x-stackQL-verb: exec
  /v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}:
    delete:
      description: Deletes the assignment between a location and a location list.
      operationId: displayvideo.advertisers.locationLists.assignedLocations.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_locations
      x-stackQL-verb: delete
  /v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations:
    post:
      description: Creates an assignment between a location and a location list.
      operationId: displayvideo.advertisers.locationLists.assignedLocations.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_locations
      x-stackQL-verb: insert
    get:
      description: Lists locations assigned to a location list.
      operationId: displayvideo.advertisers.locationLists.assignedLocations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_locations
      x-stackQL-verb: select
  /v1/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit:
    post:
      description: >-
        Bulk edits multiple assignments between locations and a single location
        list. The operation will delete the assigned locations provided in
        BulkEditAssignedLocationsRequest.deleted_assigned_locations and then
        create the assigned locations provided in
        BulkEditAssignedLocationsRequest.created_assigned_locations.
      operationId: displayvideo.advertisers.locationLists.assignedLocations.bulkEdit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_locations
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/locationLists/{locationListsId}:
    get:
      description: Gets a location list.
      operationId: displayvideo.advertisers.locationLists.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: location_lists
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/locationLists:
    post:
      description: >-
        Creates a new location list. Returns the newly created location list if
        successful.
      operationId: displayvideo.advertisers.locationLists.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: location_lists
      x-stackQL-verb: insert
    get:
      description: Lists location lists based on a given advertiser id.
      operationId: displayvideo.advertisers.locationLists.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: location_lists
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/locationLists/{locationListId}:
    patch:
      description: >-
        Updates a location list. Returns the updated location list if
        successful.
      operationId: displayvideo.advertisers.locationLists.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: location_lists
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}:
    get:
      description: Gets a single targeting option assigned to an advertiser.
      operationId: displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
    delete:
      description: Deletes an assigned targeting option from an advertiser.
      operationId: displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: delete
  /v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to an advertiser.
      operationId: displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
    post:
      description: >-
        Assigns a targeting option to an advertiser. Returns the assigned
        targeting option if successful.
      operationId: displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: insert
  /v1/advertisers/{advertiserId}/channels/{channelsId}/sites:
    post:
      description: Creates a site in a channel.
      operationId: displayvideo.advertisers.channels.sites.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: insert
  /v1/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}:
    delete:
      description: Deletes a site from a channel.
      operationId: displayvideo.advertisers.channels.sites.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: delete
  /v1/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit:
    post:
      description: >-
        Bulk edits sites under a single channel. The operation will delete the
        sites provided in BulkEditSitesRequest.deleted_sites and then create the
        sites provided in BulkEditSitesRequest.created_sites.
      operationId: displayvideo.advertisers.channels.sites.bulkEdit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/channels/{channelsId}/sites:
    get:
      description: Lists sites in a channel.
      operationId: displayvideo.advertisers.channels.sites.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: select
  /v1/advertisers/{advertiserId}/channels/{channelsId}/sites:replace:
    post:
      description: >-
        Replaces all of the sites under a single channel. The operation will
        replace the sites under a channel with the sites provided in
        ReplaceSitesRequest.new_sites.
      operationId: displayvideo.advertisers.channels.sites.replace
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/channels:
    post:
      description: Creates a new channel. Returns the newly created channel if successful.
      operationId: displayvideo.advertisers.channels.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: channels
      x-stackQL-verb: insert
    get:
      description: Lists channels for a partner or advertiser.
      operationId: displayvideo.advertisers.channels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: channels
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/channels/{channelsId}:
    get:
      description: Gets a channel for a partner or advertiser.
      operationId: displayvideo.advertisers.channels.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: channels
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/channels/{channelId}:
    patch:
      description: Updates a channel. Returns the updated channel if successful.
      operationId: displayvideo.advertisers.channels.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: channels
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/creatives:
    post:
      description: >-
        Creates a new creative. Returns the newly created creative if
        successful.
      operationId: displayvideo.advertisers.creatives.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: creatives
      x-stackQL-verb: insert
    get:
      description: >-
        Lists creatives in an advertiser. The order is defined by the order_by
        parameter. If a filter by entity_status is not specified, creatives with
        `ENTITY_STATUS_ARCHIVED` will not be included in the results.
      operationId: displayvideo.advertisers.creatives.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: creatives
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/creatives/{creativesId}:
    delete:
      description: >-
        Deletes a creative. Returns error code `NOT_FOUND` if the creative does
        not exist. The creative should be archived first, i.e. set entity_status
        to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.
      operationId: displayvideo.advertisers.creatives.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: creatives
      x-stackQL-verb: delete
    get:
      description: Gets a creative.
      operationId: displayvideo.advertisers.creatives.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: creatives
      x-stackQL-verb: select
    patch:
      description: >-
        Updates an existing creative. Returns the updated creative if
        successful.
      operationId: displayvideo.advertisers.creatives.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: creatives
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}:
    get:
      description: Gets a single targeting option assigned to a campaign.
      operationId: >-
        displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions:
    get:
      description: >-
        Lists the targeting options assigned to a campaign for a specified
        targeting type.
      operationId: >-
        displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/campaigns/{campaignsId}:
    patch:
      description: >-
        Updates an existing campaign. Returns the updated campaign if
        successful.
      operationId: displayvideo.advertisers.campaigns.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-mediaplanning
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-mediaplanning
      x-stackQL-resource: campaigns
      x-stackQL-verb: exec
    delete:
      description: >-
        Permanently deletes a campaign. A deleted campaign cannot be recovered.
        The campaign should be archived first, i.e. set entity_status to
        `ENTITY_STATUS_ARCHIVED`, to be able to delete it.
      operationId: displayvideo.advertisers.campaigns.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-mediaplanning
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-mediaplanning
      x-stackQL-resource: campaigns
      x-stackQL-verb: delete
    get:
      description: Gets a campaign.
      operationId: displayvideo.advertisers.campaigns.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-mediaplanning
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-mediaplanning
      x-stackQL-resource: campaigns
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/campaigns:
    post:
      description: >-
        Creates a new campaign. Returns the newly created campaign if
        successful.
      operationId: displayvideo.advertisers.campaigns.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-mediaplanning
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-mediaplanning
      x-stackQL-resource: campaigns
      x-stackQL-verb: insert
    get:
      description: >-
        Lists campaigns in an advertiser. The order is defined by the order_by
        parameter. If a filter by entity_status is not specified, campaigns with
        `ENTITY_STATUS_ARCHIVED` will not be included in the results.
      operationId: displayvideo.advertisers.campaigns.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-mediaplanning
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-mediaplanning
      x-stackQL-resource: campaigns
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}/campaigns/{campaignsId}:bulkListCampaignAssignedTargetingOptions:
    get:
      description: Lists assigned targeting options of a campaign across targeting types.
      operationId: >-
        displayvideo.advertisers.campaigns.bulkListCampaignAssignedTargetingOptions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: campaigns
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}:
    patch:
      description: >-
        Updates an existing advertiser. Returns the updated advertiser if
        successful.
      operationId: displayvideo.advertisers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: advertisers
      x-stackQL-verb: exec
    get:
      description: Gets an advertiser.
      operationId: displayvideo.advertisers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: advertisers
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes an advertiser. Deleting an advertiser will delete all of its
        child resources, for example, campaigns, insertion orders and line
        items. A deleted advertiser cannot be recovered.
      operationId: displayvideo.advertisers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: advertisers
      x-stackQL-verb: delete
  /v1/advertisers/{advertisersId}:bulkListAdvertiserAssignedTargetingOptions:
    get:
      description: >-
        Lists assigned targeting options of an advertiser across targeting
        types.
      operationId: displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: advertisers
      x-stackQL-verb: exec
  /v1/advertisers:
    post:
      description: >-
        Creates a new advertiser. Returns the newly created advertiser if
        successful. This method can take up to 180 seconds to complete.
      operationId: displayvideo.advertisers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: advertisers
      x-stackQL-verb: insert
    get:
      description: >-
        Lists advertisers that are accessible to the current user. The order is
        defined by the order_by parameter. A single partner_id is required.
        Cross-partner listing is not supported.
      operationId: displayvideo.advertisers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: advertisers
      x-stackQL-verb: select
  /v1/advertisers/{advertisersId}:audit:
    get:
      description: >-
        Audits an advertiser. Returns the counts of used entities per resource
        type under the advertiser provided. Used entities count towards their
        respective resource limit. See
        https://support.google.com/displayvideo/answer/6071450.
      operationId: displayvideo.advertisers.audit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: advertisers
      x-stackQL-verb: exec
  /v1/advertisers/{advertisersId}:bulkEditAdvertiserAssignedTargetingOptions:
    post:
      description: >-
        Bulk edits targeting options under a single advertiser. The operation
        will delete the assigned targeting options provided in
        BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and
        then create the assigned targeting options provided in
        BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .
      operationId: displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: advertisers
      x-stackQL-verb: exec
  /v1/customBiddingAlgorithms:
    post:
      description: >-
        Creates a new custom bidding algorithm. Returns the newly created custom
        bidding algorithm if successful.
      operationId: displayvideo.customBiddingAlgorithms.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: custom_bidding_algorithms
      x-stackQL-verb: insert
    get:
      description: >-
        Lists custom bidding algorithms that are accessible to the current user
        and can be used in bidding stratgies. The order is defined by the
        order_by parameter.
      operationId: displayvideo.customBiddingAlgorithms.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: custom_bidding_algorithms
      x-stackQL-verb: select
  /v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript:
    get:
      description: >-
        Creates a custom bidding script reference object for a script file. The
        resulting reference object provides a resource path to which the script
        file should be uploaded. This reference object should be included in
        when creating a new custom bidding script object.
      operationId: displayvideo.customBiddingAlgorithms.uploadScript
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: custom_bidding_algorithms
      x-stackQL-verb: exec
  /v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}:
    get:
      description: Gets a custom bidding algorithm.
      operationId: displayvideo.customBiddingAlgorithms.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: custom_bidding_algorithms
      x-stackQL-verb: select
    patch:
      description: >-
        Updates an existing custom bidding algorithm. Returns the updated custom
        bidding algorithm if successful.
      operationId: displayvideo.customBiddingAlgorithms.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: custom_bidding_algorithms
      x-stackQL-verb: exec
  /v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts:
    post:
      description: >-
        Creates a new custom bidding script. Returns the newly created script if
        successful.
      operationId: displayvideo.customBiddingAlgorithms.scripts.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: scripts
      x-stackQL-verb: insert
    get:
      description: >-
        Lists custom bidding scripts that belong to the given algorithm. The
        order is defined by the order_by parameter.
      operationId: displayvideo.customBiddingAlgorithms.scripts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: scripts
      x-stackQL-verb: select
  /v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}:
    get:
      description: Gets a custom bidding script.
      operationId: displayvideo.customBiddingAlgorithms.scripts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: scripts
      x-stackQL-verb: select
  /v1/partners/{partnersId}:
    get:
      description: Gets a partner.
      operationId: displayvideo.partners.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: partners
      x-stackQL-verb: select
  /v1/partners/{partnersId}:bulkEditPartnerAssignedTargetingOptions:
    post:
      description: >-
        Bulk edits targeting options under a single partner. The operation will
        delete the assigned targeting options provided in
        BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then
        create the assigned targeting options provided in
        BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .
      operationId: displayvideo.partners.bulkEditPartnerAssignedTargetingOptions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: partners
      x-stackQL-verb: exec
  /v1/partners:
    get:
      description: >-
        Lists partners that are accessible to the current user. The order is
        defined by the order_by parameter.
      operationId: displayvideo.partners.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: partners
      x-stackQL-verb: select
  /v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}:
    delete:
      description: Deletes an assigned targeting option from a partner.
      operationId: displayvideo.partners.targetingTypes.assignedTargetingOptions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: delete
    get:
      description: Gets a single targeting option assigned to a partner.
      operationId: displayvideo.partners.targetingTypes.assignedTargetingOptions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
  /v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to a partner.
      operationId: displayvideo.partners.targetingTypes.assignedTargetingOptions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: select
    post:
      description: >-
        Assigns a targeting option to a partner. Returns the assigned targeting
        option if successful.
      operationId: displayvideo.partners.targetingTypes.assignedTargetingOptions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_targeting_options
      x-stackQL-verb: insert
  /v1/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}:
    delete:
      description: Deletes a site from a channel.
      operationId: displayvideo.partners.channels.sites.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: delete
  /v1/partners/{partnerId}/channels/{channelsId}/sites:replace:
    post:
      description: >-
        Replaces all of the sites under a single channel. The operation will
        replace the sites under a channel with the sites provided in
        ReplaceSitesRequest.new_sites.
      operationId: displayvideo.partners.channels.sites.replace
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: exec
  /v1/partners/{partnerId}/channels/{channelsId}/sites:
    post:
      description: Creates a site in a channel.
      operationId: displayvideo.partners.channels.sites.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: insert
  /v1/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit:
    post:
      description: >-
        Bulk edits sites under a single channel. The operation will delete the
        sites provided in BulkEditSitesRequest.deleted_sites and then create the
        sites provided in BulkEditSitesRequest.created_sites.
      operationId: displayvideo.partners.channels.sites.bulkEdit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: exec
  /v1/partners/{partnersId}/channels/{channelsId}/sites:
    get:
      description: Lists sites in a channel.
      operationId: displayvideo.partners.channels.sites.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sites
      x-stackQL-verb: select
  /v1/partners/{partnersId}/channels:
    get:
      description: Lists channels for a partner or advertiser.
      operationId: displayvideo.partners.channels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: channels
      x-stackQL-verb: select
    post:
      description: Creates a new channel. Returns the newly created channel if successful.
      operationId: displayvideo.partners.channels.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: channels
      x-stackQL-verb: insert
  /v1/partners/{partnersId}/channels/{channelsId}:
    get:
      description: Gets a channel for a partner or advertiser.
      operationId: displayvideo.partners.channels.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: channels
      x-stackQL-verb: select
  /v1/partners/{partnersId}/channels/{channelId}:
    patch:
      description: Updates a channel. Returns the updated channel if successful.
      operationId: displayvideo.partners.channels.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: channels
      x-stackQL-verb: exec
  /v1/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors:
    post:
      description: >-
        Edits read/write accessors of an inventory source. Returns the updated
        read_write_accessors for the inventory source.
      operationId: displayvideo.inventorySources.editInventorySourceReadWriteAccessors
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_sources
      x-stackQL-verb: exec
  /v1/inventorySources/{inventorySourcesId}:
    patch:
      description: >-
        Updates an existing inventory source. Returns the updated inventory
        source if successful.
      operationId: displayvideo.inventorySources.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_sources
      x-stackQL-verb: exec
    get:
      description: Gets an inventory source.
      operationId: displayvideo.inventorySources.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_sources
      x-stackQL-verb: select
  /v1/inventorySources:
    post:
      description: >-
        Creates a new inventory source. Returns the newly created inventory
        source if successful.
      operationId: displayvideo.inventorySources.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_sources
      x-stackQL-verb: insert
    get:
      description: >-
        Lists inventory sources that are accessible to the current user. The
        order is defined by the order_by parameter. If a filter by entity_status
        is not specified, inventory sources with entity status
        `ENTITY_STATUS_ARCHIVED` will not be included in the results.
      operationId: displayvideo.inventorySources.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_sources
      x-stackQL-verb: select
  /v1/users:
    get:
      description: >-
        Lists users that are accessible to the current user. If two users have
        user roles on the same partner or advertiser, they can access each
        other. This method has unique authentication requirements. Read the
        prerequisites in our [Managing Users
        guide](/display-video/api/guides/users/overview#prerequisites) before
        using this method. The "Try this method" feature does not work for this
        method.
      operationId: displayvideo.users.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-user-management
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-user-management
      x-stackQL-resource: users
      x-stackQL-verb: select
    post:
      description: >-
        Creates a new user. Returns the newly created user if successful. This
        method has unique authentication requirements. Read the prerequisites in
        our [Managing Users
        guide](/display-video/api/guides/users/overview#prerequisites) before
        using this method. The "Try this method" feature does not work for this
        method.
      operationId: displayvideo.users.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-user-management
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-user-management
      x-stackQL-resource: users
      x-stackQL-verb: insert
  /v1/users/{usersId}:
    get:
      description: >-
        Gets a user. This method has unique authentication requirements. Read
        the prerequisites in our [Managing Users
        guide](/display-video/api/guides/users/overview#prerequisites) before
        using this method. The "Try this method" feature does not work for this
        method.
      operationId: displayvideo.users.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-user-management
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-user-management
      x-stackQL-resource: users
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a user. This method has unique authentication requirements. Read
        the prerequisites in our [Managing Users
        guide](/display-video/api/guides/users/overview#prerequisites) before
        using this method. The "Try this method" feature does not work for this
        method.
      operationId: displayvideo.users.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-user-management
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-user-management
      x-stackQL-resource: users
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates an existing user. Returns the updated user if successful. This
        method has unique authentication requirements. Read the prerequisites in
        our [Managing Users
        guide](/display-video/api/guides/users/overview#prerequisites) before
        using this method. The "Try this method" feature does not work for this
        method.
      operationId: displayvideo.users.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-user-management
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-user-management
      x-stackQL-resource: users
      x-stackQL-verb: exec
  /v1/users/{usersId}:bulkEditAssignedUserRoles:
    post:
      description: >-
        Bulk edits user roles for a user. The operation will delete the assigned
        user roles provided in
        BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then
        assign the user roles provided in
        BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method
        has unique authentication requirements. Read the prerequisites in our
        [Managing Users
        guide](/display-video/api/guides/users/overview#prerequisites) before
        using this method. The "Try this method" feature does not work for this
        method.
      operationId: displayvideo.users.bulkEditAssignedUserRoles
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video-user-management
          Oauth2c:
            - https://www.googleapis.com/auth/display-video-user-management
      x-stackQL-resource: users
      x-stackQL-verb: exec
  /v1/floodlightGroups/{floodlightGroupId}:
    patch:
      description: >-
        Updates an existing Floodlight group. Returns the updated Floodlight
        group if successful.
      operationId: displayvideo.floodlightGroups.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: floodlight_groups
      x-stackQL-verb: exec
  /v1/floodlightGroups/{floodlightGroupsId}:
    get:
      description: Gets a Floodlight group.
      operationId: displayvideo.floodlightGroups.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: floodlight_groups
      x-stackQL-verb: select
  /v1/combinedAudiences/{combinedAudiencesId}:
    get:
      description: Gets a combined audience.
      operationId: displayvideo.combinedAudiences.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: combined_audiences
      x-stackQL-verb: select
  /v1/combinedAudiences:
    get:
      description: >-
        Lists combined audiences. The order is defined by the order_by
        parameter.
      operationId: displayvideo.combinedAudiences.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: combined_audiences
      x-stackQL-verb: select
  /v1/customLists/{customListsId}:
    get:
      description: Gets a custom list.
      operationId: displayvideo.customLists.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: custom_lists
      x-stackQL-verb: select
  /v1/customLists:
    get:
      description: Lists custom lists. The order is defined by the order_by parameter.
      operationId: displayvideo.customLists.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: custom_lists
      x-stackQL-verb: select
  /v1/guaranteedOrders:
    get:
      description: >-
        Lists guaranteed orders that are accessible to the current user. The
        order is defined by the order_by parameter. If a filter by entity_status
        is not specified, guaranteed orders with entity status
        `ENTITY_STATUS_ARCHIVED` will not be included in the results.
      operationId: displayvideo.guaranteedOrders.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: guaranteed_orders
      x-stackQL-verb: select
    post:
      description: >-
        Creates a new guaranteed order. Returns the newly created guaranteed
        order if successful.
      operationId: displayvideo.guaranteedOrders.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: guaranteed_orders
      x-stackQL-verb: insert
  /v1/guaranteedOrders/{guaranteedOrdersId}:
    get:
      description: Gets a guaranteed order.
      operationId: displayvideo.guaranteedOrders.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: guaranteed_orders
      x-stackQL-verb: select
    patch:
      description: >-
        Updates an existing guaranteed order. Returns the updated guaranteed
        order if successful.
      operationId: displayvideo.guaranteedOrders.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: guaranteed_orders
      x-stackQL-verb: exec
  /v1/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors:
    post:
      description: Edits read advertisers of a guaranteed order.
      operationId: displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: guaranteed_orders
      x-stackQL-verb: exec
  /v1/googleAudiences:
    get:
      description: Lists Google audiences. The order is defined by the order_by parameter.
      operationId: displayvideo.googleAudiences.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: google_audiences
      x-stackQL-verb: select
  /v1/googleAudiences/{googleAudiencesId}:
    get:
      description: Gets a Google audience.
      operationId: displayvideo.googleAudiences.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: google_audiences
      x-stackQL-verb: select
  /v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers:
    post:
      description: >-
        Updates the member list of a Customer Match audience. Only supported for
        the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` *
        `CUSTOMER_MATCH_DEVICE_ID`
      operationId: displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: first_and_third_party_audiences
      x-stackQL-verb: exec
  /v1/firstAndThirdPartyAudiences:
    post:
      description: >-
        Creates a FirstAndThirdPartyAudience. Only supported for the following
        audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` *
        `CUSTOMER_MATCH_DEVICE_ID`
      operationId: displayvideo.firstAndThirdPartyAudiences.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: first_and_third_party_audiences
      x-stackQL-verb: insert
    get:
      description: >-
        Lists first and third party audiences. The order is defined by the
        order_by parameter.
      operationId: displayvideo.firstAndThirdPartyAudiences.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: first_and_third_party_audiences
      x-stackQL-verb: select
  /v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:
    patch:
      description: >-
        Updates an existing FirstAndThirdPartyAudience. Only supported for the
        following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` *
        `CUSTOMER_MATCH_DEVICE_ID`
      operationId: displayvideo.firstAndThirdPartyAudiences.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: first_and_third_party_audiences
      x-stackQL-verb: exec
    get:
      description: Gets a first and third party audience.
      operationId: displayvideo.firstAndThirdPartyAudiences.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: first_and_third_party_audiences
      x-stackQL-verb: select
  /v1/sdfdownloadtasks/operations/{operationsId}:
    get:
      description: >-
        Gets the latest state of an asynchronous SDF download task operation.
        Clients should poll this method at intervals of 30 seconds.
      operationId: displayvideo.sdfdownloadtasks.operations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
        - Oauth2:
            - https://www.googleapis.com/auth/doubleclickbidmanager
          Oauth2c:
            - https://www.googleapis.com/auth/doubleclickbidmanager
      x-stackQL-resource: operations
      x-stackQL-verb: select
  /v1/sdfdownloadtasks:
    post:
      description: >-
        Creates an SDF Download Task. Returns an Operation. An SDF Download Task
        is a long-running, asynchronous operation. The metadata type of this
        operation is SdfDownloadTaskMetadata. If the request is successful, the
        response type of the operation is SdfDownloadTask. The response will not
        include the download files, which must be retrieved with media.download.
        The state of operation can be retrieved with
        sdfdownloadtask.operations.get. Any errors can be found in the
        error.message. Note that error.details is expected to be empty.
      operationId: displayvideo.sdfdownloadtasks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: sdfdownloadtasks
      x-stackQL-verb: insert
  /v1/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}:
    get:
      description: Gets a single targeting option.
      operationId: displayvideo.targetingTypes.targetingOptions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: targeting_options
      x-stackQL-verb: select
  /v1/targetingTypes/{targetingTypesId}/targetingOptions:search:
    post:
      description: >-
        Searches for targeting options of a given type based on the given search
        terms.
      operationId: displayvideo.targetingTypes.targetingOptions.search
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: targeting_options
      x-stackQL-verb: exec
  /v1/targetingTypes/{targetingTypesId}/targetingOptions:
    get:
      description: Lists targeting options of a given type.
      operationId: displayvideo.targetingTypes.targetingOptions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: targeting_options
      x-stackQL-verb: select
  /v1/inventorySourceGroups/{inventorySourceGroupsId}:
    get:
      description: Gets an inventory source group.
      operationId: displayvideo.inventorySourceGroups.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_source_groups
      x-stackQL-verb: select
    delete:
      description: Deletes an inventory source group.
      operationId: displayvideo.inventorySourceGroups.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_source_groups
      x-stackQL-verb: delete
  /v1/inventorySourceGroups:
    get:
      description: >-
        Lists inventory source groups that are accessible to the current user.
        The order is defined by the order_by parameter.
      operationId: displayvideo.inventorySourceGroups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_source_groups
      x-stackQL-verb: select
    post:
      description: >-
        Creates a new inventory source group. Returns the newly created
        inventory source group if successful.
      operationId: displayvideo.inventorySourceGroups.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_source_groups
      x-stackQL-verb: insert
  /v1/inventorySourceGroups/{inventorySourceGroupId}:
    patch:
      description: >-
        Updates an inventory source group. Returns the updated inventory source
        group if successful.
      operationId: displayvideo.inventorySourceGroups.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: inventory_source_groups
      x-stackQL-verb: exec
  /v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:
    get:
      description: Lists inventory sources assigned to an inventory source group.
      operationId: displayvideo.inventorySourceGroups.assignedInventorySources.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_inventory_sources
      x-stackQL-verb: select
    post:
      description: >-
        Creates an assignment between an inventory source and an inventory
        source group.
      operationId: displayvideo.inventorySourceGroups.assignedInventorySources.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_inventory_sources
      x-stackQL-verb: insert
  /v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}:
    delete:
      description: >-
        Deletes the assignment between an inventory source and an inventory
        source group.
      operationId: displayvideo.inventorySourceGroups.assignedInventorySources.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_inventory_sources
      x-stackQL-verb: delete
  /v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit:
    post:
      description: >-
        Bulk edits multiple assignments between inventory sources and a single
        inventory source group. The operation will delete the assigned inventory
        sources provided in
        BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources
        and then create the assigned inventory sources provided in
        BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.
      operationId: displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/display-video
          Oauth2c:
            - https://www.googleapis.com/auth/display-video
      x-stackQL-resource: assigned_inventory_sources
      x-stackQL-verb: exec
