openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: AdMob API
  description: >-
    The AdMob API allows publishers to programmatically get information about
    their AdMob account. 
  version: v1
  x-discovery-doc-revision: '20230622'
  x-generated-date: '2023-06-25'
servers:
  - url: https://admob.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/admob.report: See your AdMob data
            https://www.googleapis.com/auth/admob.readonly: See your AdMob data
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/accounts/{accountsId}/adUnits:
    get:
      description: List the ad units under the specified AdMob account.
      operationId: admob.accounts.adUnits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
      x-stackQL-resource: ad_units
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/apps:
    get:
      description: List the apps under the specified AdMob account.
      operationId: admob.accounts.apps.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
      x-stackQL-resource: apps
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/networkReport:generate:
    post:
      description: >-
        Generates an AdMob Network report based on the provided report
        specification. Returns result of a server-side streaming RPC. The result
        is returned in a sequence of responses.
      operationId: admob.accounts.networkReport.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      x-stackQL-resource: network_report
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/mediationReport:generate:
    post:
      description: >-
        Generates an AdMob mediation report based on the provided report
        specification. Returns result of a server-side streaming RPC. The result
        is returned in a sequence of responses.
      operationId: admob.accounts.mediationReport.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      x-stackQL-resource: mediation_report
      x-stackQL-verb: exec
  /v1/accounts:
    get:
      description: >-
        Lists the AdMob publisher account that was most recently signed in to
        from the AdMob UI. For more information, see
        https://support.google.com/admob/answer/10243672.
      operationId: admob.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      x-stackQL-resource: accounts
      x-stackQL-verb: select
  /v1/accounts/{accountsId}:
    get:
      description: Gets information about the specified AdMob publisher account.
      operationId: admob.accounts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      x-stackQL-resource: accounts
      x-stackQL-verb: select
