openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Chat API
  description: >-
    Enables apps to fetch information and perform actions in Google Chat.
    Authentication is a prerequisite for using the Google Chat REST API.
  version: v1
  x-discovery-doc-revision: '20230618'
  x-generated-date: '2023-06-25'
servers:
  - url: https://chat.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/chat.memberships.readonly: View members in Google Chat conversations.
            https://www.googleapis.com/auth/chat.bot: 'Private Service: https://www.googleapis.com/auth/chat.bot'
            https://www.googleapis.com/auth/chat.messages.reactions.readonly: View reactions to messages in Google Chat
            https://www.googleapis.com/auth/chat.messages.create: Compose and send messages in Google Chat
            https://www.googleapis.com/auth/chat.memberships.app: Add and remove itself from conversations in Google Chat
            https://www.googleapis.com/auth/chat.messages.reactions.create: Add reactions to messages in Google Chat
            https://www.googleapis.com/auth/chat.spaces: >-
              Create conversations and spaces and view or update metadata
              (including history settings) in Google Chat
            https://www.googleapis.com/auth/chat.messages.reactions: View, add, and delete reactions to messages in Google Chat
            https://www.googleapis.com/auth/chat.memberships: View, add, and remove members from conversations in Google Chat
            https://www.googleapis.com/auth/chat.spaces.readonly: View chat and spaces in Google Chat
            https://www.googleapis.com/auth/chat.messages: >-
              View, compose, send, update, and delete messages, and add, view,
              and delete reactions to messages.
            https://www.googleapis.com/auth/chat.import: Import spaces, messages, and memberships into Google Chat.
            https://www.googleapis.com/auth/chat.delete: >-
              Delete conversations and spaces & remove access to associated
              files in Google Chat
            https://www.googleapis.com/auth/chat.messages.readonly: View messages and reactions in Google Chat
            https://www.googleapis.com/auth/chat.spaces.create: Create new conversations in Google Chat
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/spaces/{spacesId}/members/{membersId}:
    get:
      description: >-
        Returns details about a membership. For an example, see [Get a
        membership](https://developers.google.com/chat/api/guides/v1/members/get).
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Fully supports [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        and [user
        authentication](https://developers.google.com/chat/api/guides/auth/users).
        [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.memberships` or `chat.memberships.readonly`
        authorization scope.
      operationId: chat.spaces.members.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.readonly
      x-stackQL-resource: members
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a membership. For an example, see [Delete a
        membership](https://developers.google.com/chat/api/guides/v1/members/delete).
        Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.memberships` or `chat.memberships.app` authorization
        scope.
      operationId: chat.spaces.members.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.app
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.app
      x-stackQL-resource: members
      x-stackQL-verb: delete
  /v1/spaces/{spacesId}/members:
    post:
      description: >-
        Creates a human membership or app membership for the calling app.
        Creating memberships for other apps isn't supported. For an example, see
        [ Create a
        membership](https://developers.google.com/chat/api/guides/v1/members/create).
        When creating a membership, if the specified member has their
        auto-accept policy turned off, then they're invited, and must accept the
        space invitation before joining. Otherwise, creating a membership adds
        the member directly to the specified space. Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.memberships` (for human membership) or
        `chat.memberships.app` (for app membership) scope. To specify the member
        to add, set the `membership.member.name` in the
        `CreateMembershipRequest`: - To add the calling app to a space or a
        direct message between two human users, use `users/app`. Unable to add
        other apps to the space. - To add a human user, use `users/{user}`,
        where `{user}` is either the `{person_id}` for the
        [person](https://developers.google.com/people/api/rest/v1/people) from
        the People API, or the `id` for the
        [user](https://developers.google.com/admin-sdk/directory/reference/rest/v1/users)
        in the Directory API. For example, if the People API `Person`
        `resourceName` is `people/123456789`, you can add the user to the space
        by setting the `membership.member.name` to `users/123456789`.
      operationId: chat.spaces.members.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.app
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.app
      x-stackQL-resource: members
      x-stackQL-verb: insert
    get:
      description: >-
        Lists memberships in a space. For an example, see [List
        memberships](https://developers.google.com/chat/api/guides/v1/members/list).
        Listing memberships with [app
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        lists memberships in spaces that the Chat app has access to, but
        excludes Chat app memberships, including its own. Listing memberships
        with [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        lists memberships in spaces that the authenticated user has access to.
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Fully supports [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        and [user
        authentication](https://developers.google.com/chat/api/guides/auth/users).
        [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.memberships` or `chat.memberships.readonly`
        authorization scope.
      operationId: chat.spaces.members.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.readonly
      x-stackQL-resource: members
      x-stackQL-verb: select
  /v1/spaces/{spacesId}/messages/{messagesId}:
    delete:
      description: >-
        Deletes a message. For an example, see [Delete a
        message](https://developers.google.com/chat/api/guides/v1/messages/delete).
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Fully supports [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        and [user
        authentication](https://developers.google.com/chat/api/guides/auth/users).
        [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.messages` authorization scope.
      operationId: chat.spaces.messages.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
      x-stackQL-resource: messages
      x-stackQL-verb: delete
    put:
      description: >-
        Updates a message. There's a difference between the `patch` and `update`
        methods. The `patch` method uses a `patch` request while the `update`
        method uses a `put` request. We recommend using the `patch` method. For
        an example, see [Update a
        message](https://developers.google.com/chat/api/guides/v1/messages/update).
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Fully supports [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        and [user
        authentication](https://developers.google.com/chat/api/guides/auth/users).
        [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.messages` authorization scope.
      operationId: chat.spaces.messages.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
      x-stackQL-resource: messages
      x-stackQL-verb: exec
    patch:
      description: >-
        Updates a message. There's a difference between the `patch` and `update`
        methods. The `patch` method uses a `patch` request while the `update`
        method uses a `put` request. We recommend using the `patch` method. For
        an example, see [Update a
        message](https://developers.google.com/chat/api/guides/v1/messages/update).
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Fully supports [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        and [user
        authentication](https://developers.google.com/chat/api/guides/auth/users).
        [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.messages` authorization scope.
      operationId: chat.spaces.messages.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
      x-stackQL-resource: messages
      x-stackQL-verb: exec
    get:
      description: >-
        Returns details about a message. For an example, see [Read a
        message](https://developers.google.com/chat/api/guides/v1/messages/get).
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Fully supports [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        and [user
        authentication](https://developers.google.com/chat/api/guides/auth/users).
        [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.messages` or `chat.messages.readonly` authorization
        scope. Note: Might return a message from a blocked member or space.
      operationId: chat.spaces.messages.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
      x-stackQL-resource: messages
      x-stackQL-verb: select
  /v1/spaces/{spacesId}/messages:
    post:
      description: >-
        Creates a message. For an example, see [Create a
        message](https://developers.google.com/chat/api/guides/crudl/messages#create_a_message).
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Creating a text message supports both [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and [app authentication]
        (https://developers.google.com/chat/api/guides/auth/service-accounts).
        [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.messages` or `chat.messages.create` authorization
        scope. Creating a card message only supports and requires [app
        authentication]
        (https://developers.google.com/chat/api/guides/auth/service-accounts).
        Because Chat provides authentication for
        [webhooks](https://developers.google.com/chat/how-tos/webhooks) as part
        of the URL that's generated when a webhook is registered, webhooks can
        create messages without a service account or user authentication.
      operationId: chat.spaces.messages.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.create
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.create
      x-stackQL-resource: messages
      x-stackQL-verb: insert
    get:
      description: >-
        Lists messages in a space that the caller is a member of, including
        messages from blocked members and spaces. For an example, see [List
        messages](/chat/api/guides/v1/messages/list). Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.messages` or `chat.messages.readonly` authorization scope.
        This method is only supported in spaces that don't allow users from
        outside the Workspace organization to join.
      operationId: chat.spaces.messages.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
      x-stackQL-resource: messages
      x-stackQL-verb: select
  /v1/spaces/{spacesId}/messages/{messagesId}/attachments/{attachmentsId}:
    get:
      description: >-
        Gets the metadata of a message attachment. The attachment data is
        fetched using the [media
        API](https://developers.google.com/chat/api/reference/rest/v1/media/download).
        For an example, see [Get a message
        attachment](https://developers.google.com/chat/api/guides/v1/media-and-attachments/get).
        Requires [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).
      operationId: chat.spaces.messages.attachments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
      x-stackQL-resource: attachments
      x-stackQL-verb: select
  /v1/spaces/{spacesId}/messages/{messagesId}/reactions:
    get:
      description: >-
        Lists reactions to a message. For an example, see [List
        reactions](https://developers.google.com/chat/api/guides/v1/reactions/list).
        Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and `chat.messages`, `chat.messages.readonly`,
        `chat.messages.reactions`, or `chat.messages.reactions.readonly` scope.
      operationId: chat.spaces.messages.reactions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
      x-stackQL-resource: reactions
      x-stackQL-verb: select
    post:
      description: >-
        Creates a reaction and adds it to a message. For an example, see [Create
        a
        reaction](https://developers.google.com/chat/api/guides/v1/reactions/create).
        Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.messages`, `chat.messages.reactions`, or
        `chat.messages.reactions.create` scope. Only unicode emoji are
        supported.
      operationId: chat.spaces.messages.reactions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions.create
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions.create
      x-stackQL-resource: reactions
      x-stackQL-verb: insert
  /v1/spaces/{spacesId}/messages/{messagesId}/reactions/{reactionsId}:
    delete:
      description: >-
        Deletes a reaction to a message. For an example, see [Delete a
        reaction](https://developers.google.com/chat/api/guides/v1/reactions/delete).
        Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.messages` or `chat.messages.reactions` scope.
      operationId: chat.spaces.messages.reactions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
      x-stackQL-resource: reactions
      x-stackQL-verb: delete
  /v1/spaces/{spacesId}:
    patch:
      description: >-
        Updates a space. For an example, see [Update a
        space](https://developers.google.com/chat/api/guides/v1/spaces/update).
        Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.spaces` scope.
      operationId: chat.spaces.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
      x-stackQL-resource: spaces
      x-stackQL-verb: exec
    get:
      description: >-
        Returns details about a space. For an example, see [Get a
        space](https://developers.google.com/chat/api/guides/v1/spaces/get).
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Fully supports [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        and [user
        authentication](https://developers.google.com/chat/api/guides/auth/users).
        [User
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.spaces` or `chat.spaces.readonly` authorization
        scope.
      operationId: chat.spaces.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      x-stackQL-resource: spaces
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a named space. Always performs a cascading delete, which means
        that the space's child resources—like messages posted in the space and
        memberships in the space—are also deleted. For an example, see [Delete a
        space](https://developers.google.com/chat/api/guides/v1/spaces/delete).
        Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        from a user who has permission to delete the space, and the
        `chat.delete` scope.
      operationId: chat.spaces.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.delete
          Oauth2c:
            - https://www.googleapis.com/auth/chat.delete
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
      x-stackQL-resource: spaces
      x-stackQL-verb: delete
  /v1/spaces:findDirectMessage:
    get:
      description: >-
        Returns the existing direct message with the specified user. If no
        direct message space is found, returns a `404 NOT_FOUND` error. For an
        example, see [Find a direct
        message](/chat/api/guides/v1/spaces/find-direct-message). With [user
        authentication](https://developers.google.com/chat/api/guides/auth/users),
        returns the direct message space between the specified user and the
        authenticated user. With [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts),
        returns the direct message space between the specified user and the
        calling Chat app. Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        or [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).
      operationId: chat.spaces.findDirectMessage
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      x-stackQL-resource: spaces
      x-stackQL-verb: exec
  /v1/spaces:
    post:
      description: >-
        Creates a named space. Spaces grouped by topics or that have guest
        access aren't supported. For an example, see [Create a
        space](https://developers.google.com/chat/api/guides/v1/spaces/create).
        Requires [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.spaces.create` or `chat.spaces` scope.
      operationId: chat.spaces.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.create
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.create
      x-stackQL-resource: spaces
      x-stackQL-verb: insert
    get:
      description: >-
        Lists spaces the caller is a member of. Group chats and DMs aren't
        listed until the first message is sent. For an example, see [List
        spaces](https://developers.google.com/chat/api/guides/v1/spaces/list).
        Requires
        [authentication](https://developers.google.com/chat/api/guides/auth).
        Fully supports [service account
        authentication](https://developers.google.com/chat/api/guides/auth/service-accounts)
        and [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        requires the `chat.spaces` or `chat.spaces.readonly` authorization
        scope. Lists spaces visible to the caller or authenticated user. Group
        chats and DMs aren't listed until the first message is sent.
      operationId: chat.spaces.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      x-stackQL-resource: spaces
      x-stackQL-verb: select
  /v1/spaces:setup:
    post:
      description: >-
        Creates a space and adds specified users to it. The calling user is
        automatically added to the space, and shouldn't be specified as a
        membership in the request. For an example, see [Set up a
        space](https://developers.google.com/chat/api/guides/v1/spaces/set-up).
        To specify the human members to add, add memberships with the
        appropriate `member.name` in the `SetUpSpaceRequest`. To add a human
        user, use `users/{user}`, where `{user}` is either the `{person_id}` for
        the [person](https://developers.google.com/people/api/rest/v1/people)
        from the People API, or the `id` for the
        [user](https://developers.google.com/admin-sdk/directory/reference/rest/v1/users)
        in the Admin SDK Directory API. For example, if the People API `Person`
        `resourceName` is `people/123456789`, you can add the user to the space
        by including a membership with `users/123456789` as the `member.name`.
        For a space or group chat, if the caller blocks or is blocked by some
        members, then those members aren't added to the created space. To create
        a direct message (DM) between the calling user and another human user,
        specify exactly one membership to represent the human user. If one user
        blocks the other, the request fails and the DM isn't created. To create
        a DM between the calling user and the calling app, set
        `Space.singleUserBotDm` to `true` and don't specify any memberships. You
        can only use this method to set up a DM with the calling app. To add the
        calling app as a member of a space or an existing DM between two human
        users, see [create a
        membership](https://developers.google.com/chat/api/guides/v1/members/create).
        If a DM already exists between two users, even when one user blocks the
        other at the time a request is made, then the existing DM is returned.
        Spaces with threaded replies or guest access aren't supported. Requires
        [user
        authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.spaces.create` or `chat.spaces` scope.
      operationId: chat.spaces.setup
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.create
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.create
      x-stackQL-resource: spaces
      x-stackQL-verb: exec
  /v1/media/{mediaId}:
    get:
      description: >-
        Downloads media. Download is supported on the URI
        `/v1/media/{+name}?alt=media`.
      operationId: chat.media.download
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
      x-stackQL-resource: media
      x-stackQL-verb: exec
  /v1/spaces/{spacesId}/attachments:upload:
    post:
      description: >-
        Uploads an attachment. For an example, see [Upload media as a file
        attachment](https://developers.google.com/chat/api/guides/v1/media-and-attachments/upload).
        Requires user
        [authentication](https://developers.google.com/chat/api/guides/auth/users)
        and the `chat.messages` or `chat.messages.create` authorization scope.
        You can upload attachments up to 200 MB. Certain file types aren't
        supported. For details, see [File types blocked by Google
        Chat](https://support.google.com/chat/answer/7651457?&co=GENIE.Platform%3DDesktop#File%20types%20blocked%20in%20Google%20Chat).
      operationId: chat.media.upload
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.import
          Oauth2c:
            - https://www.googleapis.com/auth/chat.import
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.create
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.create
      x-stackQL-resource: media
      x-stackQL-verb: exec
