openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Chrome Management API
  description: >-
    The Chrome Management API is a suite of services that allows Chrome
    administrators to view, manage and gain insights on their Chrome OS and
    Chrome Browser devices.
  version: v1
  x-discovery-doc-revision: '20230622'
  x-generated-date: '2023-06-25'
servers:
  - url: https://chromemanagement.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/chrome.management.telemetry.readonly: >-
              See basic device and telemetry information collected from Chrome
              OS devices or users managed within your organization
            https://www.googleapis.com/auth/chrome.management.appdetails.readonly: >-
              See detailed information about apps installed on Chrome browsers
              and devices managed by your organization
            https://www.googleapis.com/auth/chrome.management.reports.readonly: >-
              See reports about devices and Chrome browsers managed within your
              organization
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/customers/{customersId}/apps/android/{androidId}:
    get:
      description: Get a specific app for a customer by its resource name.
      operationId: chromemanagement.customers.apps.android.get
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.appdetails.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.appdetails.readonly
      x-stackQL-resource: android
      x-stackQL-verb: select
  /v1/customers/{customersId}/apps/chrome/{chromeId}:
    get:
      description: Get a specific app for a customer by its resource name.
      operationId: chromemanagement.customers.apps.chrome.get
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.appdetails.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.appdetails.readonly
      x-stackQL-resource: chrome
      x-stackQL-verb: select
  /v1/customers/{customersId}/apps/web/{webId}:
    get:
      description: Get a specific app for a customer by its resource name.
      operationId: chromemanagement.customers.apps.web.get
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.appdetails.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.appdetails.readonly
      x-stackQL-resource: web
      x-stackQL-verb: select
  /v1/customers/{customersId}/apps:countChromeAppRequests:
    get:
      description: Generate summary of app installation requests.
      operationId: chromemanagement.customers.apps.countChromeAppRequests
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.appdetails.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.appdetails.readonly
      x-stackQL-resource: apps
      x-stackQL-verb: exec
  /v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention:
    get:
      description: >-
        Count of Chrome Browsers that have been recently enrolled, have new
        policy to be synced, or have no recent activity.
      operationId: chromemanagement.customers.reports.countChromeBrowsersNeedingAttention
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v1/customers/{customersId}/reports:countChromeHardwareFleetDevices:
    get:
      description: >-
        Counts of devices with a specific hardware specification from the
        requested hardware type (for example model name, processor type).
        Further information can be found here
        https://support.google.com/chrome/a/answer/10564947
      operationId: chromemanagement.customers.reports.countChromeHardwareFleetDevices
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention:
    get:
      description: >-
        Counts of ChromeOS devices that have not synced policies or have lacked
        user activity in the past 28 days, are out of date, or are not
        complaint. Further information can be found here
        https://support.google.com/chrome/a/answer/10564947
      operationId: chromemanagement.customers.reports.countChromeDevicesThatNeedAttention
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v1/customers/{customersId}/reports:countInstalledApps:
    get:
      description: Generate report of app installations.
      operationId: chromemanagement.customers.reports.countInstalledApps
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v1/customers/{customersId}/reports:findInstalledAppDevices:
    get:
      description: >-
        Generate report of managed Chrome browser devices that have a specified
        app installed.
      operationId: chromemanagement.customers.reports.findInstalledAppDevices
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate:
    get:
      description: >-
        Generate report of the number of devices expiring in each month of the
        selected time frame. Devices are grouped by auto update expiration date
        and model. Further information can be found
        [here](https://support.google.com/chrome/a/answer/10564947).
      operationId: >-
        chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v1/customers/{customersId}/reports:countChromeVersions:
    get:
      description: Generate report of installed Chrome versions.
      operationId: chromemanagement.customers.reports.countChromeVersions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v1/customers/{customersId}/telemetry/users/{usersId}:
    get:
      description: Get telemetry user.
      operationId: chromemanagement.customers.telemetry.users.get
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      x-stackQL-resource: users
      x-stackQL-verb: select
  /v1/customers/{customersId}/telemetry/users:
    get:
      description: List all telemetry users.
      operationId: chromemanagement.customers.telemetry.users.list
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      x-stackQL-resource: users
      x-stackQL-verb: select
  /v1/customers/{customersId}/telemetry/events:
    get:
      description: List telemetry events.
      operationId: chromemanagement.customers.telemetry.events.list
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      x-stackQL-resource: events
      x-stackQL-verb: select
  /v1/customers/{customersId}/telemetry/devices/{devicesId}:
    get:
      description: Get telemetry device.
      operationId: chromemanagement.customers.telemetry.devices.get
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      x-stackQL-resource: devices
      x-stackQL-verb: select
  /v1/customers/{customersId}/telemetry/devices:
    get:
      description: List all telemetry devices.
      operationId: chromemanagement.customers.telemetry.devices.list
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      x-stackQL-resource: devices
      x-stackQL-verb: select
