openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Search Console API
  description: >-
    The Search Console API provides access to both Search Console data (verified
    users only) and to public information on an URL basis (anyone)
  version: v1
  x-discovery-doc-revision: '20230622'
  x-generated-date: '2023-06-25'
servers:
  - url: https://searchconsole.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/webmasters.readonly: View Search Console data for your verified sites
            https://www.googleapis.com/auth/webmasters: View and manage Search Console data for your verified sites
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/urlTestingTools/mobileFriendlyTest:run:
    post:
      description: Runs Mobile-Friendly Test for a given URL.
      operationId: searchconsole.urlTestingTools.mobileFriendlyTest.run
      security: []
      x-stackQL-resource: mobile_friendly_test
      x-stackQL-verb: exec
  /webmasters/v3/sites/{siteUrl}/searchAnalytics/query:
    post:
      description: >-
        Query your data with filters and parameters that you define. Returns
        zero or more rows grouped by the row keys that you define. You must
        define a date range of one or more days. When date is one of the group
        by values, any days without data are omitted from the result list. If
        you need to know which days have data, issue a broad date range query
        grouped by date for any metric, and see which day rows are returned.
      operationId: webmasters.searchanalytics.query
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      x-stackQL-resource: searchanalytics
      x-stackQL-verb: exec
  /v1/urlInspection/index:inspect:
    post:
      description: Index inspection.
      operationId: searchconsole.urlInspection.index.inspect
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      x-stackQL-resource: index
      x-stackQL-verb: exec
  /webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}:
    put:
      description: Submits a sitemap for a site.
      operationId: webmasters.sitemaps.submit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
      x-stackQL-resource: sitemaps
      x-stackQL-verb: exec
    get:
      description: Retrieves information about a specific sitemap.
      operationId: webmasters.sitemaps.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      x-stackQL-resource: sitemaps
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a sitemap from the Sitemaps report. Does not stop Google from
        crawling this sitemap or the URLs that were previously crawled in the
        deleted sitemap.
      operationId: webmasters.sitemaps.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
      x-stackQL-resource: sitemaps
      x-stackQL-verb: delete
  /webmasters/v3/sites/{siteUrl}/sitemaps:
    get:
      description: ' Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request).'
      operationId: webmasters.sitemaps.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      x-stackQL-resource: sitemaps
      x-stackQL-verb: select
  /webmasters/v3/sites/{siteUrl}:
    put:
      description: ' Adds a site to the set of the user''s sites in Search Console.'
      operationId: webmasters.sites.add
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
      x-stackQL-resource: sites
      x-stackQL-verb: insert
    delete:
      description: ' Removes a site from the set of the user''s Search Console sites.'
      operationId: webmasters.sites.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
      x-stackQL-resource: sites
      x-stackQL-verb: delete
    get:
      description: ' Retrieves information about specific site.'
      operationId: webmasters.sites.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      x-stackQL-resource: sites
      x-stackQL-verb: select
  /webmasters/v3/sites:
    get:
      description: ' Lists the user''s Search Console sites.'
      operationId: webmasters.sites.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      x-stackQL-resource: sites
      x-stackQL-verb: select
