openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Drive API
  description: The Google Drive API allows clients to access resources from Google Drive.
  version: v2
  x-discovery-doc-revision: '20230621'
  x-generated-date: '2023-06-25'
servers:
  - url: https://www.googleapis.com/drive/v2
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/drive.file: >-
              See, edit, create, and delete only the specific Google Drive files
              you use with this app
            https://www.googleapis.com/auth/drive.metadata: View and manage metadata of files in your Google Drive
            https://www.googleapis.com/auth/drive.photos.readonly: View the photos, videos and albums in your Google Photos
            https://www.googleapis.com/auth/drive.metadata.readonly: See information about your Google Drive files
            https://www.googleapis.com/auth/drive.apps.readonly: View your Google Drive apps
            https://www.googleapis.com/auth/drive.scripts: Modify your Google Apps Script scripts' behavior
            https://www.googleapis.com/auth/drive.readonly: See and download all your Google Drive files
            https://www.googleapis.com/auth/drive: See, edit, create, and delete all of your Google Drive files
            https://www.googleapis.com/auth/drive.appdata: >-
              See, create, and delete its own configuration data in your Google
              Drive
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /files/{fileId}/comments/{commentId}/replies:
    post:
      description: Creates a new reply to the given comment.
      operationId: drive.replies.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: replies
      x-stackQL-verb: insert
    get:
      description: Lists all of the replies to a comment.
      operationId: drive.replies.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: replies
      x-stackQL-verb: select
  /files/{fileId}/comments/{commentId}/replies/{replyId}:
    delete:
      description: Deletes a reply.
      operationId: drive.replies.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: replies
      x-stackQL-verb: delete
    patch:
      description: Updates an existing reply.
      operationId: drive.replies.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: replies
      x-stackQL-verb: exec
    put:
      description: Updates an existing reply.
      operationId: drive.replies.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: replies
      x-stackQL-verb: exec
    get:
      description: Gets a reply.
      operationId: drive.replies.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: replies
      x-stackQL-verb: select
  /about:
    get:
      description: >-
        Gets the information about the current user along with Drive API
        settings
      operationId: drive.about.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: about
      x-stackQL-verb: select
  /drives/{driveId}:
    get:
      description: Gets a shared drive's metadata by ID.
      operationId: drive.drives.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: drives
      x-stackQL-verb: select
    put:
      description: Updates the metadata for a shared drive.
      operationId: drive.drives.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: drives
      x-stackQL-verb: exec
    delete:
      description: >-
        Permanently deletes a shared drive for which the user is an organizer.
        The shared drive cannot contain any untrashed items.
      operationId: drive.drives.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: drives
      x-stackQL-verb: delete
  /drives/{driveId}/unhide:
    post:
      description: Restores a shared drive to the default view.
      operationId: drive.drives.unhide
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: drives
      x-stackQL-verb: exec
  /drives:
    post:
      description: Creates a new shared drive.
      operationId: drive.drives.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: drives
      x-stackQL-verb: insert
    get:
      description: ' Lists the user''s shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/drive/api/guides/search-shareddrives) guide.'
      operationId: drive.drives.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: drives
      x-stackQL-verb: select
  /drives/{driveId}/hide:
    post:
      description: Hides a shared drive from the default view.
      operationId: drive.drives.hide
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: drives
      x-stackQL-verb: exec
  /files/{fileId}/revisions:
    get:
      description: Lists a file's revisions.
      operationId: drive.revisions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: revisions
      x-stackQL-verb: select
  /files/{fileId}/revisions/{revisionId}:
    get:
      description: Gets a specific revision.
      operationId: drive.revisions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: revisions
      x-stackQL-verb: select
    patch:
      description: Updates a revision.
      operationId: drive.revisions.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: revisions
      x-stackQL-verb: exec
    delete:
      description: >-
        Permanently deletes a file version. You can only delete revisions for
        files with binary content, like images or videos. Revisions for other
        files, like Google Docs or Sheets, and the last remaining file version
        can't be deleted.
      operationId: drive.revisions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: revisions
      x-stackQL-verb: delete
    put:
      description: Updates a revision.
      operationId: drive.revisions.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: revisions
      x-stackQL-verb: exec
  /teamdrives/{teamDriveId}:
    put:
      description: 'Deprecated: Use `drives.update` instead.'
      operationId: drive.teamdrives.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: teamdrives
      x-stackQL-verb: exec
    delete:
      description: 'Deprecated: Use `drives.delete` instead.'
      operationId: drive.teamdrives.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: teamdrives
      x-stackQL-verb: delete
    get:
      description: 'Deprecated: Use `drives.get` instead.'
      operationId: drive.teamdrives.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: teamdrives
      x-stackQL-verb: select
  /teamdrives:
    get:
      description: 'Deprecated: Use `drives.list` instead.'
      operationId: drive.teamdrives.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: teamdrives
      x-stackQL-verb: select
    post:
      description: 'Deprecated: Use `drives.insert` instead.'
      operationId: drive.teamdrives.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: teamdrives
      x-stackQL-verb: insert
  /apps:
    get:
      description: Lists a user's installed apps.
      operationId: drive.apps.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
      x-stackQL-resource: apps
      x-stackQL-verb: select
  /apps/{appId}:
    get:
      description: Gets a specific app.
      operationId: drive.apps.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: apps
      x-stackQL-verb: select
  /files/{fileId}/properties:
    get:
      description: Lists a file's properties.
      operationId: drive.properties.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: select
    post:
      description: Adds a property to a file, or updates it if it already exists.
      operationId: drive.properties.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
      x-stackQL-resource: properties
      x-stackQL-verb: insert
  /files/{fileId}/properties/{propertyKey}:
    put:
      description: Updates a property.
      operationId: drive.properties.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
      x-stackQL-resource: properties
      x-stackQL-verb: exec
    patch:
      description: Updates a property.
      operationId: drive.properties.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
      x-stackQL-resource: properties
      x-stackQL-verb: exec
    get:
      description: Gets a property by its key.
      operationId: drive.properties.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: select
    delete:
      description: Deletes a property.
      operationId: drive.properties.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
      x-stackQL-resource: properties
      x-stackQL-verb: delete
  /files/{fileId}/permissions:
    get:
      description: Lists a file's or shared drive's permissions.
      operationId: drive.permissions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: permissions
      x-stackQL-verb: select
    post:
      description: >-
        Inserts a permission for a file or shared drive. **Warning:** Concurrent
        permissions operations on the same file are not supported; only the last
        update is applied.
      operationId: drive.permissions.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: permissions
      x-stackQL-verb: insert
  /files/{fileId}/permissions/{permissionId}:
    delete:
      description: >-
        Deletes a permission from a file or shared drive. **Warning:**
        Concurrent permissions operations on the same file are not supported;
        only the last update is applied.
      operationId: drive.permissions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: permissions
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates a permission using patch semantics. **Warning:** Concurrent
        permissions operations on the same file are not supported; only the last
        update is applied.
      operationId: drive.permissions.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: permissions
      x-stackQL-verb: exec
    put:
      description: >-
        Updates a permission. **Warning:** Concurrent permissions operations on
        the same file are not supported; only the last update is applied.
      operationId: drive.permissions.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: permissions
      x-stackQL-verb: exec
    get:
      description: Gets a permission by ID.
      operationId: drive.permissions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: permissions
      x-stackQL-verb: select
  /permissionIds/{email}:
    get:
      description: Returns the permission ID for an email address.
      operationId: drive.permissions.getIdForEmail
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: permissions__id_for_email
      x-stackQL-verb: select
  /changes:
    get:
      description: Lists the changes for a user or shared drive.
      operationId: drive.changes.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: changes
      x-stackQL-verb: select
  /changes/{changeId}:
    get:
      description: >-
        Deprecated: Use `changes.getStartPageToken` and `changes.list` to
        retrieve recent changes.
      operationId: drive.changes.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: changes
      x-stackQL-verb: select
  /changes/startPageToken:
    get:
      description: Gets the starting pageToken for listing future changes.
      operationId: drive.changes.getStartPageToken
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: changes__start_page_token
      x-stackQL-verb: select
  /changes/watch:
    post:
      description: Subscribe to changes for a user.
      operationId: drive.changes.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: changes
      x-stackQL-verb: exec
  /files/{fileId}/touch:
    post:
      description: Set the file's updated time to the current server time.
      operationId: drive.files.touch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/{fileId}/modifyLabels:
    post:
      description: >-
        Modifies the set of labels applied to a file. Returns a list of the
        labels that were added or modified.
      operationId: drive.files.modifyLabels
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/generateIds:
    get:
      description: >-
        Generates a set of file IDs which can be provided in insert or copy
        requests.
      operationId: drive.files.generateIds
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/{fileId}:
    put:
      description: ' Updates a file''s metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the lit[...]'
      operationId: drive.files.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.scripts
          Oauth2c:
            - https://www.googleapis.com/auth/drive.scripts
      x-stackQL-resource: files
      x-stackQL-verb: exec
    get:
      description: ' Gets a file''s metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads).'
      operationId: drive.files.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: files
      x-stackQL-verb: select
    delete:
      description: >-
        Permanently deletes a file by ID. Skips the trash. The currently
        authenticated user must own the file or be an organizer on the parent
        for shared drive files.
      operationId: drive.files.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: files
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates a file's metadata and/or content. When calling this method, only
        populate fields in the request that you want to modify. When updating
        fields, some fields might change automatically, such as modifiedDate.
        This method supports patch semantics.
      operationId: drive.files.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.scripts
          Oauth2c:
            - https://www.googleapis.com/auth/drive.scripts
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files:
    get:
      description: ' Lists the user''s files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files & folders](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don''t want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.'
      operationId: drive.files.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: files
      x-stackQL-verb: select
    post:
      description: ' Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads). Apps creating shortcuts with `files.[...]'
      operationId: drive.files.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: files
      x-stackQL-verb: insert
  /files/trash:
    delete:
      description: Permanently deletes all of the user's trashed files.
      operationId: drive.files.emptyTrash
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/{fileId}/listLabels:
    get:
      description: Lists the labels on a file.
      operationId: drive.files.listLabels
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: files__labels
      x-stackQL-verb: select
  /files/{fileId}/watch:
    post:
      description: Subscribes to changes to a file.
      operationId: drive.files.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/{fileId}/copy:
    post:
      description: Creates a copy of the specified file.
      operationId: drive.files.copy
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/{fileId}/untrash:
    post:
      description: >-
        Restores a file from the trash. The currently authenticated user must
        own the file or be at least a `fileOrganizer` on the parent for shared
        drive files. Only the owner may untrash a file.
      operationId: drive.files.untrash
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/{fileId}/trash:
    post:
      description: ' Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files. Only the owner may trash a file. The trashed item is excluded from all `files.list` responses returned for any user who doesn''t own the file. However, all users with access to the file can see the trashed item metadata in an API response. All users with access can copy, download, export, and share the file. *Note:* Files moved [...]'
      operationId: drive.files.trash
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/{fileId}/export:
    get:
      description: >-
        Exports a Google Workspace document to the requested MIME type and
        returns exported byte content. Note that the exported content is limited
        to 10MB.
      operationId: drive.files.export
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: files
      x-stackQL-verb: exec
  /files/{fileId}/comments:
    get:
      description: Lists a file's comments.
      operationId: drive.comments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: comments
      x-stackQL-verb: select
    post:
      description: Creates a new comment on the given file.
      operationId: drive.comments.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: comments
      x-stackQL-verb: insert
  /files/{fileId}/comments/{commentId}:
    get:
      description: Gets a comment by ID.
      operationId: drive.comments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: comments
      x-stackQL-verb: select
    delete:
      description: Deletes a comment.
      operationId: drive.comments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: comments
      x-stackQL-verb: delete
    patch:
      description: Updates an existing comment.
      operationId: drive.comments.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: comments
      x-stackQL-verb: exec
    put:
      description: Updates an existing comment.
      operationId: drive.comments.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: comments
      x-stackQL-verb: exec
  /files/{folderId}/children/{childId}:
    delete:
      description: Removes a child from a folder.
      operationId: drive.children.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: children
      x-stackQL-verb: delete
    get:
      description: Gets a specific child reference.
      operationId: drive.children.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: children
      x-stackQL-verb: select
  /files/{folderId}/children:
    get:
      description: Lists a folder's children.
      operationId: drive.children.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: children
      x-stackQL-verb: select
    post:
      description: Inserts a file into a folder.
      operationId: drive.children.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: children
      x-stackQL-verb: insert
  /channels/stop:
    post:
      description: Stops watching resources through this channel.
      operationId: drive.channels.stop
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.apps.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.apps.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: channels
      x-stackQL-verb: exec
  /files/{fileId}/parents/{parentId}:
    delete:
      description: Removes a parent from a file.
      operationId: drive.parents.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: parents
      x-stackQL-verb: delete
    get:
      description: Gets a specific parent reference.
      operationId: drive.parents.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: parents
      x-stackQL-verb: select
  /files/{fileId}/parents:
    get:
      description: Lists a file's parents.
      operationId: drive.parents.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.metadata.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.metadata.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.photos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.photos.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      x-stackQL-resource: parents
      x-stackQL-verb: select
    post:
      description: Adds a parent folder for a file.
      operationId: drive.parents.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      x-stackQL-resource: parents
      x-stackQL-verb: insert
