openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Gmail API
  description: >-
    The Gmail API lets you view and manage Gmail mailbox data like threads,
    messages, and labels.
  version: v1
  x-discovery-doc-revision: '20230619'
  x-generated-date: '2023-06-25'
servers:
  - url: https://gmail.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://mail.google.com/: >-
              Read, compose, send, and permanently delete all your email from
              Gmail
            https://www.googleapis.com/auth/gmail.addons.current.message.action: View your email messages when you interact with the add-on
            https://www.googleapis.com/auth/gmail.labels: See and edit your email labels
            https://www.googleapis.com/auth/gmail.addons.current.action.compose: Manage drafts and send emails when you interact with the add-on
            https://www.googleapis.com/auth/gmail.modify: Read, compose, and send emails from your Gmail account
            https://www.googleapis.com/auth/gmail.addons.current.message.readonly: View your email messages when the add-on is running
            https://www.googleapis.com/auth/gmail.send: Send email on your behalf
            https://www.googleapis.com/auth/gmail.settings.sharing: >-
              Manage your sensitive mail settings, including who can manage your
              mail
            https://www.googleapis.com/auth/gmail.addons.current.message.metadata: View your email message metadata when the add-on is running
            https://www.googleapis.com/auth/gmail.settings.basic: >-
              See, edit, create, or change your email settings and filters in
              Gmail
            https://www.googleapis.com/auth/gmail.metadata: >-
              View your email message metadata such as labels and headers, but
              not the email body
            https://www.googleapis.com/auth/gmail.compose: Manage drafts and send emails
            https://www.googleapis.com/auth/gmail.readonly: View your email messages and settings
            https://www.googleapis.com/auth/gmail.insert: Add emails into your Gmail mailbox
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /gmail/v1/users/{userId}/profile:
    get:
      description: Gets the current user's Gmail profile.
      operationId: gmail.users.getProfile
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.compose
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: users__profile
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/watch:
    post:
      description: Set up or update a push notification watch on the given user mailbox.
      operationId: gmail.users.watch
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: users
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/stop:
    post:
      description: Stop receiving push notifications for the given user mailbox.
      operationId: gmail.users.stop
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: users
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/drafts:
    get:
      description: Lists the drafts in the user's mailbox.
      operationId: gmail.users.drafts.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.compose
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: drafts
      x-stackQL-verb: select
    post:
      description: Creates a new draft with the `DRAFT` label.
      operationId: gmail.users.drafts.create
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.compose
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: drafts
      x-stackQL-verb: insert
  /gmail/v1/users/{userId}/drafts/{id}:
    put:
      description: Replaces a draft's content.
      operationId: gmail.users.drafts.update
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.compose
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: drafts
      x-stackQL-verb: exec
    delete:
      description: >-
        Immediately and permanently deletes the specified draft. Does not simply
        trash it.
      operationId: gmail.users.drafts.delete
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.compose
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: drafts
      x-stackQL-verb: delete
    get:
      description: Gets the specified draft.
      operationId: gmail.users.drafts.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.compose
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: drafts
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/drafts/send:
    post:
      description: >-
        Sends the specified, existing draft to the recipients in the `To`, `Cc`,
        and `Bcc` headers.
      operationId: gmail.users.drafts.send
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.compose
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: drafts
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}:
    get:
      description: Gets the specified message attachment.
      operationId: gmail.users.messages.attachments.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.action
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.action
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: attachments
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/messages:
    post:
      description: >-
        Directly inserts a message into only this user's mailbox similar to
        `IMAP APPEND`, bypassing most scanning and classification. Does not send
        a message.
      operationId: gmail.users.messages.insert
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.insert
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.insert
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: messages
      x-stackQL-verb: insert
    get:
      description: Lists the messages in the user's mailbox.
      operationId: gmail.users.messages.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: messages
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/messages/{id}:
    get:
      description: Gets the specified message.
      operationId: gmail.users.messages.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.action
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.action
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.metadata
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.metadata
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: messages
      x-stackQL-verb: select
    delete:
      description: >-
        Immediately and permanently deletes the specified message. This
        operation cannot be undone. Prefer `messages.trash` instead.
      operationId: gmail.users.messages.delete
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
      x-stackQL-resource: messages
      x-stackQL-verb: delete
  /gmail/v1/users/{userId}/messages/send:
    post:
      description: >-
        Sends the specified message to the recipients in the `To`, `Cc`, and
        `Bcc` headers. For example usage, see [Sending
        email](https://developers.google.com/gmail/api/guides/sending).
      operationId: gmail.users.messages.send
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.action.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.compose
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.compose
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.send
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.send
      x-stackQL-resource: messages
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/messages/import:
    post:
      description: >-
        Imports a message into only this user's mailbox, with standard email
        delivery scanning and classification similar to receiving via SMTP. This
        method doesn't perform SPF checks, so it might not work for some spam
        messages, such as those attempting to perform domain spoofing. This
        method does not send a message.
      operationId: gmail.users.messages.import
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.insert
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.insert
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: messages
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/messages/batchDelete:
    post:
      description: >-
        Deletes many messages by message ID. Provides no guarantees that
        messages were not already deleted or even existed at all.
      operationId: gmail.users.messages.batchDelete
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
      x-stackQL-resource: messages
      x-stackQL-verb: delete
  /gmail/v1/users/{userId}/messages/{id}/untrash:
    post:
      description: Removes the specified message from the trash.
      operationId: gmail.users.messages.untrash
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: messages
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/messages/batchModify:
    post:
      description: Modifies the labels on the specified messages.
      operationId: gmail.users.messages.batchModify
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: messages
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/messages/{id}/trash:
    post:
      description: Moves the specified message to the trash.
      operationId: gmail.users.messages.trash
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: messages
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/messages/{id}/modify:
    post:
      description: Modifies the labels on the specified message.
      operationId: gmail.users.messages.modify
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: messages
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/history:
    get:
      description: >-
        Lists the history of all changes to the given mailbox. History results
        are returned in chronological order (increasing `historyId`).
      operationId: gmail.users.history.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: history
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/threads/{id}/untrash:
    post:
      description: >-
        Removes the specified thread from the trash. Any messages that belong to
        the thread are also removed from the trash.
      operationId: gmail.users.threads.untrash
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: threads
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/threads/{id}:
    get:
      description: Gets the specified thread.
      operationId: gmail.users.threads.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.action
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.action
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.metadata
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.metadata
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/gmail.addons.current.message.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: threads
      x-stackQL-verb: select
    delete:
      description: >-
        Immediately and permanently deletes the specified thread. Any messages
        that belong to the thread are also deleted. This operation cannot be
        undone. Prefer `threads.trash` instead.
      operationId: gmail.users.threads.delete
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
      x-stackQL-resource: threads
      x-stackQL-verb: delete
  /gmail/v1/users/{userId}/threads/{id}/modify:
    post:
      description: >-
        Modifies the labels applied to the thread. This applies to all messages
        in the thread.
      operationId: gmail.users.threads.modify
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: threads
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/threads:
    get:
      description: Lists the threads in the user's mailbox.
      operationId: gmail.users.threads.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: threads
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/threads/{id}/trash:
    post:
      description: >-
        Moves the specified thread to the trash. Any messages that belong to the
        thread are also moved to the trash.
      operationId: gmail.users.threads.trash
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: threads
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/settings/cse/identities:
    post:
      description: >-
        Creates and configures a client-side encryption identity that's
        authorized to send mail from the user account. Google publishes the
        S/MIME certificate to a shared domain-wide directory so that people
        within a Google Workspace organization can encrypt and send mail to the
        identity.
      operationId: gmail.users.settings.cse.identities.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: identities
      x-stackQL-verb: insert
    get:
      description: Lists the client-side encrypted identities for an authenticated user.
      operationId: gmail.users.settings.cse.identities.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: identities
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}:
    get:
      description: Retrieves a client-side encryption identity configuration.
      operationId: gmail.users.settings.cse.identities.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: identities
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a client-side encryption identity. The authenticated user can no
        longer use the identity to send encrypted messages. You cannot restore
        the identity after you delete it. Instead, use the CreateCseIdentity
        method to create another identity with the same configuration.
      operationId: gmail.users.settings.cse.identities.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: identities
      x-stackQL-verb: delete
  /gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}:
    patch:
      description: >-
        Associates a different key pair with an existing client-side encryption
        identity. The updated key pair must validate against Google's [S/MIME
        certificate profiles](https://support.google.com/a/answer/7300887).
      operationId: gmail.users.settings.cse.identities.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: identities
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable:
    post:
      description: >-
        Turns off a client-side encryption key pair. The authenticated user can
        no longer use the key pair to decrypt incoming CSE message texts or sign
        outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on
        the key pair. After 30 days, you can permanently delete the key pair by
        using the ObliterateCseKeyPair method.
      operationId: gmail.users.settings.cse.keypairs.disable
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: keypairs
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/settings/cse/keypairs:
    post:
      description: >-
        Creates and uploads a client-side encryption S/MIME public key
        certificate chain and private key metadata for the authenticated user.
      operationId: gmail.users.settings.cse.keypairs.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: keypairs
      x-stackQL-verb: insert
    get:
      description: Lists client-side encryption key pairs for an authenticated user.
      operationId: gmail.users.settings.cse.keypairs.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: keypairs
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable:
    post:
      description: >-
        Turns on a client-side encryption key pair that was turned off. The key
        pair becomes active again for any associated client-side encryption
        identities.
      operationId: gmail.users.settings.cse.keypairs.enable
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: keypairs
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate:
    post:
      description: >-
        Deletes a client-side encryption key pair permanently and immediately.
        You can only permanently delete key pairs that have been turned off for
        more than 30 days. To turn off a key pair, use the DisableCseKeyPair
        method. Gmail can't restore or decrypt any messages that were encrypted
        by an obliterated key. Authenticated users and Google Workspace
        administrators lose access to reading the encrypted messages.
      operationId: gmail.users.settings.cse.keypairs.obliterate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: keypairs
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:
    get:
      description: Retrieves an existing client-side encryption key pair.
      operationId: gmail.users.settings.cse.keypairs.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: keypairs
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/forwardingAddresses:
    post:
      description: >-
        Creates a forwarding address. If ownership verification is required, a
        message will be sent to the recipient and the resource's verification
        status will be set to `pending`; otherwise, the resource will be created
        with verification status set to `accepted`. This method is only
        available to service account clients that have been delegated
        domain-wide authority.
      operationId: gmail.users.settings.forwardingAddresses.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: forwarding_addresses
      x-stackQL-verb: insert
    get:
      description: Lists the forwarding addresses for the specified account.
      operationId: gmail.users.settings.forwardingAddresses.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: forwarding_addresses
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}:
    delete:
      description: >-
        Deletes the specified forwarding address and revokes any verification
        that may have been required. This method is only available to service
        account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.forwardingAddresses.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: forwarding_addresses
      x-stackQL-verb: delete
    get:
      description: Gets the specified forwarding address.
      operationId: gmail.users.settings.forwardingAddresses.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: forwarding_addresses
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/delegates/{delegateEmail}:
    delete:
      description: >-
        Removes the specified delegate (which can be of any verification
        status), and revokes any verification that may have been required for
        using it. Note that a delegate user must be referred to by their primary
        email address, and not an email alias. This method is only available to
        service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.delegates.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: delegates
      x-stackQL-verb: delete
    get:
      description: >-
        Gets the specified delegate. Note that a delegate user must be referred
        to by their primary email address, and not an email alias. This method
        is only available to service account clients that have been delegated
        domain-wide authority.
      operationId: gmail.users.settings.delegates.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: delegates
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/delegates:
    post:
      description: >-
        Adds a delegate with its verification status set directly to `accepted`,
        without sending any verification email. The delegate user must be a
        member of the same Google Workspace organization as the delegator user.
        Gmail imposes limitations on the number of delegates and delegators each
        user in a Google Workspace organization can have. These limits depend on
        your organization, but in general each user can have up to 25 delegates
        and up to 10 delegators. Note that a delegate user must be referred to
        by their primary email address, and not an email alias. Also note that
        when a new delegate is created, there may be up to a one minute delay
        before the new delegate is available for use. This method is only
        available to service account clients that have been delegated
        domain-wide authority.
      operationId: gmail.users.settings.delegates.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: delegates
      x-stackQL-verb: insert
    get:
      description: >-
        Lists the delegates for the specified account. This method is only
        available to service account clients that have been delegated
        domain-wide authority.
      operationId: gmail.users.settings.delegates.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: delegates
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo:
    get:
      description: Lists S/MIME configs for the specified send-as alias.
      operationId: gmail.users.settings.sendAs.smimeInfo.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: smime_info
      x-stackQL-verb: select
    post:
      description: >-
        Insert (upload) the given S/MIME config for the specified send-as alias.
        Note that pkcs12 format is required for the key.
      operationId: gmail.users.settings.sendAs.smimeInfo.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: smime_info
      x-stackQL-verb: insert
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault:
    post:
      description: Sets the default S/MIME config for the specified send-as alias.
      operationId: gmail.users.settings.sendAs.smimeInfo.setDefault
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: smime_info
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}:
    delete:
      description: Deletes the specified S/MIME config for the specified send-as alias.
      operationId: gmail.users.settings.sendAs.smimeInfo.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: smime_info
      x-stackQL-verb: delete
    get:
      description: Gets the specified S/MIME config for the specified send-as alias.
      operationId: gmail.users.settings.sendAs.smimeInfo.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: smime_info
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}:
    get:
      description: >-
        Gets the specified send-as alias. Fails with an HTTP 404 error if the
        specified address is not a member of the collection.
      operationId: gmail.users.settings.sendAs.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: send_as
      x-stackQL-verb: select
    patch:
      description: Patch the specified send-as alias.
      operationId: gmail.users.settings.sendAs.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: send_as
      x-stackQL-verb: exec
    put:
      description: >-
        Updates a send-as alias. If a signature is provided, Gmail will sanitize
        the HTML before saving it with the alias. Addresses other than the
        primary address for the account can only be updated by service account
        clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.sendAs.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: send_as
      x-stackQL-verb: exec
    delete:
      description: >-
        Deletes the specified send-as alias. Revokes any verification that may
        have been required for using it. This method is only available to
        service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.sendAs.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: send_as
      x-stackQL-verb: delete
  /gmail/v1/users/{userId}/settings/sendAs:
    get:
      description: >-
        Lists the send-as aliases for the specified account. The result includes
        the primary send-as address associated with the account as well as any
        custom "from" aliases.
      operationId: gmail.users.settings.sendAs.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: send_as
      x-stackQL-verb: select
    post:
      description: >-
        Creates a custom "from" send-as alias. If an SMTP MSA is specified,
        Gmail will attempt to connect to the SMTP service to validate the
        configuration before creating the alias. If ownership verification is
        required for the alias, a message will be sent to the email address and
        the resource's verification status will be set to `pending`; otherwise,
        the resource will be created with verification status set to `accepted`.
        If a signature is provided, Gmail will sanitize the HTML before saving
        it with the alias. This method is only available to service account
        clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.sendAs.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: send_as
      x-stackQL-verb: insert
  /gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify:
    post:
      description: >-
        Sends a verification email to the specified send-as alias address. The
        verification status must be `pending`. This method is only available to
        service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.sendAs.verify
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: send_as
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/settings/filters/{id}:
    get:
      description: Gets a filter.
      operationId: gmail.users.settings.filters.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: filters
      x-stackQL-verb: select
    delete:
      description: Immediately and permanently deletes the specified filter.
      operationId: gmail.users.settings.filters.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: filters
      x-stackQL-verb: delete
  /gmail/v1/users/{userId}/settings/filters:
    get:
      description: Lists the message filters of a Gmail user.
      operationId: gmail.users.settings.filters.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: filters
      x-stackQL-verb: select
    post:
      description: 'Creates a filter. Note: you can only create a maximum of 1,000 filters.'
      operationId: gmail.users.settings.filters.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: filters
      x-stackQL-verb: insert
  /gmail/v1/users/{userId}/settings/language:
    get:
      description: Gets language settings.
      operationId: gmail.users.settings.getLanguage
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings__language
      x-stackQL-verb: select
    put:
      description: >-
        Updates language settings. If successful, the return object contains the
        `displayLanguage` that was saved for the user, which may differ from the
        value passed into the request. This is because the requested
        `displayLanguage` may not be directly supported by Gmail but have a
        close variant that is, and so the variant may be chosen and saved
        instead.
      operationId: gmail.users.settings.updateLanguage
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/settings/pop:
    put:
      description: Updates POP settings.
      operationId: gmail.users.settings.updatePop
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings
      x-stackQL-verb: exec
    get:
      description: Gets POP settings.
      operationId: gmail.users.settings.getPop
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings__pop
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/autoForwarding:
    put:
      description: >-
        Updates the auto-forwarding setting for the specified account. A
        verified forwarding address must be specified when auto-forwarding is
        enabled. This method is only available to service account clients that
        have been delegated domain-wide authority.
      operationId: gmail.users.settings.updateAutoForwarding
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.sharing
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.sharing
      x-stackQL-resource: settings
      x-stackQL-verb: exec
    get:
      description: Gets the auto-forwarding setting for the specified account.
      operationId: gmail.users.settings.getAutoForwarding
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings__auto_forwarding
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/imap:
    put:
      description: Updates IMAP settings.
      operationId: gmail.users.settings.updateImap
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings
      x-stackQL-verb: exec
    get:
      description: Gets IMAP settings.
      operationId: gmail.users.settings.getImap
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings__imap
      x-stackQL-verb: select
  /gmail/v1/users/{userId}/settings/vacation:
    get:
      description: Gets vacation responder settings.
      operationId: gmail.users.settings.getVacation
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings__vacation
      x-stackQL-verb: select
    put:
      description: Updates vacation responder settings.
      operationId: gmail.users.settings.updateVacation
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.settings.basic
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.settings.basic
      x-stackQL-resource: settings
      x-stackQL-verb: exec
  /gmail/v1/users/{userId}/labels:
    get:
      description: Lists all labels in the user's mailbox.
      operationId: gmail.users.labels.list
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.labels
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.labels
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: labels
      x-stackQL-verb: select
    post:
      description: Creates a new label.
      operationId: gmail.users.labels.create
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.labels
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.labels
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: labels
      x-stackQL-verb: insert
  /gmail/v1/users/{userId}/labels/{id}:
    get:
      description: Gets the specified label.
      operationId: gmail.users.labels.get
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.labels
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.labels
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.metadata
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.metadata
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.readonly
      x-stackQL-resource: labels
      x-stackQL-verb: select
    put:
      description: Updates the specified label.
      operationId: gmail.users.labels.update
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.labels
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.labels
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: labels
      x-stackQL-verb: exec
    patch:
      description: Patch the specified label.
      operationId: gmail.users.labels.patch
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.labels
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.labels
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: labels
      x-stackQL-verb: exec
    delete:
      description: >-
        Immediately and permanently deletes the specified label and removes it
        from any messages and threads that it is applied to.
      operationId: gmail.users.labels.delete
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.labels
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.labels
        - Oauth2:
            - https://www.googleapis.com/auth/gmail.modify
          Oauth2c:
            - https://www.googleapis.com/auth/gmail.modify
      x-stackQL-resource: labels
      x-stackQL-verb: delete
