openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: People API
  description: Provides access to information about profiles and contacts.
  version: v1
  x-discovery-doc-revision: '20230621'
  x-generated-date: '2023-06-25'
servers:
  - url: https://people.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/user.emails.read: See and download all of your Google Account email addresses
            https://www.googleapis.com/auth/user.addresses.read: View your street addresses
            https://www.googleapis.com/auth/userinfo.profile: >-
              See your personal info, including any personal info you've made
              publicly available
            https://www.googleapis.com/auth/userinfo.email: See your primary Google Account email address
            https://www.googleapis.com/auth/contacts: See, edit, download, and permanently delete your contacts
            https://www.googleapis.com/auth/contacts.other.readonly: >-
              See and download contact info automatically saved in your "Other
              contacts"
            https://www.googleapis.com/auth/directory.readonly: See and download your organization's GSuite directory
            https://www.googleapis.com/auth/user.gender.read: See your gender
            https://www.googleapis.com/auth/user.phonenumbers.read: See and download your personal phone numbers
            https://www.googleapis.com/auth/user.birthday.read: See and download your exact date of birth
            https://www.googleapis.com/auth/contacts.readonly: See and download your contacts
            https://www.googleapis.com/auth/user.organization.read: See your education, work history and org info
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/contactGroups:batchGet:
    get:
      description: >-
        Get a list of contact groups owned by the authenticated user by
        specifying a list of contact group resource names.
      operationId: people.contactGroups.batchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
      x-stackQL-resource: contact_groups
      x-stackQL-verb: select
  /v1/contactGroups:
    post:
      description: >-
        Create a new contact group owned by the authenticated user. Created
        contact group names must be unique to the users contact groups.
        Attempting to create a group with a duplicate name will return a HTTP
        409 error. Mutate requests for the same user should be sent sequentially
        to avoid increased latency and failures.
      operationId: people.contactGroups.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: contact_groups
      x-stackQL-verb: insert
    get:
      description: >-
        List all contact groups owned by the authenticated user. Members of the
        contact groups are not populated.
      operationId: people.contactGroups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
      x-stackQL-resource: contact_groups
      x-stackQL-verb: select
  /v1/contactGroups/{contactGroupsId}:
    get:
      description: >-
        Get a specific contact group owned by the authenticated user by
        specifying a contact group resource name.
      operationId: people.contactGroups.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
      x-stackQL-resource: contact_groups
      x-stackQL-verb: select
    delete:
      description: >-
        Delete an existing contact group owned by the authenticated user by
        specifying a contact group resource name. Mutate requests for the same
        user should be sent sequentially to avoid increased latency and
        failures.
      operationId: people.contactGroups.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: contact_groups
      x-stackQL-verb: delete
    put:
      description: >-
        Update the name of an existing contact group owned by the authenticated
        user. Updated contact group names must be unique to the users contact
        groups. Attempting to create a group with a duplicate name will return a
        HTTP 409 error. Mutate requests for the same user should be sent
        sequentially to avoid increased latency and failures.
      operationId: people.contactGroups.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: contact_groups
      x-stackQL-verb: exec
  /v1/contactGroups/{contactGroupsId}/members:modify:
    post:
      description: >-
        Modify the members of a contact group owned by the authenticated user.
        The only system contact groups that can have members added are
        `contactGroups/myContacts` and `contactGroups/starred`. Other system
        contact groups are deprecated and can only have contacts removed.
      operationId: people.contactGroups.members.modify
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: members
      x-stackQL-verb: exec
  /v1/people/{peopleId}/connections:
    get:
      description: >-
        Provides a list of the authenticated user's contacts. Sync tokens expire
        7 days after the full sync. A request with an expired sync token will
        get an error with an
        [google.rpc.ErrorInfo](https://cloud.google.com/apis/design/errors#error_info)
        with reason "EXPIRED_SYNC_TOKEN". In the case of such an error clients
        should make a full sync request without a `sync_token`. The first page
        of a full sync request has an additional quota. If the quota is
        exceeded, a 429 error will be returned. This quota is fixed and can not
        be increased. When the `sync_token` is specified, resources deleted
        since the last sync will be returned as a person with
        `PersonMetadata.deleted` set to true. When the `page_token` or
        `sync_token` is specified, all other request parameters must match the
        first call. Writes may have a propagation delay of several minutes for
        sync requests. Incremental syncs are not intended for read-after-write
        use cases. See example usage at [List the user's contacts that have
        changed](/people/v1/contacts#list_the_users_contacts_that_have_changed).
      operationId: people.people.connections.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
      x-stackQL-resource: connections
      x-stackQL-verb: select
  /v1/people:batchGet:
    get:
      description: >-
        Provides information about a list of specific people by specifying a
        list of requested resource names. Use `people/me` to indicate the
        authenticated user. The request returns a 400 error if 'personFields' is
        not specified.
      operationId: people.people.getBatchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/directory.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/directory.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/user.addresses.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.addresses.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.birthday.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.birthday.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.emails.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.emails.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.gender.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.gender.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.organization.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.organization.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.phonenumbers.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.phonenumbers.read
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.email
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.email
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.profile
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.profile
      x-stackQL-resource: people__batch_get
      x-stackQL-verb: select
  /v1/people:searchDirectoryPeople:
    get:
      description: >-
        Provides a list of domain profiles and domain contacts in the
        authenticated user's domain directory that match the search query.
      operationId: people.people.searchDirectoryPeople
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/directory.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/directory.readonly
      x-stackQL-resource: people
      x-stackQL-verb: exec
  /v1/people:createContact:
    post:
      description: >-
        Create a new contact and return the person resource for that contact.
        The request returns a 400 error if more than one field is specified on a
        field that is a singleton for contact sources: * biographies * birthdays
        * genders * names Mutate requests for the same user should be sent
        sequentially to avoid increased latency and failures.
      operationId: people.people.createContact
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: people__contact
      x-stackQL-verb: insert
  /v1/people/{peopleId}:deleteContactPhoto:
    delete:
      description: >-
        Delete a contact's photo. Mutate requests for the same user should be
        done sequentially to avoid // lock contention.
      operationId: people.people.deleteContactPhoto
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: people__contact_photo
      x-stackQL-verb: delete
  /v1/people:listDirectoryPeople:
    get:
      description: >-
        Provides a list of domain profiles and domain contacts in the
        authenticated user's domain directory. When the `sync_token` is
        specified, resources deleted since the last sync will be returned as a
        person with `PersonMetadata.deleted` set to true. When the `page_token`
        or `sync_token` is specified, all other request parameters must match
        the first call. Writes may have a propagation delay of several minutes
        for sync requests. Incremental syncs are not intended for
        read-after-write use cases. See example usage at [List the directory
        people that have
        changed](/people/v1/directory#list_the_directory_people_that_have_changed).
      operationId: people.people.listDirectoryPeople
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/directory.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/directory.readonly
      x-stackQL-resource: people__directory_people
      x-stackQL-verb: select
  /v1/people/{peopleId}:
    get:
      description: >-
        Provides information about a person by specifying a resource name. Use
        `people/me` to indicate the authenticated user. The request returns a
        400 error if 'personFields' is not specified.
      operationId: people.people.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/directory.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/directory.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/user.addresses.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.addresses.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.birthday.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.birthday.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.emails.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.emails.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.gender.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.gender.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.organization.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.organization.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.phonenumbers.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.phonenumbers.read
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.email
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.email
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.profile
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.profile
      x-stackQL-resource: people
      x-stackQL-verb: select
  /v1/people/{peopleId}:deleteContact:
    delete:
      description: >-
        Delete a contact person. Any non-contact data will not be deleted.
        Mutate requests for the same user should be sent sequentially to avoid
        increased latency and failures.
      operationId: people.people.deleteContact
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: people__contact
      x-stackQL-verb: delete
  /v1/people:searchContacts:
    get:
      description: >-
        Provides a list of contacts in the authenticated user's grouped contacts
        that matches the search query. The query matches on a contact's `names`,
        `nickNames`, `emailAddresses`, `phoneNumbers`, and `organizations`
        fields that are from the CONTACT source. **IMPORTANT**: Before
        searching, clients should send a warmup request with an empty query to
        update the cache. See
        https://developers.google.com/people/v1/contacts#search_the_users_contacts
      operationId: people.people.searchContacts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
      x-stackQL-resource: people
      x-stackQL-verb: exec
  /v1/people/{peopleId}:updateContact:
    patch:
      description: >-
        Update contact data for an existing contact person. Any non-contact data
        will not be modified. Any non-contact data in the person to update will
        be ignored. All fields specified in the `update_mask` will be replaced.
        The server returns a 400 error if `person.metadata.sources` is not
        specified for the contact to be updated or if there is no contact
        source. The server returns a 400 error with reason
        `"failedPrecondition"` if `person.metadata.sources.etag` is different
        than the contact's etag, which indicates the contact has changed since
        its data was read. Clients should get the latest person and merge their
        updates into the latest person. The server returns a 400 error if
        `memberships` are being updated and there are no contact group
        memberships specified on the person. The server returns a 400 error if
        more than one field is specified on a field that is a singleton for
        contact sources: * biographies * birthdays * genders * names Mutate
        requests for the same user should be sent sequentially to avoid
        increased latency and failures.
      operationId: people.people.updateContact
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: people
      x-stackQL-verb: exec
  /v1/people:batchUpdateContacts:
    post:
      description: >-
        Update a batch of contacts and return a map of resource names to
        PersonResponses for the updated contacts. Mutate requests for the same
        user should be sent sequentially to avoid increased latency and
        failures.
      operationId: people.people.batchUpdateContacts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: people
      x-stackQL-verb: exec
  /v1/people:batchDeleteContacts:
    post:
      description: >-
        Delete a batch of contacts. Any non-contact data will not be deleted.
        Mutate requests for the same user should be sent sequentially to avoid
        increased latency and failures.
      operationId: people.people.batchDeleteContacts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: people
      x-stackQL-verb: exec
  /v1/people:batchCreateContacts:
    post:
      description: >-
        Create a batch of new contacts and return the PersonResponses for the
        newly Mutate requests for the same user should be sent sequentially to
        avoid increased latency and failures.
      operationId: people.people.batchCreateContacts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: people
      x-stackQL-verb: exec
  /v1/people/{peopleId}:updateContactPhoto:
    patch:
      description: >-
        Update a contact's photo. Mutate requests for the same user should be
        sent sequentially to avoid increased latency and failures.
      operationId: people.people.updateContactPhoto
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      x-stackQL-resource: people
      x-stackQL-verb: exec
  /v1/otherContacts:search:
    get:
      description: >-
        Provides a list of contacts in the authenticated user's other contacts
        that matches the search query. The query matches on a contact's `names`,
        `emailAddresses`, and `phoneNumbers` fields that are from the
        OTHER_CONTACT source. **IMPORTANT**: Before searching, clients should
        send a warmup request with an empty query to update the cache. See
        https://developers.google.com/people/v1/other-contacts#search_the_users_other_contacts
      operationId: people.otherContacts.search
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.other.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.other.readonly
      x-stackQL-resource: other_contacts
      x-stackQL-verb: exec
  /v1/otherContacts/{otherContactsId}:copyOtherContactToMyContactsGroup:
    post:
      description: >-
        Copies an "Other contact" to a new contact in the user's "myContacts"
        group Mutate requests for the same user should be sent sequentially to
        avoid increased latency and failures.
      operationId: people.otherContacts.copyOtherContactToMyContactsGroup
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.other.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.other.readonly
      x-stackQL-resource: other_contacts
      x-stackQL-verb: exec
  /v1/otherContacts:
    get:
      description: >-
        List all "Other contacts", that is contacts that are not in a contact
        group. "Other contacts" are typically auto created contacts from
        interactions. Sync tokens expire 7 days after the full sync. A request
        with an expired sync token will get an error with an
        [google.rpc.ErrorInfo](https://cloud.google.com/apis/design/errors#error_info)
        with reason "EXPIRED_SYNC_TOKEN". In the case of such an error clients
        should make a full sync request without a `sync_token`. The first page
        of a full sync request has an additional quota. If the quota is
        exceeded, a 429 error will be returned. This quota is fixed and can not
        be increased. When the `sync_token` is specified, resources deleted
        since the last sync will be returned as a person with
        `PersonMetadata.deleted` set to true. When the `page_token` or
        `sync_token` is specified, all other request parameters must match the
        first call. Writes may have a propagation delay of several minutes for
        sync requests. Incremental syncs are not intended for read-after-write
        use cases. See example usage at [List the user's other contacts that
        have
        changed](/people/v1/other-contacts#list_the_users_other_contacts_that_have_changed).
      operationId: people.otherContacts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.other.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.other.readonly
      x-stackQL-resource: other_contacts
      x-stackQL-verb: select
