openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Cloud Identity API
  description: API for provisioning and managing identity resources.
  version: v1
  x-discovery-doc-revision: '20230619'
  x-generated-date: '2023-06-25'
servers:
  - url: https://cloudidentity.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/cloud-identity.groups.readonly: >-
              See any Cloud Identity Groups that you can access, including group
              members and their emails
            https://www.googleapis.com/auth/cloud-identity.devices: >-
              Private Service:
              https://www.googleapis.com/auth/cloud-identity.devices
            https://www.googleapis.com/auth/cloud-identity.devices.readonly: >-
              Private Service:
              https://www.googleapis.com/auth/cloud-identity.devices.readonly
            https://www.googleapis.com/auth/cloud-identity.devices.lookup: See your device details
            https://www.googleapis.com/auth/cloud-platform: >-
              See, edit, configure, and delete your Google Cloud data and see
              the email address for your Google Account.
            https://www.googleapis.com/auth/cloud-identity.groups: >-
              See, change, create, and delete any of the Cloud Identity Groups
              that you can access, including the members of each group
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/customers/{customersId}/userinvitations/{userinvitationsId}:
    get:
      description: >-
        Retrieves a UserInvitation resource. **Note:** New consumer accounts
        with the customer's verified domain created within the previous 48 hours
        will not appear in the result. This delay also applies to newly-verified
        domains.
      operationId: cloudidentity.customers.userinvitations.get
      security: []
      x-stackQL-resource: userinvitations
      x-stackQL-verb: select
  /v1/customers/{customersId}/userinvitations:
    get:
      description: >-
        Retrieves a list of UserInvitation resources. **Note:** New consumer
        accounts with the customer's verified domain created within the previous
        48 hours will not appear in the result. This delay also applies to
        newly-verified domains.
      operationId: cloudidentity.customers.userinvitations.list
      security: []
      x-stackQL-resource: userinvitations
      x-stackQL-verb: select
  /v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel:
    post:
      description: Cancels a UserInvitation that was already sent.
      operationId: cloudidentity.customers.userinvitations.cancel
      security: []
      x-stackQL-resource: userinvitations
      x-stackQL-verb: exec
  /v1/customers/{customersId}/userinvitations/{userinvitationsId}:send:
    post:
      description: >-
        Sends a UserInvitation to email. If the `UserInvitation` does not exist
        for this request and it is a valid request, the request creates a
        `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour
        delay where newly-created consumer accounts will not appear in the
        results. You can still send a `UserInvitation` to those accounts if you
        know the unmanaged email address and IsInvitableUser==True.
      operationId: cloudidentity.customers.userinvitations.send
      security: []
      x-stackQL-resource: userinvitations
      x-stackQL-verb: exec
  /v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser:
    get:
      description: >-
        Verifies whether a user account is eligible to receive a UserInvitation
        (is an unmanaged account). Eligibility is based on the following
        criteria: * the email address is a consumer account and it's the primary
        email address of the account, and * the domain of the email address
        matches an existing verified Google Workspace or Cloud Identity domain
        If both conditions are met, the user is eligible. **Note:** This method
        is not supported for Workspace Essentials customers.
      operationId: cloudidentity.customers.userinvitations.isInvitableUser
      security: []
      x-stackQL-resource: userinvitations
      x-stackQL-verb: exec
  /v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:
    get:
      description: Returns a list of IdpCredentials in an InboundSamlSsoProfile.
      operationId: cloudidentity.inboundSamlSsoProfiles.idpCredentials.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: idp_credentials
      x-stackQL-verb: select
  /v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}:
    get:
      description: Gets an IdpCredential.
      operationId: cloudidentity.inboundSamlSsoProfiles.idpCredentials.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: idp_credentials
      x-stackQL-verb: select
    delete:
      description: Deletes an IdpCredential.
      operationId: cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: idp_credentials
      x-stackQL-verb: delete
  /v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add:
    post:
      description: Adds an IdpCredential. Up to 2 credentials are allowed.
      operationId: cloudidentity.inboundSamlSsoProfiles.idpCredentials.add
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: idp_credentials
      x-stackQL-verb: insert
  /v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}:
    patch:
      description: Updates an InboundSamlSsoProfile.
      operationId: cloudidentity.inboundSamlSsoProfiles.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_saml_sso_profiles
      x-stackQL-verb: exec
    delete:
      description: Deletes an InboundSamlSsoProfile.
      operationId: cloudidentity.inboundSamlSsoProfiles.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_saml_sso_profiles
      x-stackQL-verb: delete
    get:
      description: Gets an InboundSamlSsoProfile.
      operationId: cloudidentity.inboundSamlSsoProfiles.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_saml_sso_profiles
      x-stackQL-verb: select
  /v1/inboundSamlSsoProfiles:
    post:
      description: Creates an InboundSamlSsoProfile for a customer.
      operationId: cloudidentity.inboundSamlSsoProfiles.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_saml_sso_profiles
      x-stackQL-verb: insert
    get:
      description: Lists InboundSamlSsoProfiles for a customer.
      operationId: cloudidentity.inboundSamlSsoProfiles.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_saml_sso_profiles
      x-stackQL-verb: select
  /v1/groups/{groupsId}/memberships:searchTransitiveMemberships:
    get:
      description: >-
        Search transitive memberships of a group. **Note:** This feature is only
        available to Google Workspace Enterprise Standard, Enterprise Plus, and
        Enterprise for Education; and Cloud Identity Premium accounts. If the
        account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP
        status code will be returned. A transitive membership is any direct or
        indirect membership of a group. Actor must have view permissions to all
        transitive memberships.
      operationId: cloudidentity.groups.memberships.searchTransitiveMemberships
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: exec
  /v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles:
    post:
      description: Modifies the `MembershipRole`s of a `Membership`.
      operationId: cloudidentity.groups.memberships.modifyMembershipRoles
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: exec
  /v1/groups/{groupsId}/memberships:searchTransitiveGroups:
    get:
      description: >-
        Search transitive groups of a member. **Note:** This feature is only
        available to Google Workspace Enterprise Standard, Enterprise Plus, and
        Enterprise for Education; and Cloud Identity Premium accounts. If the
        account of the member is not one of these, a 403 (PERMISSION_DENIED)
        HTTP status code will be returned. A transitive group is any group that
        has a direct or indirect membership to the member. Actor must have view
        permissions all transitive groups.
      operationId: cloudidentity.groups.memberships.searchTransitiveGroups
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: exec
  /v1/groups/{groupsId}/memberships:getMembershipGraph:
    get:
      description: >-
        Get a membership graph of just a member or both a member and a group.
        **Note:** This feature is only available to Google Workspace Enterprise
        Standard, Enterprise Plus, and Enterprise for Education; and Cloud
        Identity Premium accounts. If the account of the member is not one of
        these, a 403 (PERMISSION_DENIED) HTTP status code will be returned.
        Given a member, the response will contain all membership paths from the
        member. Given both a group and a member, the response will contain all
        membership paths between the group and the member.
      operationId: cloudidentity.groups.memberships.getMembershipGraph
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships__membership_graph
      x-stackQL-verb: select
  /v1/groups/{groupsId}/memberships:searchDirectGroups:
    get:
      description: Searches direct groups of a member.
      operationId: cloudidentity.groups.memberships.searchDirectGroups
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: exec
  /v1/groups/{groupsId}/memberships/{membershipsId}:
    get:
      description: Retrieves a `Membership`.
      operationId: cloudidentity.groups.memberships.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: select
    delete:
      description: Deletes a `Membership`.
      operationId: cloudidentity.groups.memberships.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: delete
  /v1/groups/{groupsId}/memberships:
    post:
      description: Creates a `Membership`.
      operationId: cloudidentity.groups.memberships.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: insert
    get:
      description: Lists the `Membership`s within a `Group`.
      operationId: cloudidentity.groups.memberships.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: select
  /v1/groups/{groupsId}/memberships:checkTransitiveMembership:
    get:
      description: >-
        Check a potential member for membership in a group. **Note:** This
        feature is only available to Google Workspace Enterprise Standard,
        Enterprise Plus, and Enterprise for Education; and Cloud Identity
        Premium accounts. If the account of the member is not one of these, a
        403 (PERMISSION_DENIED) HTTP status code will be returned. A member has
        membership to a group as long as there is a single viewable transitive
        membership between the group and the member. The actor must have view
        permissions to at least one transitive membership between the member and
        group.
      operationId: cloudidentity.groups.memberships.checkTransitiveMembership
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: exec
  /v1/groups/{groupsId}/memberships:lookup:
    get:
      description: >-
        Looks up the [resource
        name](https://cloud.google.com/apis/design/resource_names) of a
        `Membership` by its `EntityKey`.
      operationId: cloudidentity.groups.memberships.lookup
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: memberships
      x-stackQL-verb: exec
  /v1/groups:lookup:
    get:
      description: >-
        Looks up the [resource
        name](https://cloud.google.com/apis/design/resource_names) of a `Group`
        by its `EntityKey`.
      operationId: cloudidentity.groups.lookup
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups
      x-stackQL-verb: exec
  /v1/groups:
    get:
      description: Lists the `Group` resources under a customer or namespace.
      operationId: cloudidentity.groups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups
      x-stackQL-verb: select
    post:
      description: Creates a Group.
      operationId: cloudidentity.groups.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups
      x-stackQL-verb: insert
  /v1/groups:search:
    get:
      description: Searches for `Group` resources matching a specified query.
      operationId: cloudidentity.groups.search
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups
      x-stackQL-verb: exec
  /v1/groups/{groupsId}:
    get:
      description: Retrieves a `Group`.
      operationId: cloudidentity.groups.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups
      x-stackQL-verb: select
    delete:
      description: Deletes a `Group`.
      operationId: cloudidentity.groups.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups
      x-stackQL-verb: delete
    patch:
      description: Updates a `Group`.
      operationId: cloudidentity.groups.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups
      x-stackQL-verb: exec
  /v1/groups/{groupsId}/securitySettings:
    get:
      description: Get Security Settings
      operationId: cloudidentity.groups.getSecuritySettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups__security_settings
      x-stackQL-verb: select
    patch:
      description: Update Security Settings
      operationId: cloudidentity.groups.updateSecuritySettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.groups
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.groups
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: groups
      x-stackQL-verb: exec
  /v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve:
    post:
      description: Approves device to access user data.
      operationId: cloudidentity.devices.deviceUsers.approve
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: device_users
      x-stackQL-verb: exec
  /v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:
    get:
      description: Retrieves the specified DeviceUser
      operationId: cloudidentity.devices.deviceUsers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      x-stackQL-resource: device_users
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes the specified DeviceUser. This also revokes the user's access to
        device data.
      operationId: cloudidentity.devices.deviceUsers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: device_users
      x-stackQL-verb: delete
  /v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe:
    post:
      description: >-
        Cancels an unfinished user account wipe. This operation can be used to
        cancel device wipe in the gap between the wipe operation returning
        success and the device being wiped.
      operationId: cloudidentity.devices.deviceUsers.cancelWipe
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: device_users
      x-stackQL-verb: exec
  /v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block:
    post:
      description: Blocks device from accessing user data
      operationId: cloudidentity.devices.deviceUsers.block
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: device_users
      x-stackQL-verb: exec
  /v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe:
    post:
      description: >-
        Wipes the user's account on a device. Other data on the device that is
        not associated with the user's work account is not affected. For
        example, if a Gmail app is installed on a device that is used for
        personal and work purposes, and the user is logged in to the Gmail app
        with their personal account as well as their work account, wiping the
        "deviceUser" by their work administrator will not affect their personal
        account within Gmail or other apps such as Photos.
      operationId: cloudidentity.devices.deviceUsers.wipe
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: device_users
      x-stackQL-verb: exec
  /v1/devices/{devicesId}/deviceUsers:
    get:
      description: Lists/Searches DeviceUsers.
      operationId: cloudidentity.devices.deviceUsers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      x-stackQL-resource: device_users
      x-stackQL-verb: select
  /v1/devices/{devicesId}/deviceUsers:lookup:
    get:
      description: >-
        Looks up resource names of the DeviceUsers associated with the caller's
        credentials, as well as the properties provided in the request. This
        method must be called with end-user credentials with the scope:
        https://www.googleapis.com/auth/cloud-identity.devices.lookup If
        multiple properties are provided, only DeviceUsers having all of these
        properties are considered as matches - i.e. the query behaves like an
        AND. Different platforms require different amounts of information from
        the caller to ensure that the DeviceUser is uniquely identified. - iOS:
        No properties need to be passed, the caller's credentials are sufficient
        to identify the corresponding DeviceUser. - Android: Specifying the
        'android_id' field is required. - Desktop: Specifying the
        'raw_resource_id' field is required.
      operationId: cloudidentity.devices.deviceUsers.lookup
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices.lookup
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices.lookup
      x-stackQL-resource: device_users
      x-stackQL-verb: exec
  /v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates:
    get:
      description: Lists the client states for the given search query.
      operationId: cloudidentity.devices.deviceUsers.clientStates.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      x-stackQL-resource: client_states
      x-stackQL-verb: select
  /v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}:
    patch:
      description: >-
        Updates the client state for the device user **Note**: This method is
        available only to customers who have one of the following SKUs:
        Enterprise Standard, Enterprise Plus, Enterprise for Education, and
        Cloud Identity Premium
      operationId: cloudidentity.devices.deviceUsers.clientStates.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: client_states
      x-stackQL-verb: exec
    get:
      description: Gets the client state for the device user
      operationId: cloudidentity.devices.deviceUsers.clientStates.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      x-stackQL-resource: client_states
      x-stackQL-verb: select
  /v1/devices/{devicesId}:cancelWipe:
    post:
      description: >-
        Cancels an unfinished device wipe. This operation can be used to cancel
        device wipe in the gap between the wipe operation returning success and
        the device being wiped. This operation is possible when the device is in
        a "pending wipe" state. The device enters the "pending wipe" state when
        a wipe device command is issued, but has not yet been sent to the
        device. The cancel wipe will fail if the wipe command has already been
        issued to the device.
      operationId: cloudidentity.devices.cancelWipe
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: devices
      x-stackQL-verb: exec
  /v1/devices/{devicesId}:wipe:
    post:
      description: Wipes all data on the specified device.
      operationId: cloudidentity.devices.wipe
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: devices
      x-stackQL-verb: exec
  /v1/devices/{devicesId}:
    get:
      description: Retrieves the specified device.
      operationId: cloudidentity.devices.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      x-stackQL-resource: devices
      x-stackQL-verb: select
    delete:
      description: Deletes the specified device.
      operationId: cloudidentity.devices.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: devices
      x-stackQL-verb: delete
  /v1/devices:
    get:
      description: Lists/Searches devices.
      operationId: cloudidentity.devices.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      x-stackQL-resource: devices
      x-stackQL-verb: select
    post:
      description: >-
        Creates a device. Only company-owned device may be created. **Note**:
        This method is available only to customers who have one of the following
        SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education,
        and Cloud Identity Premium
      operationId: cloudidentity.devices.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-identity.devices
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-identity.devices
      x-stackQL-resource: devices
      x-stackQL-verb: insert
  /v1/inboundSsoAssignments:
    post:
      description: >-
        Creates an InboundSsoAssignment for users and devices in a `Customer`
        under a given `Group` or `OrgUnit`.
      operationId: cloudidentity.inboundSsoAssignments.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_sso_assignments
      x-stackQL-verb: insert
    get:
      description: Lists the InboundSsoAssignments for a `Customer`.
      operationId: cloudidentity.inboundSsoAssignments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_sso_assignments
      x-stackQL-verb: select
  /v1/inboundSsoAssignments/{inboundSsoAssignmentsId}:
    delete:
      description: >-
        Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an
        assignment that has `sso_mode` == `SSO_OFF`.
      operationId: cloudidentity.inboundSsoAssignments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_sso_assignments
      x-stackQL-verb: delete
    get:
      description: Gets an InboundSsoAssignment.
      operationId: cloudidentity.inboundSsoAssignments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_sso_assignments
      x-stackQL-verb: select
    patch:
      description: >-
        Updates an InboundSsoAssignment. The body of this request is the
        `inbound_sso_assignment` field and the `update_mask` is relative to
        that. For example: a PATCH to
        `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body
        of `{ "rank": 1 }` moves that (presumably group-targeted) SSO assignment
        to the highest priority and shifts any other group-targeted assignments
        down in priority.
      operationId: cloudidentity.inboundSsoAssignments.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: inbound_sso_assignments
      x-stackQL-verb: exec
