openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Keep API
  description: >-
    The Google Keep API is used in an enterprise environment to manage Google
    Keep content and resolve issues identified by cloud security software.
  version: v1
  x-discovery-doc-revision: '20230615'
  x-generated-date: '2023-06-25'
servers:
  - url: https://keep.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/keep.readonly: View all your Google Keep data
            https://www.googleapis.com/auth/keep: See, edit, create and permanently delete all your Google Keep data
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/notes/{notesId}/attachments/{attachmentsId}:
    get:
      description: >-
        Gets an attachment. To download attachment media via REST requires the
        alt=media query parameter. Returns a 400 bad request error if attachment
        media is not available in the requested MIME type.
      operationId: keep.media.download
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
        - Oauth2:
            - https://www.googleapis.com/auth/keep.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/keep.readonly
      x-stackQL-resource: media
      x-stackQL-verb: exec
  /v1/notes:
    post:
      description: Creates a new note.
      operationId: keep.notes.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
      x-stackQL-resource: notes
      x-stackQL-verb: insert
    get:
      description: >-
        Lists notes. Every list call returns a page of results with `page_size`
        as the upper bound of returned items. A `page_size` of zero allows the
        server to choose the upper bound. The ListNotesResponse contains at most
        `page_size` entries. If there are more things left to list, it provides
        a `next_page_token` value. (Page tokens are opaque values.) To get the
        next page of results, copy the result's `next_page_token` into the next
        request's `page_token`. Repeat until the `next_page_token` returned with
        a page of results is empty. ListNotes return consistent results in the
        face of concurrent changes, or signals that it cannot with an ABORTED
        error.
      operationId: keep.notes.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
        - Oauth2:
            - https://www.googleapis.com/auth/keep.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/keep.readonly
      x-stackQL-resource: notes
      x-stackQL-verb: select
  /v1/notes/{notesId}:
    get:
      description: Gets a note.
      operationId: keep.notes.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
        - Oauth2:
            - https://www.googleapis.com/auth/keep.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/keep.readonly
      x-stackQL-resource: notes
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a note. Caller must have the `OWNER` role on the note to delete.
        Deleting a note removes the resource immediately and cannot be undone.
        Any collaborators will lose access to the note.
      operationId: keep.notes.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
      x-stackQL-resource: notes
      x-stackQL-verb: delete
  /v1/notes/{notesId}/permissions:batchDelete:
    post:
      description: >-
        Deletes one or more permissions on the note. The specified entities will
        immediately lose access. A permission with the `OWNER` role can't be
        removed. If removing a permission fails, then the entire request fails
        and no changes are made. Returns a 400 bad request error if a specified
        permission does not exist on the note.
      operationId: keep.notes.permissions.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
      x-stackQL-resource: permissions
      x-stackQL-verb: delete
  /v1/notes/{notesId}/permissions:batchCreate:
    post:
      description: >-
        Creates one or more permissions on the note. Only permissions with the
        `WRITER` role may be created. If adding any permission fails, then the
        entire request fails and no changes are made.
      operationId: keep.notes.permissions.batchCreate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
      x-stackQL-resource: permissions
      x-stackQL-verb: insert
