openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Cloud Channel API
  description: >-
    The Cloud Channel API enables Google Cloud partners to have a single unified
    resale platform and APIs across all of Google Cloud including GCP,
    Workspace, Maps and Chrome.
  version: v1
  x-discovery-doc-revision: '20230621'
  x-generated-date: '2023-06-25'
servers:
  - url: https://cloudchannel.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/apps.order: Manage users on your domain
            https://www.googleapis.com/auth/apps.reports.usage.readonly: View usage reports for your G Suite domain
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/operations/{operationsId}:
    delete:
      description: >-
        Deletes a long-running operation. This method indicates that the client
        is no longer interested in the operation result. It does not cancel the
        operation. If the server doesn't support this method, it returns
        `google.rpc.Code.UNIMPLEMENTED`.
      operationId: cloudchannel.operations.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: operations
      x-stackQL-verb: delete
    get:
      description: >-
        Gets the latest state of a long-running operation. Clients can use this
        method to poll the operation result at intervals as recommended by the
        API service.
      operationId: cloudchannel.operations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: operations
      x-stackQL-verb: select
  /v1/operations/{operationsId}:cancel:
    post:
      description: >-
        Starts asynchronous cancellation on a long-running operation. The server
        makes a best effort to cancel the operation, but success is not
        guaranteed. If the server doesn't support this method, it returns
        `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation
        or other methods to check whether the cancellation succeeded or whether
        the operation completed despite cancellation. On successful
        cancellation, the operation is not deleted; instead, it becomes an
        operation with an Operation.error value with a google.rpc.Status.code of
        1, corresponding to `Code.CANCELLED`.
      operationId: cloudchannel.operations.cancel
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: operations
      x-stackQL-verb: exec
  /v1/operations:
    get:
      description: >-
        Lists operations that match the specified filter in the request. If the
        server doesn't support this method, it returns `UNIMPLEMENTED`.
      operationId: cloudchannel.operations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: operations
      x-stackQL-verb: select
  /v1/products/{productsId}/skus:
    get:
      description: >-
        Lists the SKUs for a product the reseller is authorized to sell.
        Possible error codes: * INVALID_ARGUMENT: Required request parameters
        are missing or invalid.
      operationId: cloudchannel.products.skus.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: skus
      x-stackQL-verb: select
  /v1/products:
    get:
      description: >-
        Lists the Products the reseller is authorized to sell. Possible error
        codes: * INVALID_ARGUMENT: Required request parameters are missing or
        invalid.
      operationId: cloudchannel.products.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: products
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/offers:
    get:
      description: >-
        Lists the Offers the reseller can sell. Possible error codes: *
        INVALID_ARGUMENT: Required request parameters are missing or invalid.
      operationId: cloudchannel.accounts.offers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: offers
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/customers:
    get:
      description: >-
        List Customers. Possible error codes: * PERMISSION_DENIED: The reseller
        account making the request is different from the reseller account in the
        API request. * INVALID_ARGUMENT: Required request parameters are missing
        or invalid. Return value: List of Customers, or an empty list if there
        are no customers.
      operationId: cloudchannel.accounts.customers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: select
    post:
      description: >-
        Creates a new Customer resource under the reseller or distributor
        account. Possible error codes: * PERMISSION_DENIED: The reseller account
        making the request is different from the reseller account in the API
        request. * INVALID_ARGUMENT: * Required request parameters are missing
        or invalid. * Domain field value doesn't match the primary email domain.
        Return value: The newly created Customer resource.
      operationId: cloudchannel.accounts.customers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: insert
  /v1/accounts/{accountsId}/customers:import:
    post:
      description: >-
        Imports a Customer from the Cloud Identity associated with the provided
        Cloud Identity ID or domain before a TransferEntitlements call. If a
        linked Customer already exists and overwrite_if_exists is true, it will
        update that Customer's data. Possible error codes: * PERMISSION_DENIED:
        The reseller account making the request is different from the reseller
        account in the API request. * NOT_FOUND: Cloud Identity doesn't exist or
        was deleted. * INVALID_ARGUMENT: Required parameters are missing, or the
        auth_token is expired or invalid. * ALREADY_EXISTS: A customer already
        exists and has conflicting critical fields. Requires an overwrite.
        Return value: The Customer.
      operationId: cloudchannel.accounts.customers.import
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}:
    patch:
      description: >-
        Updates an existing Customer resource for the reseller or distributor.
        Possible error codes: * PERMISSION_DENIED: The reseller account making
        the request is different from the reseller account in the API request. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        NOT_FOUND: No Customer resource found for the name in the request.
        Return value: The updated Customer resource.
      operationId: cloudchannel.accounts.customers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: exec
    delete:
      description: >-
        Deletes the given Customer permanently. Possible error codes: *
        PERMISSION_DENIED: The account making the request does not own this
        customer. * INVALID_ARGUMENT: Required request parameters are missing or
        invalid. * FAILED_PRECONDITION: The customer has existing entitlements.
        * NOT_FOUND: No Customer resource found for the name in the request.
      operationId: cloudchannel.accounts.customers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: delete
    get:
      description: >-
        Returns the requested Customer resource. Possible error codes: *
        PERMISSION_DENIED: The reseller account making the request is different
        from the reseller account in the API request. * INVALID_ARGUMENT:
        Required request parameters are missing or invalid. * NOT_FOUND: The
        customer resource doesn't exist. Usually the result of an invalid name
        parameter. Return value: The Customer resource.
      operationId: cloudchannel.accounts.customers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/customers/{customersId}:provisionCloudIdentity:
    post:
      description: >-
        Creates a Cloud Identity for the given customer using the customer's
        information, or the information provided here. Possible error codes: *
        PERMISSION_DENIED: The customer doesn't belong to the reseller. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        NOT_FOUND: The customer was not found. * ALREADY_EXISTS: The customer's
        primary email already exists. Retry after changing the customer's
        primary contact email. * INTERNAL: Any non-user error related to a
        technical issue in the backend. Contact Cloud Channel support. *
        UNKNOWN: Any non-user error related to a technical issue in the backend.
        Contact Cloud Channel support. Return value: The ID of a long-running
        operation. To get the results of the operation, call the GetOperation
        method of CloudChannelOperationsService. The Operation metadata contains
        an instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.provisionCloudIdentity
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}:queryEligibleBillingAccounts:
    get:
      description: >-
        Lists the billing accounts that are eligible to purchase particular SKUs
        for a given customer. Possible error codes: * PERMISSION_DENIED: The
        customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required
        request parameters are missing or invalid. Return value: Based on the
        provided list of SKUs, returns a list of SKU groups that must be
        purchased using the same billing account and the billing accounts
        eligible to purchase each SKU group.
      operationId: cloudchannel.accounts.customers.queryEligibleBillingAccounts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}:listPurchasableSkus:
    get:
      description: >-
        Lists the following: * SKUs that you can purchase for a customer * SKUs
        that you can upgrade or downgrade for an entitlement. Possible error
        codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller.
        * INVALID_ARGUMENT: Required request parameters are missing or invalid.
      operationId: cloudchannel.accounts.customers.listPurchasableSkus
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers__purchasable_skus
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/customers/{customersId}:transferEntitlements:
    post:
      description: >-
        Transfers customer entitlements to new reseller. Possible error codes: *
        PERMISSION_DENIED: The customer doesn't belong to the reseller. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        NOT_FOUND: The customer or offer resource was not found. *
        ALREADY_EXISTS: The SKU was already transferred for the customer. *
        CONDITION_NOT_MET or FAILED_PRECONDITION: * The SKU requires domain
        verification to transfer, but the domain is not verified. * An Add-On
        SKU (example, Vault or Drive) is missing the pre-requisite SKU (example,
        G Suite Basic). * (Developer accounts only) Reseller and resold domain
        must meet the following naming requirements: * Domain names must start
        with goog-test. * Domain names must include the reseller domain. *
        Specify all transferring entitlements. * INTERNAL: Any non-user error
        related to a technical issue in the backend. Contact Cloud Channel
        support. * UNKNOWN: Any non-user error related to a technical issue in
        the backend. Contact Cloud Channel support. Return value: The ID of a
        long-running operation. To get the results of the operation, call the
        GetOperation method of CloudChannelOperationsService. The Operation
        metadata will contain an instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.transferEntitlements
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}:listPurchasableOffers:
    get:
      description: >-
        Lists the following: * Offers that you can purchase for a customer. *
        Offers that you can change for an entitlement. Possible error codes: *
        PERMISSION_DENIED: The customer doesn't belong to the reseller *
        INVALID_ARGUMENT: Required request parameters are missing or invalid.
      operationId: cloudchannel.accounts.customers.listPurchasableOffers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers__purchasable_offers
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/customers/{customersId}:transferEntitlementsToGoogle:
    post:
      description: >-
        Transfers customer entitlements from their current reseller to Google.
        Possible error codes: * PERMISSION_DENIED: The customer doesn't belong
        to the reseller. * INVALID_ARGUMENT: Required request parameters are
        missing or invalid. * NOT_FOUND: The customer or offer resource was not
        found. * ALREADY_EXISTS: The SKU was already transferred for the
        customer. * CONDITION_NOT_MET or FAILED_PRECONDITION: * The SKU requires
        domain verification to transfer, but the domain is not verified. * An
        Add-On SKU (example, Vault or Drive) is missing the pre-requisite SKU
        (example, G Suite Basic). * (Developer accounts only) Reseller and
        resold domain must meet the following naming requirements: * Domain
        names must start with goog-test. * Domain names must include the
        reseller domain. * INTERNAL: Any non-user error related to a technical
        issue in the backend. Contact Cloud Channel support. * UNKNOWN: Any
        non-user error related to a technical issue in the backend. Contact
        Cloud Channel support. Return value: The ID of a long-running operation.
        To get the results of the operation, call the GetOperation method of
        CloudChannelOperationsService. The response will contain
        google.protobuf.Empty on success. The Operation metadata will contain an
        instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.transferEntitlementsToGoogle
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeParameters:
    post:
      description: >-
        Change parameters of the entitlement. An entitlement update is a
        long-running operation and it updates the entitlement as a result of
        fulfillment. Possible error codes: * PERMISSION_DENIED: The customer
        doesn't belong to the reseller. * INVALID_ARGUMENT: Required request
        parameters are missing or invalid. For example, the number of seats
        being changed is greater than the allowed number of max seats, or
        decreasing seats for a commitment based plan. * NOT_FOUND: Entitlement
        resource not found. * INTERNAL: Any non-user error related to a
        technical issue in the backend. Contact Cloud Channel support. *
        UNKNOWN: Any non-user error related to a technical issue in the backend.
        Contact Cloud Channel support. Return value: The ID of a long-running
        operation. To get the results of the operation, call the GetOperation
        method of CloudChannelOperationsService. The Operation metadata will
        contain an instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.entitlements.changeParameters
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements:
    post:
      description: >-
        Creates an entitlement for a customer. Possible error codes: *
        PERMISSION_DENIED: The customer doesn't belong to the reseller. *
        INVALID_ARGUMENT: * Required request parameters are missing or invalid.
        * There is already a customer entitlement for a SKU from the same
        product family. * INVALID_VALUE: Make sure the OfferId is valid. If it
        is, contact Google Channel support for further troubleshooting. *
        NOT_FOUND: The customer or offer resource was not found. *
        ALREADY_EXISTS: * The SKU was already purchased for the customer. * The
        customer's primary email already exists. Retry after changing the
        customer's primary contact email. * CONDITION_NOT_MET or
        FAILED_PRECONDITION: * The domain required for purchasing a SKU has not
        been verified. * A pre-requisite SKU required to purchase an Add-On SKU
        is missing. For example, Google Workspace Business Starter is required
        to purchase Vault or Drive. * (Developer accounts only) Reseller and
        resold domain must meet the following naming requirements: * Domain
        names must start with goog-test. * Domain names must include the
        reseller domain. * INTERNAL: Any non-user error related to a technical
        issue in the backend. Contact Cloud Channel support. * UNKNOWN: Any
        non-user error related to a technical issue in the backend. Contact
        Cloud Channel support. Return value: The ID of a long-running operation.
        To get the results of the operation, call the GetOperation method of
        CloudChannelOperationsService. The Operation metadata will contain an
        instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.entitlements.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: insert
    get:
      description: >-
        Lists Entitlements belonging to a customer. Possible error codes: *
        PERMISSION_DENIED: The customer doesn't belong to the reseller. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid.
        Return value: A list of the customer's Entitlements.
      operationId: cloudchannel.accounts.customers.entitlements.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:cancel:
    post:
      description: >-
        Cancels a previously fulfilled entitlement. An entitlement cancellation
        is a long-running operation. Possible error codes: * PERMISSION_DENIED:
        The reseller account making the request is different from the reseller
        account in the API request. * FAILED_PRECONDITION: There are Google
        Cloud projects linked to the Google Cloud entitlement's Cloud Billing
        subaccount. * INVALID_ARGUMENT: Required request parameters are missing
        or invalid. * NOT_FOUND: Entitlement resource not found. *
        DELETION_TYPE_NOT_ALLOWED: Cancel is only allowed for Google Workspace
        add-ons, or entitlements for Google Cloud's development platform. *
        INTERNAL: Any non-user error related to a technical issue in the
        backend. Contact Cloud Channel support. * UNKNOWN: Any non-user error
        related to a technical issue in the backend. Contact Cloud Channel
        support. Return value: The ID of a long-running operation. To get the
        results of the operation, call the GetOperation method of
        CloudChannelOperationsService. The response will contain
        google.protobuf.Empty on success. The Operation metadata will contain an
        instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.entitlements.cancel
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeOffer:
    post:
      description: >-
        Updates the Offer for an existing customer entitlement. An entitlement
        update is a long-running operation and it updates the entitlement as a
        result of fulfillment. Possible error codes: * PERMISSION_DENIED: The
        customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required
        request parameters are missing or invalid. * NOT_FOUND: Offer or
        Entitlement resource not found. * INTERNAL: Any non-user error related
        to a technical issue in the backend. Contact Cloud Channel support. *
        UNKNOWN: Any non-user error related to a technical issue in the backend.
        Contact Cloud Channel support. Return value: The ID of a long-running
        operation. To get the results of the operation, call the GetOperation
        method of CloudChannelOperationsService. The Operation metadata will
        contain an instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.entitlements.changeOffer
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:startPaidService:
    post:
      description: >-
        Starts paid service for a trial entitlement. Starts paid service for a
        trial entitlement immediately. This method is only applicable if a plan
        is set up for a trial entitlement but has some trial days remaining.
        Possible error codes: * PERMISSION_DENIED: The customer doesn't belong
        to the reseller. * INVALID_ARGUMENT: Required request parameters are
        missing or invalid. * NOT_FOUND: Entitlement resource not found. *
        FAILED_PRECONDITION/NOT_IN_TRIAL: This method only works for entitlement
        on trial plans. * INTERNAL: Any non-user error related to a technical
        issue in the backend. Contact Cloud Channel support. * UNKNOWN: Any
        non-user error related to a technical issue in the backend. Contact
        Cloud Channel support. Return value: The ID of a long-running operation.
        To get the results of the operation, call the GetOperation method of
        CloudChannelOperationsService. The Operation metadata will contain an
        instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.entitlements.startPaidService
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:
    get:
      description: >-
        Returns the requested Entitlement resource. Possible error codes: *
        PERMISSION_DENIED: The customer doesn't belong to the reseller. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        NOT_FOUND: The customer entitlement was not found. Return value: The
        requested Entitlement resource.
      operationId: cloudchannel.accounts.customers.entitlements.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:activate:
    post:
      description: >-
        Activates a previously suspended entitlement. Entitlements suspended for
        pending ToS acceptance can't be activated using this method. An
        entitlement activation is a long-running operation and it updates the
        state of the customer entitlement. Possible error codes: *
        PERMISSION_DENIED: The reseller account making the request is different
        from the reseller account in the API request. * INVALID_ARGUMENT:
        Required request parameters are missing or invalid. * NOT_FOUND:
        Entitlement resource not found. * SUSPENSION_NOT_RESELLER_INITIATED: Can
        only activate reseller-initiated suspensions and entitlements that have
        accepted the TOS. * NOT_SUSPENDED: Can only activate suspended
        entitlements not in an ACTIVE state. * INTERNAL: Any non-user error
        related to a technical issue in the backend. Contact Cloud Channel
        support. * UNKNOWN: Any non-user error related to a technical issue in
        the backend. Contact Cloud Channel support. Return value: The ID of a
        long-running operation. To get the results of the operation, call the
        GetOperation method of CloudChannelOperationsService. The Operation
        metadata will contain an instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.entitlements.activate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeRenewalSettings:
    post:
      description: >-
        Updates the renewal settings for an existing customer entitlement. An
        entitlement update is a long-running operation and it updates the
        entitlement as a result of fulfillment. Possible error codes: *
        PERMISSION_DENIED: The customer doesn't belong to the reseller. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        NOT_FOUND: Entitlement resource not found. * NOT_COMMITMENT_PLAN:
        Renewal Settings are only applicable for a commitment plan. Can't enable
        or disable renewals for non-commitment plans. * INTERNAL: Any non-user
        error related to a technical issue in the backend. Contact Cloud Channel
        support. * UNKNOWN: Any non-user error related to a technical issue in
        the backend. Contact Cloud Channel support. Return value: The ID of a
        long-running operation. To get the results of the operation, call the
        GetOperation method of CloudChannelOperationsService. The Operation
        metadata will contain an instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.entitlements.changeRenewalSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:listEntitlementChanges:
    get:
      description: >-
        List entitlement history. Possible error codes: * PERMISSION_DENIED: The
        reseller account making the request and the provided reseller account
        are different. * INVALID_ARGUMENT: Missing or invalid required fields in
        the request. * NOT_FOUND: The parent resource doesn't exist. Usually the
        result of an invalid name parameter. * INTERNAL: Any non-user error
        related to a technical issue in the backend. In this case, contact
        CloudChannel support. * UNKNOWN: Any non-user error related to a
        technical issue in the backend. In this case, contact Cloud Channel
        support. Return value: List of EntitlementChanges.
      operationId: cloudchannel.accounts.customers.entitlements.listEntitlementChanges
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements__entitlement_changes
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:suspend:
    post:
      description: >-
        Suspends a previously fulfilled entitlement. An entitlement suspension
        is a long-running operation. Possible error codes: * PERMISSION_DENIED:
        The customer doesn't belong to the reseller. * INVALID_ARGUMENT:
        Required request parameters are missing or invalid. * NOT_FOUND:
        Entitlement resource not found. * NOT_ACTIVE: Entitlement is not active.
        * INTERNAL: Any non-user error related to a technical issue in the
        backend. Contact Cloud Channel support. * UNKNOWN: Any non-user error
        related to a technical issue in the backend. Contact Cloud Channel
        support. Return value: The ID of a long-running operation. To get the
        results of the operation, call the GetOperation method of
        CloudChannelOperationsService. The Operation metadata will contain an
        instance of OperationMetadata.
      operationId: cloudchannel.accounts.customers.entitlements.suspend
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:lookupOffer:
    get:
      description: >-
        Returns the requested Offer resource. Possible error codes: *
        PERMISSION_DENIED: The entitlement doesn't belong to the reseller. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        NOT_FOUND: Entitlement or offer was not found. Return value: The Offer
        resource.
      operationId: cloudchannel.accounts.customers.entitlements.lookupOffer
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: entitlements
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs/{customerRepricingConfigsId}:
    patch:
      description: >-
        Updates a CustomerRepricingConfig. Call this method to set modifications
        for a specific customer's bill. This method overwrites the existing
        CustomerRepricingConfig. You can only update configs if the
        RepricingConfig.effective_invoice_month is a future month. To make
        changes to configs for the current month, use
        CreateCustomerRepricingConfig, taking note of its restrictions. You
        cannot update the RepricingConfig.effective_invoice_month. When updating
        a config in the future: * This config must already exist. Possible Error
        Codes: * PERMISSION_DENIED: If the account making the request and the
        account being queried are different. * INVALID_ARGUMENT: Missing or
        invalid required parameters in the request. Also displays if the updated
        config is for the current month or past months. * NOT_FOUND: The
        CustomerRepricingConfig specified does not exist or is not associated
        with the given account. * INTERNAL: Any non-user error related to
        technical issues in the backend. In this case, contact Cloud Channel
        support. Return Value: If successful, the updated
        CustomerRepricingConfig resource, otherwise returns an error.
      operationId: cloudchannel.accounts.customers.customerRepricingConfigs.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customer_repricing_configs
      x-stackQL-verb: exec
    delete:
      description: >-
        Deletes the given CustomerRepricingConfig permanently. You can only
        delete configs if their RepricingConfig.effective_invoice_month is set
        to a date after the current month. Possible error codes: *
        PERMISSION_DENIED: The account making the request does not own this
        customer. * INVALID_ARGUMENT: Required request parameters are missing or
        invalid. * FAILED_PRECONDITION: The CustomerRepricingConfig is active or
        in the past. * NOT_FOUND: No CustomerRepricingConfig found for the name
        in the request.
      operationId: cloudchannel.accounts.customers.customerRepricingConfigs.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customer_repricing_configs
      x-stackQL-verb: delete
    get:
      description: >-
        Gets information about how a Reseller modifies their bill before sending
        it to a Customer. Possible Error Codes: * PERMISSION_DENIED: If the
        account making the request and the account being queried are different.
        * NOT_FOUND: The CustomerRepricingConfig was not found. * INTERNAL: Any
        non-user error related to technical issues in the backend. In this case,
        contact Cloud Channel support. Return Value: If successful, the
        CustomerRepricingConfig resource, otherwise returns an error.
      operationId: cloudchannel.accounts.customers.customerRepricingConfigs.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customer_repricing_configs
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs:
    post:
      description: >-
        Creates a CustomerRepricingConfig. Call this method to set modifications
        for a specific customer's bill. You can only create configs if the
        RepricingConfig.effective_invoice_month is a future month. If needed,
        you can create a config for the current month, with some restrictions.
        When creating a config for a future month, make sure there are no
        existing configs for that RepricingConfig.effective_invoice_month. The
        following restrictions are for creating configs in the current month. *
        This functionality is reserved for recovering from an erroneous config,
        and should not be used for regular business cases. * The new config will
        not modify exports used with other configs. Changes to the config may be
        immediate, but may take up to 24 hours. * There is a limit of ten
        configs for any RepricingConfig.EntitlementGranularity.entitlement or
        RepricingConfig.effective_invoice_month. * The contained
        CustomerRepricingConfig.repricing_config vaule must be different from
        the value used in the current config for a
        RepricingConfig.EntitlementGranularity.entitlement. Possible Error
        Codes: * PERMISSION_DENIED: If the account making the request and the
        account being queried are different. * INVALID_ARGUMENT: Missing or
        invalid required parameters in the request. Also displays if the updated
        config is for the current month or past months. * NOT_FOUND: The
        CustomerRepricingConfig specified does not exist or is not associated
        with the given account. * INTERNAL: Any non-user error related to
        technical issues in the backend. In this case, contact Cloud Channel
        support. Return Value: If successful, the updated
        CustomerRepricingConfig resource, otherwise returns an error.
      operationId: cloudchannel.accounts.customers.customerRepricingConfigs.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customer_repricing_configs
      x-stackQL-verb: insert
    get:
      description: >-
        Lists information about how a Reseller modifies their bill before
        sending it to a Customer. Possible Error Codes: * PERMISSION_DENIED: If
        the account making the request and the account being queried are
        different. * NOT_FOUND: The CustomerRepricingConfig specified does not
        exist or is not associated with the given account. * INTERNAL: Any
        non-user error related to technical issues in the backend. In this case,
        contact Cloud Channel support. Return Value: If successful, the
        CustomerRepricingConfig resources. The data for each resource is
        displayed in the ascending order of: * Customer ID *
        RepricingConfig.EntitlementGranularity.entitlement *
        RepricingConfig.effective_invoice_month *
        CustomerRepricingConfig.update_time If unsuccessful, returns an error.
      operationId: cloudchannel.accounts.customers.customerRepricingConfigs.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customer_repricing_configs
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/reportJobs/{reportJobsId}:fetchReportResults:
    post:
      description: Retrieves data generated by CloudChannelReportsService.RunReportJob.
      operationId: cloudchannel.accounts.reportJobs.fetchReportResults
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
      x-stackQL-resource: report_jobs__report_results
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}:
    patch:
      description: >-
        Updates a channel partner link. Distributors call this method to change
        a link's status. For example, to suspend a partner link. You must be a
        distributor to call this method. Possible error codes: *
        PERMISSION_DENIED: The reseller account making the request is different
        from the reseller account in the API request. * INVALID_ARGUMENT: *
        Required request parameters are missing or invalid. * Link state cannot
        change from invited to active or suspended. * Cannot send
        reseller_cloud_identity_id, invite_url, or name in update mask. *
        NOT_FOUND: ChannelPartnerLink resource not found. * INTERNAL: Any
        non-user error related to a technical issue in the backend. Contact
        Cloud Channel support. * UNKNOWN: Any non-user error related to a
        technical issue in the backend. Contact Cloud Channel support. Return
        value: The updated ChannelPartnerLink resource.
      operationId: cloudchannel.accounts.channelPartnerLinks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_links
      x-stackQL-verb: exec
    get:
      description: >-
        Returns the requested ChannelPartnerLink resource. You must be a
        distributor to call this method. Possible error codes: *
        PERMISSION_DENIED: The reseller account making the request is different
        from the reseller account in the API request. * INVALID_ARGUMENT:
        Required request parameters are missing or invalid. * NOT_FOUND:
        ChannelPartnerLink resource not found because of an invalid channel
        partner link name. Return value: The ChannelPartnerLink resource.
      operationId: cloudchannel.accounts.channelPartnerLinks.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_links
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/channelPartnerLinks:
    post:
      description: >-
        Initiates a channel partner link between a distributor and a reseller,
        or between resellers in an n-tier reseller channel. Invited partners
        need to follow the invite_link_uri provided in the response to accept.
        After accepting the invitation, a link is set up between the two
        parties. You must be a distributor to call this method. Possible error
        codes: * PERMISSION_DENIED: The reseller account making the request is
        different from the reseller account in the API request. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        ALREADY_EXISTS: The ChannelPartnerLink sent in the request already
        exists. * NOT_FOUND: No Cloud Identity customer exists for provided
        domain. * INTERNAL: Any non-user error related to a technical issue in
        the backend. Contact Cloud Channel support. * UNKNOWN: Any non-user
        error related to a technical issue in the backend. Contact Cloud Channel
        support. Return value: The new ChannelPartnerLink resource.
      operationId: cloudchannel.accounts.channelPartnerLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_links
      x-stackQL-verb: insert
    get:
      description: >-
        List ChannelPartnerLinks belonging to a distributor. You must be a
        distributor to call this method. Possible error codes: *
        PERMISSION_DENIED: The reseller account making the request is different
        from the reseller account in the API request. * INVALID_ARGUMENT:
        Required request parameters are missing or invalid. Return value: The
        list of the distributor account's ChannelPartnerLink resources.
      operationId: cloudchannel.accounts.channelPartnerLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_links
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs/{channelPartnerRepricingConfigsId}:
    get:
      description: >-
        Gets information about how a Distributor modifies their bill before
        sending it to a ChannelPartner. Possible Error Codes: *
        PERMISSION_DENIED: If the account making the request and the account
        being queried are different. * NOT_FOUND: The
        ChannelPartnerRepricingConfig was not found. * INTERNAL: Any non-user
        error related to technical issues in the backend. In this case, contact
        Cloud Channel support. Return Value: If successful, the
        ChannelPartnerRepricingConfig resource, otherwise returns an error.
      operationId: >-
        cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_repricing_configs
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes the given ChannelPartnerRepricingConfig permanently. You can
        only delete configs if their RepricingConfig.effective_invoice_month is
        set to a date after the current month. Possible error codes: *
        PERMISSION_DENIED: The account making the request does not own this
        customer. * INVALID_ARGUMENT: Required request parameters are missing or
        invalid. * FAILED_PRECONDITION: The ChannelPartnerRepricingConfig is
        active or in the past. * NOT_FOUND: No ChannelPartnerRepricingConfig
        found for the name in the request.
      operationId: >-
        cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_repricing_configs
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates a ChannelPartnerRepricingConfig. Call this method to set
        modifications for a specific ChannelPartner's bill. This method
        overwrites the existing CustomerRepricingConfig. You can only update
        configs if the RepricingConfig.effective_invoice_month is a future
        month. To make changes to configs for the current month, use
        CreateChannelPartnerRepricingConfig, taking note of its restrictions.
        You cannot update the RepricingConfig.effective_invoice_month. When
        updating a config in the future: * This config must already exist.
        Possible Error Codes: * PERMISSION_DENIED: If the account making the
        request and the account being queried are different. * INVALID_ARGUMENT:
        Missing or invalid required parameters in the request. Also displays if
        the updated config is for the current month or past months. * NOT_FOUND:
        The ChannelPartnerRepricingConfig specified does not exist or is not
        associated with the given account. * INTERNAL: Any non-user error
        related to technical issues in the backend. In this case, contact Cloud
        Channel support. Return Value: If successful, the updated
        ChannelPartnerRepricingConfig resource, otherwise returns an error.
      operationId: >-
        cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_repricing_configs
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs:
    post:
      description: >-
        Creates a ChannelPartnerRepricingConfig. Call this method to set
        modifications for a specific ChannelPartner's bill. You can only create
        configs if the RepricingConfig.effective_invoice_month is a future
        month. If needed, you can create a config for the current month, with
        some restrictions. When creating a config for a future month, make sure
        there are no existing configs for that
        RepricingConfig.effective_invoice_month. The following restrictions are
        for creating configs in the current month. * This functionality is
        reserved for recovering from an erroneous config, and should not be used
        for regular business cases. * The new config will not modify exports
        used with other configs. Changes to the config may be immediate, but may
        take up to 24 hours. * There is a limit of ten configs for any
        ChannelPartner or RepricingConfig.effective_invoice_month. * The
        contained ChannelPartnerRepricingConfig.repricing_config vaule must be
        different from the value used in the current config for a
        ChannelPartner. Possible Error Codes: * PERMISSION_DENIED: If the
        account making the request and the account being queried are different.
        * INVALID_ARGUMENT: Missing or invalid required parameters in the
        request. Also displays if the updated config is for the current month or
        past months. * NOT_FOUND: The ChannelPartnerRepricingConfig specified
        does not exist or is not associated with the given account. * INTERNAL:
        Any non-user error related to technical issues in the backend. In this
        case, contact Cloud Channel support. Return Value: If successful, the
        updated ChannelPartnerRepricingConfig resource, otherwise returns an
        error.
      operationId: >-
        cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_repricing_configs
      x-stackQL-verb: insert
    get:
      description: >-
        Lists information about how a Reseller modifies their bill before
        sending it to a ChannelPartner. Possible Error Codes: *
        PERMISSION_DENIED: If the account making the request and the account
        being queried are different. * NOT_FOUND: The
        ChannelPartnerRepricingConfig specified does not exist or is not
        associated with the given account. * INTERNAL: Any non-user error
        related to technical issues in the backend. In this case, contact Cloud
        Channel support. Return Value: If successful, the
        ChannelPartnerRepricingConfig resources. The data for each resource is
        displayed in the ascending order of: * Channel Partner ID *
        RepricingConfig.effective_invoice_month *
        ChannelPartnerRepricingConfig.update_time If unsuccessful, returns an
        error.
      operationId: >-
        cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: channel_partner_repricing_configs
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers:
    get:
      description: >-
        List Customers. Possible error codes: * PERMISSION_DENIED: The reseller
        account making the request is different from the reseller account in the
        API request. * INVALID_ARGUMENT: Required request parameters are missing
        or invalid. Return value: List of Customers, or an empty list if there
        are no customers.
      operationId: cloudchannel.accounts.channelPartnerLinks.customers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: select
    post:
      description: >-
        Creates a new Customer resource under the reseller or distributor
        account. Possible error codes: * PERMISSION_DENIED: The reseller account
        making the request is different from the reseller account in the API
        request. * INVALID_ARGUMENT: * Required request parameters are missing
        or invalid. * Domain field value doesn't match the primary email domain.
        Return value: The newly created Customer resource.
      operationId: cloudchannel.accounts.channelPartnerLinks.customers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: insert
  /v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers/{customersId}:
    delete:
      description: >-
        Deletes the given Customer permanently. Possible error codes: *
        PERMISSION_DENIED: The account making the request does not own this
        customer. * INVALID_ARGUMENT: Required request parameters are missing or
        invalid. * FAILED_PRECONDITION: The customer has existing entitlements.
        * NOT_FOUND: No Customer resource found for the name in the request.
      operationId: cloudchannel.accounts.channelPartnerLinks.customers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates an existing Customer resource for the reseller or distributor.
        Possible error codes: * PERMISSION_DENIED: The reseller account making
        the request is different from the reseller account in the API request. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        NOT_FOUND: No Customer resource found for the name in the request.
        Return value: The updated Customer resource.
      operationId: cloudchannel.accounts.channelPartnerLinks.customers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: exec
    get:
      description: >-
        Returns the requested Customer resource. Possible error codes: *
        PERMISSION_DENIED: The reseller account making the request is different
        from the reseller account in the API request. * INVALID_ARGUMENT:
        Required request parameters are missing or invalid. * NOT_FOUND: The
        customer resource doesn't exist. Usually the result of an invalid name
        parameter. Return value: The Customer resource.
      operationId: cloudchannel.accounts.channelPartnerLinks.customers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers:import:
    post:
      description: >-
        Imports a Customer from the Cloud Identity associated with the provided
        Cloud Identity ID or domain before a TransferEntitlements call. If a
        linked Customer already exists and overwrite_if_exists is true, it will
        update that Customer's data. Possible error codes: * PERMISSION_DENIED:
        The reseller account making the request is different from the reseller
        account in the API request. * NOT_FOUND: Cloud Identity doesn't exist or
        was deleted. * INVALID_ARGUMENT: Required parameters are missing, or the
        auth_token is expired or invalid. * ALREADY_EXISTS: A customer already
        exists and has conflicting critical fields. Requires an overwrite.
        Return value: The Customer.
      operationId: cloudchannel.accounts.channelPartnerLinks.customers.import
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: customers
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/reports/{reportsId}:run:
    post:
      description: >-
        Begins generation of data for a given report. The report identifier is a
        UID (for example, `613bf59q`). Possible error codes: *
        PERMISSION_DENIED: The user doesn't have access to this report. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        NOT_FOUND: The report identifier was not found. * INTERNAL: Any non-user
        error related to a technical issue in the backend. Contact Cloud Channel
        support. * UNKNOWN: Any non-user error related to a technical issue in
        the backend. Contact Cloud Channel support. Return value: The ID of a
        long-running operation. To get the results of the operation, call the
        GetOperation method of CloudChannelOperationsService. The Operation
        metadata contains an instance of OperationMetadata. To get the results
        of report generation, call CloudChannelReportsService.FetchReportResults
        with the RunReportJobResponse.report_job.
      operationId: cloudchannel.accounts.reports.run
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}/reports:
    get:
      description: >-
        Lists the reports that RunReportJob can run. These reports include an
        ID, a description, and the list of columns that will be in the result.
      operationId: cloudchannel.accounts.reports.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/skuGroups/{skuGroupsId}/billableSkus:
    get:
      description: >-
        Lists the Billable SKUs in a given SKU group. Possible error codes:
        PERMISSION_DENIED: If the account making the request and the account
        being queried for are different, or the account doesn't exist.
        INVALID_ARGUMENT: Missing or invalid required parameters in the request.
        INTERNAL: Any non-user error related to technical issue in the backend.
        In this case, contact cloud channel support. Return Value: If
        successful, the BillableSku resources. The data for each resource is
        displayed in the ascending order of: * BillableSku.service_display_name
        * BillableSku.sku_display_name If unsuccessful, returns an error.
      operationId: cloudchannel.accounts.skuGroups.billableSkus.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: billable_skus
      x-stackQL-verb: select
  /v1/accounts/{accountsId}/skuGroups:
    get:
      description: >-
        Lists the Rebilling supported SKU groups the account is authorized to
        sell. Reference: https://cloud.google.com/skus/sku-groups Possible Error
        Codes: * PERMISSION_DENIED: If the account making the request and the
        account being queried are different, or the account doesn't exist. *
        INTERNAL: Any non-user error related to technical issues in the backend.
        In this case, contact Cloud Channel support. Return Value: If
        successful, the SkuGroup resources. The data for each resource is
        displayed in the alphabetical order of SKU group display name. The data
        for each resource is displayed in the ascending order of
        SkuGroup.display_name If unsuccessful, returns an error.
      operationId: cloudchannel.accounts.skuGroups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: sku_groups
      x-stackQL-verb: select
  /v1/accounts/{accountsId}:unregister:
    post:
      description: >-
        Unregisters a service account with subscriber privileges on the Cloud
        Pub/Sub topic created for this Channel Services account. If there are no
        service accounts left with subscriber privileges, this deletes the
        topic. You can call ListSubscribers to check for these accounts.
        Possible error codes: * PERMISSION_DENIED: The reseller account making
        the request and the provided reseller account are different, or the
        impersonated user is not a super admin. * INVALID_ARGUMENT: Required
        request parameters are missing or invalid. * NOT_FOUND: The topic
        resource doesn't exist. * INTERNAL: Any non-user error related to a
        technical issue in the backend. Contact Cloud Channel support. *
        UNKNOWN: Any non-user error related to a technical issue in the backend.
        Contact Cloud Channel support. Return value: The topic name that
        unregistered the service email address. Returns a success response if
        the service email address wasn't registered with the topic.
      operationId: cloudchannel.accounts.unregister
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}:listSubscribers:
    get:
      description: >-
        Lists service accounts with subscriber privileges on the Cloud Pub/Sub
        topic created for this Channel Services account. Possible error codes: *
        PERMISSION_DENIED: The reseller account making the request and the
        provided reseller account are different, or the impersonated user is not
        a super admin. * INVALID_ARGUMENT: Required request parameters are
        missing or invalid. * NOT_FOUND: The topic resource doesn't exist. *
        INTERNAL: Any non-user error related to a technical issue in the
        backend. Contact Cloud Channel support. * UNKNOWN: Any non-user error
        related to a technical issue in the backend. Contact Cloud Channel
        support. Return value: A list of service email addresses.
      operationId: cloudchannel.accounts.listSubscribers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: accounts__subscribers
      x-stackQL-verb: select
  /v1/accounts/{accountsId}:checkCloudIdentityAccountsExist:
    post:
      description: >-
        Confirms the existence of Cloud Identity accounts based on the domain
        and if the Cloud Identity accounts are owned by the reseller. Possible
        error codes: * PERMISSION_DENIED: The reseller account making the
        request is different from the reseller account in the API request. *
        INVALID_ARGUMENT: Required request parameters are missing or invalid. *
        INVALID_VALUE: Invalid domain value in the request. Return value: A list
        of CloudIdentityCustomerAccount resources for the domain (may be empty)
        Note: in the v1alpha1 version of the API, a NOT_FOUND error returns if
        no CloudIdentityCustomerAccount resources match the domain.
      operationId: cloudchannel.accounts.checkCloudIdentityAccountsExist
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}:listTransferableSkus:
    post:
      description: >-
        List TransferableSkus of a customer based on the Cloud Identity ID or
        Customer Name in the request. Use this method to list the entitlements
        information of an unowned customer. You should provide the customer's
        Cloud Identity ID or Customer Name. Possible error codes: *
        PERMISSION_DENIED: * The customer doesn't belong to the reseller and has
        no auth token. * The supplied auth token is invalid. * The reseller
        account making the request is different from the reseller account in the
        query. * INVALID_ARGUMENT: Required request parameters are missing or
        invalid. Return value: A list of the customer's TransferableSku.
      operationId: cloudchannel.accounts.listTransferableSkus
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: accounts__transferable_skus
      x-stackQL-verb: select
  /v1/accounts/{accountsId}:register:
    post:
      description: >-
        Registers a service account with subscriber privileges on the Cloud
        Pub/Sub topic for this Channel Services account. After you create a
        subscriber, you get the events through SubscriberEvent Possible error
        codes: * PERMISSION_DENIED: The reseller account making the request and
        the provided reseller account are different, or the impersonated user is
        not a super admin. * INVALID_ARGUMENT: Required request parameters are
        missing or invalid. * INTERNAL: Any non-user error related to a
        technical issue in the backend. Contact Cloud Channel support. *
        UNKNOWN: Any non-user error related to a technical issue in the backend.
        Contact Cloud Channel support. Return value: The topic name with the
        registered service email address.
      operationId: cloudchannel.accounts.register
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1/accounts/{accountsId}:listTransferableOffers:
    post:
      description: >-
        List TransferableOffers of a customer based on Cloud Identity ID or
        Customer Name in the request. Use this method when a reseller gets the
        entitlement information of an unowned customer. The reseller should
        provide the customer's Cloud Identity ID or Customer Name. Possible
        error codes: * PERMISSION_DENIED: * The customer doesn't belong to the
        reseller and has no auth token. * The customer provided incorrect
        reseller information when generating auth token. * The reseller account
        making the request is different from the reseller account in the query.
        * INVALID_ARGUMENT: Required request parameters are missing or invalid.
        Return value: List of TransferableOffer for the given customer and SKU.
      operationId: cloudchannel.accounts.listTransferableOffers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      x-stackQL-resource: accounts__transferable_offers
      x-stackQL-verb: select
