openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Vault API
  description: >-
    Retention and eDiscovery for Google Workspace. To work with Vault resources,
    the account must have the [required Vault
    privileges](https://support.google.com/vault/answer/2799699) and access to
    the matter. To access a matter, the account must have created the matter,
    have the matter shared with them, or have the **View All Matters**
    privilege. For example, to download an export, an account needs the **Manage
    Exports** privilege and the matter shared with them. 
  version: v1
  x-discovery-doc-revision: '20230613'
  x-generated-date: '2023-06-25'
servers:
  - url: https://vault.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/ediscovery: Manage your eDiscovery data
            https://www.googleapis.com/auth/ediscovery.readonly: View your eDiscovery data
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/operations/{operationsId}:
    get:
      description: >-
        Gets the latest state of a long-running operation. Clients can use this
        method to poll the operation result at intervals as recommended by the
        API service.
      operationId: vault.operations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: operations
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a long-running operation. This method indicates that the client
        is no longer interested in the operation result. It does not cancel the
        operation. If the server doesn't support this method, it returns
        `google.rpc.Code.UNIMPLEMENTED`.
      operationId: vault.operations.delete
      security: []
      x-stackQL-resource: operations
      x-stackQL-verb: delete
  /v1/operations/{operationsId}:cancel:
    post:
      description: >-
        Starts asynchronous cancellation on a long-running operation. The server
        makes a best effort to cancel the operation, but success is not
        guaranteed. If the server doesn't support this method, it returns
        `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation
        or other methods to check whether the cancellation succeeded or whether
        the operation completed despite cancellation. On successful
        cancellation, the operation is not deleted; instead, it becomes an
        operation with an Operation.error value with a google.rpc.Status.code of
        1, corresponding to `Code.CANCELLED`.
      operationId: vault.operations.cancel
      security: []
      x-stackQL-resource: operations
      x-stackQL-verb: exec
  /v1/operations:
    get:
      description: >-
        Lists operations that match the specified filter in the request. If the
        server doesn't support this method, it returns `UNIMPLEMENTED`.
      operationId: vault.operations.list
      security: []
      x-stackQL-resource: operations
      x-stackQL-verb: select
  /v1/matters:
    get:
      description: Lists matters the requestor has access to.
      operationId: vault.matters.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: matters
      x-stackQL-verb: select
    post:
      description: >-
        Creates a matter with the given name and description. The initial state
        is open, and the owner is the method caller. Returns the created matter
        with default view.
      operationId: vault.matters.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters
      x-stackQL-verb: insert
  /v1/matters/{matterId}:count:
    post:
      description: Counts the accounts processed by the specified query.
      operationId: vault.matters.count
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters
      x-stackQL-verb: exec
  /v1/matters/{matterId}:close:
    post:
      description: Closes the specified matter. Returns the matter with updated state.
      operationId: vault.matters.close
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters
      x-stackQL-verb: exec
  /v1/matters/{matterId}:
    put:
      description: >-
        Updates the specified matter. This updates only the name and description
        of the matter, identified by matter ID. Changes to any other fields are
        ignored. Returns the default view of the matter.
      operationId: vault.matters.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters
      x-stackQL-verb: exec
    get:
      description: Gets the specified matter.
      operationId: vault.matters.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: matters
      x-stackQL-verb: select
    delete:
      description: Deletes the specified matter. Returns the matter with updated state.
      operationId: vault.matters.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters
      x-stackQL-verb: delete
  /v1/matters/{matterId}:undelete:
    post:
      description: Undeletes the specified matter. Returns the matter with updated state.
      operationId: vault.matters.undelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters
      x-stackQL-verb: exec
  /v1/matters/{matterId}:removePermissions:
    post:
      description: Removes an account as a matter collaborator.
      operationId: vault.matters.removePermissions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters__permissions
      x-stackQL-verb: delete
  /v1/matters/{matterId}:addPermissions:
    post:
      description: Adds an account as a matter collaborator.
      operationId: vault.matters.addPermissions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters__permissions
      x-stackQL-verb: insert
  /v1/matters/{matterId}:reopen:
    post:
      description: Reopens the specified matter. Returns the matter with updated state.
      operationId: vault.matters.reopen
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: matters
      x-stackQL-verb: exec
  /v1/matters/{matterId}/savedQueries:
    post:
      description: Creates a saved query.
      operationId: vault.matters.savedQueries.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: saved_queries
      x-stackQL-verb: insert
    get:
      description: Lists the saved queries in a matter.
      operationId: vault.matters.savedQueries.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: saved_queries
      x-stackQL-verb: select
  /v1/matters/{matterId}/savedQueries/{savedQueryId}:
    get:
      description: Retrieves the specified saved query.
      operationId: vault.matters.savedQueries.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: saved_queries
      x-stackQL-verb: select
    delete:
      description: Deletes the specified saved query.
      operationId: vault.matters.savedQueries.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: saved_queries
      x-stackQL-verb: delete
  /v1/matters/{matterId}/holds/{holdId}/accounts:
    get:
      description: >-
        Lists the accounts covered by a hold. This can list only
        individually-specified accounts covered by the hold. If the hold covers
        an organizational unit, use the [Admin
        SDK](https://developers.google.com/admin-sdk/). to list the members of
        the organizational unit on hold.
      operationId: vault.matters.holds.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
    post:
      description: >-
        Adds an account to a hold. Accounts can be added only to a hold that
        does not have an organizational unit set. If you try to add an account
        to an organizational unit-based hold, an error is returned.
      operationId: vault.matters.holds.accounts.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: accounts
      x-stackQL-verb: insert
  /v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}:
    delete:
      description: Removes an account from a hold.
      operationId: vault.matters.holds.accounts.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: accounts
      x-stackQL-verb: delete
  /v1/matters/{matterId}/holds/{holdId}:
    delete:
      description: >-
        Removes the specified hold and releases the accounts or organizational
        unit covered by the hold. If the data is not preserved by another hold
        or retention rule, it might be purged.
      operationId: vault.matters.holds.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: holds
      x-stackQL-verb: delete
    put:
      description: >-
        Updates the scope (organizational unit or accounts) and query parameters
        of a hold. You cannot add accounts to a hold that covers an
        organizational unit, nor can you add organizational units to a hold that
        covers individual accounts. If you try, the unsupported values are
        ignored.
      operationId: vault.matters.holds.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: holds
      x-stackQL-verb: exec
    get:
      description: Gets the specified hold.
      operationId: vault.matters.holds.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: holds
      x-stackQL-verb: select
  /v1/matters/{matterId}/holds:
    post:
      description: Creates a hold in the specified matter.
      operationId: vault.matters.holds.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: holds
      x-stackQL-verb: insert
    get:
      description: Lists the holds in a matter.
      operationId: vault.matters.holds.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: holds
      x-stackQL-verb: select
  /v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts:
    post:
      description: >-
        Removes the specified accounts from a hold. Returns a list of statuses
        in the same order as the request.
      operationId: vault.matters.holds.removeHeldAccounts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: holds__held_accounts
      x-stackQL-verb: delete
  /v1/matters/{matterId}/holds/{holdId}:addHeldAccounts:
    post:
      description: >-
        Adds accounts to a hold. Returns a list of accounts that have been
        successfully added. Accounts can be added only to an existing
        account-based hold.
      operationId: vault.matters.holds.addHeldAccounts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: holds__held_accounts
      x-stackQL-verb: insert
  /v1/matters/{matterId}/exports/{exportId}:
    get:
      description: Gets an export.
      operationId: vault.matters.exports.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: exports
      x-stackQL-verb: select
    delete:
      description: Deletes an export.
      operationId: vault.matters.exports.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: exports
      x-stackQL-verb: delete
  /v1/matters/{matterId}/exports:
    post:
      description: Creates an export.
      operationId: vault.matters.exports.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
      x-stackQL-resource: exports
      x-stackQL-verb: insert
    get:
      description: Lists details about the exports in the specified matter.
      operationId: vault.matters.exports.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery
        - Oauth2:
            - https://www.googleapis.com/auth/ediscovery.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/ediscovery.readonly
      x-stackQL-resource: exports
      x-stackQL-verb: select
