openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Admin SDK API
  description: >-
    Admin SDK lets administrators of enterprise domains to view and manage
    resources like user, groups etc. It also provides audit and usage reports of
    domain.
  version: directory_v1
  x-discovery-doc-revision: '20230619'
  x-generated-date: '2023-06-25'
servers:
  - url: https://admin.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/admin.directory.userschema.readonly: View user schemas on your domain
            https://www.googleapis.com/auth/admin.directory.domain.readonly: View domains related to your customers
            https://www.googleapis.com/auth/admin.directory.device.mobile: View and manage your mobile devices' metadata
            https://www.googleapis.com/auth/admin.directory.group.member: View and manage group subscriptions on your domain
            https://www.googleapis.com/auth/admin.directory.group.readonly: View groups on your domain
            https://www.googleapis.com/auth/admin.directory.user: View and manage the provisioning of users on your domain
            https://www.googleapis.com/auth/admin.directory.customer.readonly: View customer related information
            https://www.googleapis.com/auth/cloud-platform: >-
              See, edit, configure, and delete your Google Cloud data and see
              the email address for your Google Account.
            https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly: View calendar resources on your domain
            https://www.googleapis.com/auth/admin.directory.resource.calendar: >-
              View and manage the provisioning of calendar resources on your
              domain
            https://www.googleapis.com/auth/admin.chrome.printers: >-
              See, add, edit, and permanently delete the printers that your
              organization can use with Chrome
            https://www.googleapis.com/auth/admin.chrome.printers.readonly: See the printers that your organization can use with Chrome
            https://www.googleapis.com/auth/admin.directory.orgunit: View and manage organization units on your domain
            https://www.googleapis.com/auth/admin.directory.customer: View and manage customer related information
            https://www.googleapis.com/auth/admin.directory.user.alias.readonly: View user aliases on your domain
            https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly: View delegated admin roles for your domain
            https://www.googleapis.com/auth/admin.directory.userschema: View and manage the provisioning of user schemas on your domain
            https://www.googleapis.com/auth/admin.directory.device.chromeos: View and manage your Chrome OS devices' metadata
            https://www.googleapis.com/auth/admin.directory.group: View and manage the provisioning of groups on your domain
            https://www.googleapis.com/auth/admin.directory.domain: View and manage the provisioning of domains for your customers
            https://www.googleapis.com/auth/admin.directory.device.mobile.action: Manage your mobile devices by performing administrative tasks
            https://www.googleapis.com/auth/admin.directory.rolemanagement: Manage delegated admin roles for your domain
            https://www.googleapis.com/auth/admin.directory.orgunit.readonly: View organization units on your domain
            https://www.googleapis.com/auth/admin.directory.user.security: Manage data access permissions for users on your domain
            https://www.googleapis.com/auth/admin.directory.user.readonly: See info about users on your domain
            https://www.googleapis.com/auth/admin.directory.user.alias: View and manage user aliases on your domain
            https://www.googleapis.com/auth/admin.directory.device.mobile.readonly: View your mobile devices' metadata
            https://www.googleapis.com/auth/admin.directory.group.member.readonly: View group subscriptions on your domain
            https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly: View your Chrome OS devices' metadata
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /admin/directory/v1/users/{userKey}/photos/thumbnail:
    get:
      description: Retrieves the user's photo.
      operationId: directory.users.photos.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
      x-stackQL-resource: photos
      x-stackQL-verb: select
    put:
      description: Adds a photo for the user.
      operationId: directory.users.photos.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: photos
      x-stackQL-verb: exec
    patch:
      description: >-
        Adds a photo for the user. This method supports [patch
        semantics](/admin-sdk/directory/v1/guides/performance#patch).
      operationId: directory.users.photos.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: photos
      x-stackQL-verb: exec
    delete:
      description: Removes the user's photo.
      operationId: directory.users.photos.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: photos
      x-stackQL-verb: delete
  /admin/directory/v1/users/{userKey}/aliases:
    post:
      description: Adds an alias.
      operationId: directory.users.aliases.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
      x-stackQL-resource: aliases
      x-stackQL-verb: insert
    get:
      description: Lists all aliases for a user.
      operationId: directory.users.aliases.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.user.alias.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.user.alias.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
      x-stackQL-resource: aliases
      x-stackQL-verb: select
  /admin/directory/v1/users/{userKey}/aliases/watch:
    post:
      description: Watches for changes in users list.
      operationId: directory.users.aliases.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.user.alias.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.user.alias.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
      x-stackQL-resource: aliases
      x-stackQL-verb: exec
  /admin/directory/v1/users/{userKey}/aliases/{alias}:
    delete:
      description: Removes an alias.
      operationId: directory.users.aliases.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
      x-stackQL-resource: aliases
      x-stackQL-verb: delete
  /admin/directory/v1/users/{userKey}/undelete:
    post:
      description: Undeletes a deleted user.
      operationId: directory.users.undelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: users
      x-stackQL-verb: exec
  /admin/directory/v1/users/{userKey}/makeAdmin:
    post:
      description: Makes a user a super administrator.
      operationId: directory.users.makeAdmin
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: users
      x-stackQL-verb: exec
  /admin/directory/v1/users/watch:
    post:
      description: Watches for changes in users list.
      operationId: directory.users.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: users
      x-stackQL-verb: exec
  /admin/directory/v1/users/{userKey}/signOut:
    post:
      description: >-
        Signs a user out of all web and device sessions and reset their sign-in
        cookies. User will have to sign in by authenticating again.
      operationId: directory.users.signOut
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: users
      x-stackQL-verb: exec
  /admin/directory/v1/users/{userKey}:
    delete:
      description: Deletes a user.
      operationId: directory.users.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: users
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates a user using patch semantics. The update method should be used
        instead, because it also supports patch semantics and has better
        performance. If you're mapping an external identity to a Google
        identity, use the
        [`update`](https://developers.google.com/admin-sdk/directory/v1/reference/users/update)
        method instead of the `patch` method. This method is unable to clear
        fields that contain repeated objects (`addresses`, `phones`, etc). Use
        the update method instead.
      operationId: directory.users.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: users
      x-stackQL-verb: exec
    put:
      description: >-
        Updates a user. This method supports patch semantics, meaning that you
        only need to include the fields you wish to update. Fields that are not
        present in the request will be preserved, and fields set to `null` will
        be cleared. For repeating fields that contain arrays, individual items
        in the array can't be patched piecemeal; they must be supplied in the
        request body with the desired values for all items. See the [user
        accounts
        guide](https://developers.google.com/admin-sdk/directory/v1/guides/manage-users#update_user)
        for more information.
      operationId: directory.users.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: users
      x-stackQL-verb: exec
    get:
      description: Retrieves a user.
      operationId: directory.users.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
      x-stackQL-resource: users
      x-stackQL-verb: select
  /admin/directory/v1/users:
    post:
      description: >-
        Creates a user. Mutate calls immediately following user creation might
        sometimes fail as the user isn't fully created due to propagation delay
        in our backends. Check the error details for the "User creation is not
        complete" message to see if this is the case. Retrying the calls after
        some time can help in this case.
      operationId: directory.users.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      x-stackQL-resource: users
      x-stackQL-verb: insert
    get:
      description: >-
        Retrieves a paginated list of either deleted users or all users in a
        domain.
      operationId: directory.users.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: users
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customer}/roles/ALL/privileges:
    get:
      description: Retrieves a paginated list of all privileges for a customer.
      operationId: directory.privileges.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      x-stackQL-resource: privileges
      x-stackQL-verb: select
  /admin/directory/v1/users/{userKey}/verificationCodes/generate:
    post:
      description: Generates new backup verification codes for the user.
      operationId: directory.verificationCodes.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: verification_codes
      x-stackQL-verb: exec
  /admin/directory/v1/users/{userKey}/verificationCodes/invalidate:
    post:
      description: Invalidates the current backup verification codes for the user.
      operationId: directory.verificationCodes.invalidate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: verification_codes
      x-stackQL-verb: exec
  /admin/directory/v1/users/{userKey}/verificationCodes:
    get:
      description: >-
        Returns the current set of valid backup verification codes for the
        specified user.
      operationId: directory.verificationCodes.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: verification_codes
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customerId}/devices/chromeos/moveDevicesToOu:
    post:
      description: >-
        Moves or inserts multiple Chrome OS devices to an organizational unit.
        You can move up to 50 devices at once.
      operationId: directory.chromeosdevices.moveDevicesToOu
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      x-stackQL-resource: chromeosdevices
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customerId}/devices/chromeos/{resourceId}/action:
    post:
      description: >-
        Takes an action that affects a Chrome OS Device. This includes
        deprovisioning, disabling, and re-enabling devices. *Warning:* *
        Deprovisioning a device will stop device policy syncing and remove
        device-level printers. After a device is deprovisioned, it must be wiped
        before it can be re-enrolled. * Lost or stolen devices should use the
        disable action. * Re-enabling a disabled device will consume a device
        license. If you do not have sufficient licenses available when
        completing the re-enable action, you will receive an error. For more
        information about deprovisioning and disabling devices, visit the [help
        center](https://support.google.com/chrome/a/answer/3523633).
      operationId: directory.chromeosdevices.action
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      x-stackQL-resource: chromeosdevices
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}:
    get:
      description: Retrieves a Chrome OS device's properties.
      operationId: directory.chromeosdevices.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
      x-stackQL-resource: chromeosdevices
      x-stackQL-verb: select
    put:
      description: >-
        Updates a device's updatable properties, such as `annotatedUser`,
        `annotatedLocation`, `notes`, `orgUnitPath`, or `annotatedAssetId`.
      operationId: directory.chromeosdevices.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      x-stackQL-resource: chromeosdevices
      x-stackQL-verb: exec
    patch:
      description: >-
        Updates a device's updatable properties, such as `annotatedUser`,
        `annotatedLocation`, `notes`, `orgUnitPath`, or `annotatedAssetId`. This
        method supports [patch
        semantics](/admin-sdk/directory/v1/guides/performance#patch).
      operationId: directory.chromeosdevices.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      x-stackQL-resource: chromeosdevices
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customerId}/devices/chromeos:
    get:
      description: Retrieves a paginated list of Chrome OS devices within an account.
      operationId: directory.chromeosdevices.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
      x-stackQL-resource: chromeosdevices
      x-stackQL-verb: select
  /admin/directory/v1/users/{userKey}/asps:
    get:
      description: Lists the ASPs issued by a user.
      operationId: directory.asps.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: asps
      x-stackQL-verb: select
  /admin/directory/v1/users/{userKey}/asps/{codeId}:
    get:
      description: Gets information about an ASP issued by a user.
      operationId: directory.asps.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: asps
      x-stackQL-verb: select
    delete:
      description: Deletes an ASP issued by a user.
      operationId: directory.asps.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: asps
      x-stackQL-verb: delete
  /admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}:
    delete:
      description: Removes a mobile device.
      operationId: directory.mobiledevices.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
      x-stackQL-resource: mobiledevices
      x-stackQL-verb: delete
    get:
      description: Retrieves a mobile device's properties.
      operationId: directory.mobiledevices.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.action
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.action
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
      x-stackQL-resource: mobiledevices
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customerId}/devices/mobile:
    get:
      description: >-
        Retrieves a paginated list of all user-owned mobile devices for an
        account. To retrieve a list that includes company-owned devices, use the
        Cloud Identity [Devices
        API](https://cloud.google.com/identity/docs/concepts/overview-devices)
        instead. This method times out after 60 minutes. For more information,
        see [Troubleshoot error
        codes](https://developers.google.com/admin-sdk/directory/v1/guides/troubleshoot-error-codes).
      operationId: directory.mobiledevices.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.action
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.action
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
      x-stackQL-resource: mobiledevices
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}/action:
    post:
      description: >-
        Takes an action that affects a mobile device. For example, remotely
        wiping a device.
      operationId: directory.mobiledevices.action
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.action
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.mobile.action
      x-stackQL-resource: mobiledevices
      x-stackQL-verb: exec
  /admin/directory/v1/users/{userKey}/tokens:
    get:
      description: >-
        Returns the set of tokens specified user has issued to 3rd party
        applications.
      operationId: directory.tokens.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: tokens
      x-stackQL-verb: select
  /admin/directory/v1/users/{userKey}/tokens/{clientId}:
    get:
      description: Gets information about an access token issued by a user.
      operationId: directory.tokens.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: tokens
      x-stackQL-verb: select
    delete:
      description: Deletes all access tokens issued by a user for an application.
      operationId: directory.tokens.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: tokens
      x-stackQL-verb: delete
  /admin/directory/v1/customer/{customer}/roles/{roleId}:
    put:
      description: Updates a role.
      operationId: directory.roles.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      x-stackQL-resource: roles
      x-stackQL-verb: exec
    get:
      description: Retrieves a role.
      operationId: directory.roles.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      x-stackQL-resource: roles
      x-stackQL-verb: select
    patch:
      description: Patches a role.
      operationId: directory.roles.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      x-stackQL-resource: roles
      x-stackQL-verb: exec
    delete:
      description: Deletes a role.
      operationId: directory.roles.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      x-stackQL-resource: roles
      x-stackQL-verb: delete
  /admin/directory/v1/customer/{customer}/roles:
    get:
      description: Retrieves a paginated list of all the roles in a domain.
      operationId: directory.roles.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      x-stackQL-resource: roles
      x-stackQL-verb: select
    post:
      description: Creates a role.
      operationId: directory.roles.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      x-stackQL-resource: roles
      x-stackQL-verb: insert
  /admin/directory/v1/users/{userKey}/twoStepVerification/turnOff:
    post:
      description: Turns off 2-Step Verification for user.
      operationId: directory.twoStepVerification.turnOff
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      x-stackQL-resource: two_step_verification
      x-stackQL-verb: exec
  /admin/directory_v1/channels/stop:
    post:
      description: Stops watching resources through this channel.
      operationId: admin.channels.stop
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.user.alias.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.user.alias.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      x-stackQL-resource: channels
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customer}/domainaliases/{domainAliasName}:
    get:
      description: Retrieves a domain alias of the customer.
      operationId: directory.domainAliases.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
      x-stackQL-resource: domain_aliases
      x-stackQL-verb: select
    delete:
      description: Deletes a domain Alias of the customer.
      operationId: directory.domainAliases.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
      x-stackQL-resource: domain_aliases
      x-stackQL-verb: delete
  /admin/directory/v1/customer/{customer}/domainaliases:
    post:
      description: Inserts a domain alias of the customer.
      operationId: directory.domainAliases.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
      x-stackQL-resource: domain_aliases
      x-stackQL-verb: insert
    get:
      description: Lists the domain aliases of the customer.
      operationId: directory.domainAliases.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
      x-stackQL-resource: domain_aliases
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customer}/domains:
    get:
      description: Lists the domains of the customer.
      operationId: directory.domains.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
      x-stackQL-resource: domains
      x-stackQL-verb: select
    post:
      description: Inserts a domain of the customer.
      operationId: directory.domains.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
      x-stackQL-resource: domains
      x-stackQL-verb: insert
  /admin/directory/v1/customer/{customer}/domains/{domainName}:
    get:
      description: Retrieves a domain of the customer.
      operationId: directory.domains.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
      x-stackQL-resource: domains
      x-stackQL-verb: select
    delete:
      description: Deletes a domain of the customer.
      operationId: directory.domains.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
      x-stackQL-resource: domains
      x-stackQL-verb: delete
  /admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}/commands/{commandId}:
    get:
      description: Gets command data a specific command issued to the device.
      operationId: admin.customer.devices.chromeos.commands.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
      x-stackQL-resource: commands
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}:issueCommand:
    post:
      description: Issues a command for the device to execute.
      operationId: admin.customer.devices.chromeos.issueCommand
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      x-stackQL-resource: chromeos
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customer}/roleassignments/{roleAssignmentId}:
    get:
      description: Retrieves a role assignment.
      operationId: directory.roleAssignments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      x-stackQL-resource: role_assignments
      x-stackQL-verb: select
    delete:
      description: Deletes a role assignment.
      operationId: directory.roleAssignments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      x-stackQL-resource: role_assignments
      x-stackQL-verb: delete
  /admin/directory/v1/customer/{customer}/roleassignments:
    get:
      description: Retrieves a paginated list of all roleAssignments.
      operationId: directory.roleAssignments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      x-stackQL-resource: role_assignments
      x-stackQL-verb: select
    post:
      description: Creates a role assignment.
      operationId: directory.roleAssignments.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      x-stackQL-resource: role_assignments
      x-stackQL-verb: insert
  /admin/directory/v1/customer/{customerId}/orgunits:
    post:
      description: Adds an organizational unit.
      operationId: directory.orgunits.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
      x-stackQL-resource: orgunits
      x-stackQL-verb: insert
    get:
      description: Retrieves a list of all organizational units for an account.
      operationId: directory.orgunits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit.readonly
      x-stackQL-resource: orgunits
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customerId}/orgunits/{orgunitsId}:
    patch:
      description: >-
        Updates an organizational unit. This method supports [patch
        semantics](/admin-sdk/directory/v1/guides/performance#patch)
      operationId: directory.orgunits.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
      x-stackQL-resource: orgunits
      x-stackQL-verb: exec
    delete:
      description: Removes an organizational unit.
      operationId: directory.orgunits.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
      x-stackQL-resource: orgunits
      x-stackQL-verb: delete
    get:
      description: Retrieves an organizational unit.
      operationId: directory.orgunits.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit.readonly
      x-stackQL-resource: orgunits
      x-stackQL-verb: select
    put:
      description: Updates an organizational unit.
      operationId: directory.orgunits.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
      x-stackQL-resource: orgunits
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customer}/resources/calendars:
    post:
      description: Inserts a calendar resource.
      operationId: directory.resources.calendars.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: insert
    get:
      description: Retrieves a list of calendar resources for an account.
      operationId: directory.resources.calendars.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      x-stackQL-resource: calendars
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}:
    patch:
      description: Patches a calendar resource.
      operationId: directory.resources.calendars.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: exec
    get:
      description: Retrieves a calendar resource.
      operationId: directory.resources.calendars.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      x-stackQL-resource: calendars
      x-stackQL-verb: select
    delete:
      description: Deletes a calendar resource.
      operationId: directory.resources.calendars.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: delete
    put:
      description: >-
        Updates a calendar resource. This method supports patch semantics,
        meaning you only need to include the fields you wish to update. Fields
        that are not present in the request will be preserved.
      operationId: directory.resources.calendars.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}:
    put:
      description: Updates a building.
      operationId: directory.resources.buildings.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: buildings
      x-stackQL-verb: exec
    patch:
      description: Patches a building.
      operationId: directory.resources.buildings.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: buildings
      x-stackQL-verb: exec
    delete:
      description: Deletes a building.
      operationId: directory.resources.buildings.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: buildings
      x-stackQL-verb: delete
    get:
      description: Retrieves a building.
      operationId: directory.resources.buildings.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      x-stackQL-resource: buildings
      x-stackQL-verb: select
  /admin/directory/v1/customer/{customer}/resources/buildings:
    get:
      description: Retrieves a list of buildings for an account.
      operationId: directory.resources.buildings.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      x-stackQL-resource: buildings
      x-stackQL-verb: select
    post:
      description: Inserts a building.
      operationId: directory.resources.buildings.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: buildings
      x-stackQL-verb: insert
  /admin/directory/v1/customer/{customer}/resources/features:
    get:
      description: Retrieves a list of features for an account.
      operationId: directory.resources.features.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      x-stackQL-resource: features
      x-stackQL-verb: select
    post:
      description: Inserts a feature.
      operationId: directory.resources.features.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: features
      x-stackQL-verb: insert
  /admin/directory/v1/customer/{customer}/resources/features/{featureKey}:
    put:
      description: Updates a feature.
      operationId: directory.resources.features.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: features
      x-stackQL-verb: exec
    get:
      description: Retrieves a feature.
      operationId: directory.resources.features.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      x-stackQL-resource: features
      x-stackQL-verb: select
    delete:
      description: Deletes a feature.
      operationId: directory.resources.features.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: features
      x-stackQL-verb: delete
    patch:
      description: Patches a feature.
      operationId: directory.resources.features.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: features
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customer}/resources/features/{oldName}/rename:
    post:
      description: Renames a feature.
      operationId: directory.resources.features.rename
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      x-stackQL-resource: features
      x-stackQL-verb: exec
  /admin/directory/v1/customers/{customersId}/chrome/printers:batchCreatePrinters:
    post:
      description: Creates printers under given Organization Unit.
      operationId: admin.customers.chrome.printers.batchCreatePrinters
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: printers
      x-stackQL-verb: exec
  /admin/directory/v1/customers/{customersId}/chrome/printers:batchDeletePrinters:
    post:
      description: Deletes printers in batch.
      operationId: admin.customers.chrome.printers.batchDeletePrinters
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: printers
      x-stackQL-verb: exec
  /admin/directory/v1/customers/{customersId}/chrome/printers/{printersId}:
    get:
      description: Returns a `Printer` resource (printer's config).
      operationId: admin.customers.chrome.printers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
      x-stackQL-resource: printers
      x-stackQL-verb: select
    delete:
      description: Deletes a `Printer`.
      operationId: admin.customers.chrome.printers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: printers
      x-stackQL-verb: delete
    patch:
      description: Updates a `Printer` resource.
      operationId: admin.customers.chrome.printers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: printers
      x-stackQL-verb: exec
  /admin/directory/v1/customers/{customersId}/chrome/printers:
    post:
      description: Creates a printer under given Organization Unit.
      operationId: admin.customers.chrome.printers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: printers
      x-stackQL-verb: insert
    get:
      description: List printers configs.
      operationId: admin.customers.chrome.printers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
      x-stackQL-resource: printers
      x-stackQL-verb: select
  /admin/directory/v1/customers/{customersId}/chrome/printers:listPrinterModels:
    get:
      description: Lists the supported printer models.
      operationId: admin.customers.chrome.printers.listPrinterModels
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
      x-stackQL-resource: printers__printer_models
      x-stackQL-verb: select
  /admin/directory/v1/customers/{customersId}/chrome/printServers:
    get:
      description: Lists print server configurations.
      operationId: admin.customers.chrome.printServers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
      x-stackQL-resource: print_servers
      x-stackQL-verb: select
    post:
      description: Creates a print server.
      operationId: admin.customers.chrome.printServers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: print_servers
      x-stackQL-verb: insert
  /admin/directory/v1/customers/{customersId}/chrome/printServers:batchDeletePrintServers:
    post:
      description: Deletes multiple print servers.
      operationId: admin.customers.chrome.printServers.batchDeletePrintServers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: print_servers
      x-stackQL-verb: exec
  /admin/directory/v1/customers/{customersId}/chrome/printServers/{printServersId}:
    delete:
      description: Deletes a print server.
      operationId: admin.customers.chrome.printServers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: print_servers
      x-stackQL-verb: delete
    get:
      description: Returns a print server's configuration.
      operationId: admin.customers.chrome.printServers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers.readonly
      x-stackQL-resource: print_servers
      x-stackQL-verb: select
    patch:
      description: Updates a print server's configuration.
      operationId: admin.customers.chrome.printServers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: print_servers
      x-stackQL-verb: exec
  /admin/directory/v1/customers/{customersId}/chrome/printServers:batchCreatePrintServers:
    post:
      description: Creates multiple print servers.
      operationId: admin.customers.chrome.printServers.batchCreatePrintServers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.chrome.printers
          Oauth2c:
            - https://www.googleapis.com/auth/admin.chrome.printers
      x-stackQL-resource: print_servers
      x-stackQL-verb: exec
  /admin/directory/v1/customers/{customerKey}:
    get:
      description: Retrieves a customer.
      operationId: directory.customers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.customer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.customer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.customer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.customer.readonly
      x-stackQL-resource: customers
      x-stackQL-verb: select
    patch:
      description: Patches a customer.
      operationId: directory.customers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.customer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.customer
      x-stackQL-resource: customers
      x-stackQL-verb: exec
    put:
      description: Updates a customer.
      operationId: directory.customers.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.customer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.customer
      x-stackQL-resource: customers
      x-stackQL-verb: exec
  /admin/directory/v1/groups/{groupKey}/members/{memberKey}:
    put:
      description: Updates the membership of a user in the specified group.
      operationId: directory.members.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
      x-stackQL-resource: members
      x-stackQL-verb: exec
    get:
      description: Retrieves a group member's properties.
      operationId: directory.members.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.group.member.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.group.member.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      x-stackQL-resource: members
      x-stackQL-verb: select
    patch:
      description: >-
        Updates the membership properties of a user in the specified group. This
        method supports [patch
        semantics](/admin-sdk/directory/v1/guides/performance#patch).
      operationId: directory.members.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
      x-stackQL-resource: members
      x-stackQL-verb: exec
    delete:
      description: Removes a member from a group.
      operationId: directory.members.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
      x-stackQL-resource: members
      x-stackQL-verb: delete
  /admin/directory/v1/groups/{groupKey}/hasMember/{memberKey}:
    get:
      description: >-
        Checks whether the given user is a member of the group. Membership can
        be direct or nested, but if nested, the `memberKey` and `groupKey` must
        be entities in the same domain or an `Invalid input` error is returned.
        To check for nested memberships that include entities outside of the
        group's domain, use the
        [`checkTransitiveMembership()`](https://cloud.google.com/identity/docs/reference/rest/v1/groups.memberships/checkTransitiveMembership)
        method in the Cloud Identity Groups API.
      operationId: directory.members.hasMember
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.group.member.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.group.member.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      x-stackQL-resource: members
      x-stackQL-verb: exec
  /admin/directory/v1/groups/{groupKey}/members:
    get:
      description: >-
        Retrieves a paginated list of all members in a group. This method times
        out after 60 minutes. For more information, see [Troubleshoot error
        codes](https://developers.google.com/admin-sdk/directory/v1/guides/troubleshoot-error-codes).
      operationId: directory.members.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.group.member.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.group.member.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      x-stackQL-resource: members
      x-stackQL-verb: select
    post:
      description: Adds a user to the specified group.
      operationId: directory.members.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
      x-stackQL-resource: members
      x-stackQL-verb: insert
  /admin/directory/v1/groups:
    get:
      description: >-
        Retrieves all groups of a domain or of a user given a userKey
        (paginated).
      operationId: directory.groups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      x-stackQL-resource: groups
      x-stackQL-verb: select
    post:
      description: Creates a group.
      operationId: directory.groups.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      x-stackQL-resource: groups
      x-stackQL-verb: insert
  /admin/directory/v1/groups/{groupKey}:
    get:
      description: Retrieves a group's properties.
      operationId: directory.groups.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      x-stackQL-resource: groups
      x-stackQL-verb: select
    put:
      description: Updates a group's properties.
      operationId: directory.groups.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      x-stackQL-resource: groups
      x-stackQL-verb: exec
    delete:
      description: Deletes a group.
      operationId: directory.groups.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      x-stackQL-resource: groups
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates a group's properties. This method supports [patch
        semantics](/admin-sdk/directory/v1/guides/performance#patch).
      operationId: directory.groups.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      x-stackQL-resource: groups
      x-stackQL-verb: exec
  /admin/directory/v1/groups/{groupKey}/aliases:
    post:
      description: Adds an alias for the group.
      operationId: directory.groups.aliases.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      x-stackQL-resource: aliases
      x-stackQL-verb: insert
    get:
      description: Lists all aliases for a group.
      operationId: directory.groups.aliases.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      x-stackQL-resource: aliases
      x-stackQL-verb: select
  /admin/directory/v1/groups/{groupKey}/aliases/{alias}:
    delete:
      description: Removes an alias.
      operationId: directory.groups.aliases.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      x-stackQL-resource: aliases
      x-stackQL-verb: delete
  /admin/directory/v1/customer/{customerId}/schemas/{schemaKey}:
    patch:
      description: Patches a schema.
      operationId: directory.schemas.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
      x-stackQL-resource: schemas
      x-stackQL-verb: exec
    get:
      description: Retrieves a schema.
      operationId: directory.schemas.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.userschema.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.userschema.readonly
      x-stackQL-resource: schemas
      x-stackQL-verb: select
    delete:
      description: Deletes a schema.
      operationId: directory.schemas.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
      x-stackQL-resource: schemas
      x-stackQL-verb: delete
    put:
      description: Updates a schema.
      operationId: directory.schemas.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
      x-stackQL-resource: schemas
      x-stackQL-verb: exec
  /admin/directory/v1/customer/{customerId}/schemas:
    post:
      description: Creates a schema.
      operationId: directory.schemas.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
      x-stackQL-resource: schemas
      x-stackQL-verb: insert
    get:
      description: Retrieves all schemas for a customer.
      operationId: directory.schemas.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/admin.directory.userschema.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/admin.directory.userschema.readonly
      x-stackQL-resource: schemas
      x-stackQL-verb: select
