openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Admin SDK API
  description: >-
    Admin SDK lets administrators of enterprise domains to view and manage
    resources like user, groups etc. It also provides audit and usage reports of
    domain.
  version: datatransfer_v1
  x-discovery-doc-revision: '20230619'
  x-generated-date: '2023-06-25'
servers:
  - url: https://admin.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/admin.datatransfer: View and manage data transfers between users in your organization
            https://www.googleapis.com/auth/admin.datatransfer.readonly: View data transfers between users in your organization
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /admin/datatransfer/v1/transfers/{dataTransferId}:
    get:
      description: Retrieves a data transfer request by its resource ID.
      operationId: datatransfer.transfers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      x-stackQL-resource: transfers
      x-stackQL-verb: select
  /admin/datatransfer/v1/transfers:
    get:
      description: >-
        Lists the transfers for a customer by source user, destination user, or
        status.
      operationId: datatransfer.transfers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      x-stackQL-resource: transfers
      x-stackQL-verb: select
    post:
      description: >-
        Inserts a data transfer request. See the [Transfer
        parameters](/admin-sdk/data-transfer/v1/parameters) reference for
        specific application requirements.
      operationId: datatransfer.transfers.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
      x-stackQL-resource: transfers
      x-stackQL-verb: insert
  /admin/datatransfer/v1/applications:
    get:
      description: Lists the applications available for data transfer for a customer.
      operationId: datatransfer.applications.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      x-stackQL-resource: applications
      x-stackQL-verb: select
  /admin/datatransfer/v1/applications/{applicationId}:
    get:
      description: Retrieves information about an application for the given application ID.
      operationId: datatransfer.applications.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      x-stackQL-resource: applications
      x-stackQL-verb: select
