openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Admin SDK API
  description: >-
    Admin SDK lets administrators of enterprise domains to view and manage
    resources like user, groups etc. It also provides audit and usage reports of
    domain.
  version: reports_v1
  x-discovery-doc-revision: '20230619'
  x-generated-date: '2023-06-25'
servers:
  - url: https://admin.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/admin.reports.usage.readonly: View usage reports for your G Suite domain
            https://www.googleapis.com/auth/admin.reports.audit.readonly: View audit reports for your G Suite domain
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /admin/reports/v1/usage/dates/{date}:
    get:
      description: >-
        Retrieves a report which is a collection of properties and statistics
        for a specific customer's account. For more information, see the
        Customers Usage Report guide. For more information about the customer
        report's parameters, see the Customers Usage parameters reference
        guides. 
      operationId: reports.customerUsageReports.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.reports.usage.readonly
      x-stackQL-resource: customer_usage_reports
      x-stackQL-verb: select
  /admin/reports/v1/activity/users/{userKey}/applications/{applicationName}/watch:
    post:
      description: >-
        Start receiving notifications for account activities. For more
        information, see Receiving Push Notifications.
      operationId: reports.activities.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.reports.audit.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.reports.audit.readonly
      x-stackQL-resource: activities
      x-stackQL-verb: exec
  /admin/reports/v1/activity/users/{userKey}/applications/{applicationName}:
    get:
      description: >-
        Retrieves a list of activities for a specific customer's account and
        application such as the Admin console application or the Google Drive
        application. For more information, see the guides for administrator and
        Google Drive activity reports. For more information about the activity
        report's parameters, see the activity parameters reference guides. 
      operationId: reports.activities.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.reports.audit.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.reports.audit.readonly
      x-stackQL-resource: activities
      x-stackQL-verb: select
  /admin/reports/v1/usage/{entityType}/{entityKey}/dates/{date}:
    get:
      description: >-
        Retrieves a report which is a collection of properties and statistics
        for entities used by users within the account. For more information, see
        the Entities Usage Report guide. For more information about the entities
        report's parameters, see the Entities Usage parameters reference guides.
      operationId: reports.entityUsageReports.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.reports.usage.readonly
      x-stackQL-resource: entity_usage_reports
      x-stackQL-verb: select
  /admin/reports/v1/usage/users/{userKey}/dates/{date}:
    get:
      description: >-
        Retrieves a report which is a collection of properties and statistics
        for a set of users with the account. For more information, see the User
        Usage Report guide. For more information about the user report's
        parameters, see the Users Usage parameters reference guides.
      operationId: reports.userUsageReport.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.reports.usage.readonly
      x-stackQL-resource: user_usage_report
      x-stackQL-verb: select
  /admin/reports_v1/channels/stop:
    post:
      description: Stop watching resources through this channel.
      operationId: admin.channels.stop
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.reports.audit.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.reports.audit.readonly
      x-stackQL-resource: channels
      x-stackQL-verb: exec
