openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Tag Manager API
  description: >-
    This API allows clients to access and modify container and tag
    configuration.
  version: v2
  x-discovery-doc-revision: '20230621'
  x-generated-date: '2023-06-25'
servers:
  - url: https://tagmanager.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/tagmanager.readonly: View your Google Tag Manager container and its subcomponents
            https://www.googleapis.com/auth/tagmanager.manage.accounts: View and manage your Google Tag Manager accounts
            https://www.googleapis.com/auth/tagmanager.edit.containerversions: Manage your Google Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.edit.containers: >-
              Manage your Google Tag Manager container and its subcomponents,
              excluding versioning and publishing
            https://www.googleapis.com/auth/tagmanager.publish: Publish your Google Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.manage.users: >-
              Manage user permissions of your Google Tag Manager account and
              container
            https://www.googleapis.com/auth/tagmanager.delete.containers: Delete your Google Tag Manager containers
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /tagmanager/v2/accounts/{accountsId}:
    get:
      description: Gets a GTM Account.
      operationId: tagmanager.accounts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
    put:
      description: Updates a GTM Account.
      operationId: tagmanager.accounts.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /tagmanager/v2/accounts:
    get:
      description: Lists all GTM Accounts that a user has access to.
      operationId: tagmanager.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/version_headers:latest:
    get:
      description: Gets the latest container version header
      operationId: tagmanager.accounts.containers.version_headers.latest
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: version_headers
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/version_headers:
    get:
      description: Lists all Container Versions of a GTM Container.
      operationId: tagmanager.accounts.containers.version_headers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: version_headers
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:
    put:
      description: Updates a Container Version.
      operationId: tagmanager.accounts.containers.versions.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: versions
      x-stackQL-verb: exec
    get:
      description: Gets a Container Version.
      operationId: tagmanager.accounts.containers.versions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: versions
      x-stackQL-verb: select
    delete:
      description: Deletes a Container Version.
      operationId: tagmanager.accounts.containers.versions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: versions
      x-stackQL-verb: delete
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions:live:
    get:
      description: Gets the live (i.e. published) container version
      operationId: tagmanager.accounts.containers.versions.live
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: versions
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:publish:
    post:
      description: Publishes a Container Version.
      operationId: tagmanager.accounts.containers.versions.publish
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.publish
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.publish
      x-stackQL-resource: versions
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:undelete:
    post:
      description: Undeletes a Container Version.
      operationId: tagmanager.accounts.containers.versions.undelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: versions
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:set_latest:
    post:
      description: >-
        Sets the latest version used for synchronization of workspaces when
        detecting conflicts and errors.
      operationId: tagmanager.accounts.containers.versions.set_latest
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: versions
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments:
    post:
      description: Creates a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: environments
      x-stackQL-verb: insert
    get:
      description: Lists all GTM Environments of a GTM Container.
      operationId: tagmanager.accounts.containers.environments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: environments
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}:
    put:
      description: Updates a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: environments
      x-stackQL-verb: exec
    delete:
      description: Deletes a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: environments
      x-stackQL-verb: delete
    get:
      description: Gets a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: environments
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}:reauthorize:
    post:
      description: Re-generates the authorization code for a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.reauthorize
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.publish
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.publish
      x-stackQL-resource: environments
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/destinations/{destinationsId}:
    get:
      description: Gets a Destination.
      operationId: tagmanager.accounts.containers.destinations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: destinations
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/destinations:link:
    post:
      description: >-
        Adds a Destination to this Container and removes it from the Container
        to which it is currently linked.
      operationId: tagmanager.accounts.containers.destinations.link
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: destinations
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/destinations:
    get:
      description: Lists all Destinations linked to a GTM Container.
      operationId: tagmanager.accounts.containers.destinations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: destinations
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}:
    get:
      description: Gets a GTM Zone.
      operationId: tagmanager.accounts.containers.workspaces.zones.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: zones
      x-stackQL-verb: select
    put:
      description: Updates a GTM Zone.
      operationId: tagmanager.accounts.containers.workspaces.zones.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: zones
      x-stackQL-verb: exec
    delete:
      description: Deletes a GTM Zone.
      operationId: tagmanager.accounts.containers.workspaces.zones.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: zones
      x-stackQL-verb: delete
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}:revert:
    post:
      description: Reverts changes to a GTM Zone in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.zones.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: zones
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones:
    get:
      description: Lists all GTM Zones of a GTM container workspace.
      operationId: tagmanager.accounts.containers.workspaces.zones.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: zones
      x-stackQL-verb: select
    post:
      description: Creates a GTM Zone.
      operationId: tagmanager.accounts.containers.workspaces.zones.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: zones
      x-stackQL-verb: insert
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations:
    post:
      description: Creates a GTM Transformation.
      operationId: tagmanager.accounts.containers.workspaces.transformations.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: transformations
      x-stackQL-verb: insert
    get:
      description: Lists all GTM Transformations of a GTM container workspace.
      operationId: tagmanager.accounts.containers.workspaces.transformations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: transformations
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations/{transformationsId}:
    get:
      description: Gets a GTM Transformation.
      operationId: tagmanager.accounts.containers.workspaces.transformations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: transformations
      x-stackQL-verb: select
    delete:
      description: Deletes a GTM Transformation.
      operationId: tagmanager.accounts.containers.workspaces.transformations.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: transformations
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Transformation.
      operationId: tagmanager.accounts.containers.workspaces.transformations.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: transformations
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations/{transformationsId}:revert:
    post:
      description: Reverts changes to a GTM Transformation in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.transformations.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: transformations
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients/{clientsId}:
    get:
      description: Gets a GTM Client.
      operationId: tagmanager.accounts.containers.workspaces.clients.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: clients
      x-stackQL-verb: select
    put:
      description: Updates a GTM Client.
      operationId: tagmanager.accounts.containers.workspaces.clients.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: clients
      x-stackQL-verb: exec
    delete:
      description: Deletes a GTM Client.
      operationId: tagmanager.accounts.containers.workspaces.clients.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: clients
      x-stackQL-verb: delete
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients/{clientsId}:revert:
    post:
      description: Reverts changes to a GTM Client in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.clients.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: clients
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients:
    post:
      description: Creates a GTM Client.
      operationId: tagmanager.accounts.containers.workspaces.clients.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: clients
      x-stackQL-verb: insert
    get:
      description: Lists all GTM Clients of a GTM container workspace.
      operationId: tagmanager.accounts.containers.workspaces.clients.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: clients
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}:
    put:
      description: Updates a GTM Tag.
      operationId: tagmanager.accounts.containers.workspaces.tags.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: tags
      x-stackQL-verb: exec
    delete:
      description: Deletes a GTM Tag.
      operationId: tagmanager.accounts.containers.workspaces.tags.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: tags
      x-stackQL-verb: delete
    get:
      description: Gets a GTM Tag.
      operationId: tagmanager.accounts.containers.workspaces.tags.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: tags
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags:
    get:
      description: Lists all GTM Tags of a Container.
      operationId: tagmanager.accounts.containers.workspaces.tags.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: tags
      x-stackQL-verb: select
    post:
      description: Creates a GTM Tag.
      operationId: tagmanager.accounts.containers.workspaces.tags.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: tags
      x-stackQL-verb: insert
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}:revert:
    post:
      description: Reverts changes to a GTM Tag in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.tags.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: tags
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}:revert:
    post:
      description: Reverts changes to a GTM Variable in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.variables.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: variables
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}:
    get:
      description: Gets a GTM Variable.
      operationId: tagmanager.accounts.containers.workspaces.variables.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: variables
      x-stackQL-verb: select
    delete:
      description: Deletes a GTM Variable.
      operationId: tagmanager.accounts.containers.workspaces.variables.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: variables
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Variable.
      operationId: tagmanager.accounts.containers.workspaces.variables.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: variables
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables:
    get:
      description: Lists all GTM Variables of a Container.
      operationId: tagmanager.accounts.containers.workspaces.variables.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: variables
      x-stackQL-verb: select
    post:
      description: Creates a GTM Variable.
      operationId: tagmanager.accounts.containers.workspaces.variables.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: variables
      x-stackQL-verb: insert
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:
    delete:
      description: Deletes a GTM Folder.
      operationId: tagmanager.accounts.containers.workspaces.folders.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: folders
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Folder.
      operationId: tagmanager.accounts.containers.workspaces.folders.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: folders
      x-stackQL-verb: exec
    get:
      description: Gets a GTM Folder.
      operationId: tagmanager.accounts.containers.workspaces.folders.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: folders
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:entities:
    post:
      description: List all entities in a GTM Folder.
      operationId: tagmanager.accounts.containers.workspaces.folders.entities
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: folders
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders:
    post:
      description: Creates a GTM Folder.
      operationId: tagmanager.accounts.containers.workspaces.folders.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: folders
      x-stackQL-verb: insert
    get:
      description: Lists all GTM Folders of a Container.
      operationId: tagmanager.accounts.containers.workspaces.folders.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: folders
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:revert:
    post:
      description: Reverts changes to a GTM Folder in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.folders.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: folders
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:move_entities_to_folder:
    post:
      description: Moves entities to a GTM Folder.
      operationId: >-
        tagmanager.accounts.containers.workspaces.folders.move_entities_to_folder
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: folders
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/gtag_config:
    post:
      description: Creates a Google tag config.
      operationId: tagmanager.accounts.containers.workspaces.gtag_config.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: gtag_config
      x-stackQL-verb: insert
    get:
      description: Lists all Google tag configs in a Container.
      operationId: tagmanager.accounts.containers.workspaces.gtag_config.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: gtag_config
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/gtag_config/{gtag_configId}:
    delete:
      description: Deletes a Google tag config.
      operationId: tagmanager.accounts.containers.workspaces.gtag_config.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: gtag_config
      x-stackQL-verb: delete
    get:
      description: Gets a Google tag config.
      operationId: tagmanager.accounts.containers.workspaces.gtag_config.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: gtag_config
      x-stackQL-verb: select
    put:
      description: Updates a Google tag config.
      operationId: tagmanager.accounts.containers.workspaces.gtag_config.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: gtag_config
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}:
    delete:
      description: Deletes a GTM Template.
      operationId: tagmanager.accounts.containers.workspaces.templates.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: templates
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Template.
      operationId: tagmanager.accounts.containers.workspaces.templates.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: templates
      x-stackQL-verb: exec
    get:
      description: Gets a GTM Template.
      operationId: tagmanager.accounts.containers.workspaces.templates.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: templates
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates:
    get:
      description: Lists all GTM Templates of a GTM container workspace.
      operationId: tagmanager.accounts.containers.workspaces.templates.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: templates
      x-stackQL-verb: select
    post:
      description: Creates a GTM Custom Template.
      operationId: tagmanager.accounts.containers.workspaces.templates.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: templates
      x-stackQL-verb: insert
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}:revert:
    post:
      description: Reverts changes to a GTM Template in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.templates.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: templates
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables:revert:
    post:
      description: Reverts changes to a GTM Built-In Variables in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.built_in_variables.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: built_in_variables
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables:
    post:
      description: Creates one or more GTM Built-In Variables.
      operationId: tagmanager.accounts.containers.workspaces.built_in_variables.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: built_in_variables
      x-stackQL-verb: insert
    delete:
      description: Deletes one or more GTM Built-In Variables.
      operationId: tagmanager.accounts.containers.workspaces.built_in_variables.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: built_in_variables
      x-stackQL-verb: delete
    get:
      description: Lists all the enabled Built-In Variables of a GTM Container.
      operationId: tagmanager.accounts.containers.workspaces.built_in_variables.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: built_in_variables
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}:
    get:
      description: Gets a GTM Trigger.
      operationId: tagmanager.accounts.containers.workspaces.triggers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: triggers
      x-stackQL-verb: select
    delete:
      description: Deletes a GTM Trigger.
      operationId: tagmanager.accounts.containers.workspaces.triggers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: triggers
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Trigger.
      operationId: tagmanager.accounts.containers.workspaces.triggers.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: triggers
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers:
    get:
      description: Lists all GTM Triggers of a Container.
      operationId: tagmanager.accounts.containers.workspaces.triggers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: triggers
      x-stackQL-verb: select
    post:
      description: Creates a GTM Trigger.
      operationId: tagmanager.accounts.containers.workspaces.triggers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: triggers
      x-stackQL-verb: insert
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}:revert:
    post:
      description: Reverts changes to a GTM Trigger in a GTM Workspace.
      operationId: tagmanager.accounts.containers.workspaces.triggers.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: triggers
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:
    delete:
      description: Deletes a Workspace.
      operationId: tagmanager.accounts.containers.workspaces.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.delete.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.delete.containers
      x-stackQL-resource: workspaces
      x-stackQL-verb: delete
    get:
      description: Gets a Workspace.
      operationId: tagmanager.accounts.containers.workspaces.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: workspaces
      x-stackQL-verb: select
    put:
      description: Updates a Workspace.
      operationId: tagmanager.accounts.containers.workspaces.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: workspaces
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:sync:
    post:
      description: >-
        Syncs a workspace to the latest container version by updating all
        unmodified workspace entities and displaying conflicts for modified
        entities.
      operationId: tagmanager.accounts.containers.workspaces.sync
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: workspaces
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/status:
    get:
      description: Finds conflicting and modified entities in the workspace.
      operationId: tagmanager.accounts.containers.workspaces.getStatus
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: workspaces__status
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:create_version:
    post:
      description: >-
        Creates a Container Version from the entities present in the workspace,
        deletes the workspace, and sets the base container version to the newly
        created version.
      operationId: tagmanager.accounts.containers.workspaces.create_version
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: workspaces__version
      x-stackQL-verb: insert
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:resolve_conflict:
    post:
      description: >-
        Resolves a merge conflict for a workspace entity by updating it to the
        resolved entity passed in the request.
      operationId: tagmanager.accounts.containers.workspaces.resolve_conflict
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: workspaces
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:quick_preview:
    post:
      description: >-
        Quick previews a workspace by creating a fake container version from all
        entities in the provided workspace.
      operationId: tagmanager.accounts.containers.workspaces.quick_preview
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: workspaces
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces:
    post:
      description: Creates a Workspace.
      operationId: tagmanager.accounts.containers.workspaces.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: workspaces
      x-stackQL-verb: insert
    get:
      description: Lists all Workspaces that belong to a GTM Container.
      operationId: tagmanager.accounts.containers.workspaces.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: workspaces
      x-stackQL-verb: select
  /tagmanager/v2/accounts/{accountsId}/containers:
    get:
      description: Lists all Containers that belongs to a GTM Account.
      operationId: tagmanager.accounts.containers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: containers
      x-stackQL-verb: select
    post:
      description: Creates a Container.
      operationId: tagmanager.accounts.containers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: containers
      x-stackQL-verb: insert
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}:combine:
    post:
      description: Combines Containers.
      operationId: tagmanager.accounts.containers.combine
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: containers
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}:
    get:
      description: Gets a Container.
      operationId: tagmanager.accounts.containers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: containers
      x-stackQL-verb: select
    put:
      description: Updates a Container.
      operationId: tagmanager.accounts.containers.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: containers
      x-stackQL-verb: exec
    delete:
      description: Deletes a Container.
      operationId: tagmanager.accounts.containers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.delete.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.delete.containers
      x-stackQL-resource: containers
      x-stackQL-verb: delete
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}:move_tag_id:
    post:
      description: Move Tag ID out of a Container.
      operationId: tagmanager.accounts.containers.move_tag_id
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: containers
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/containers/{containersId}:snippet:
    get:
      description: Gets the tagging snippet for a Container.
      operationId: tagmanager.accounts.containers.snippet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: containers
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/containers:lookup:
    get:
      description: Looks up a Container by destination ID.
      operationId: tagmanager.accounts.containers.lookup
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: containers
      x-stackQL-verb: exec
  /tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}:
    put:
      description: Updates a user's Account & Container access.
      operationId: tagmanager.accounts.user_permissions.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: user_permissions
      x-stackQL-verb: exec
    get:
      description: Gets a user's Account & Container access.
      operationId: tagmanager.accounts.user_permissions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: user_permissions
      x-stackQL-verb: select
    delete:
      description: >-
        Removes a user from the account, revoking access to it and all of its
        containers.
      operationId: tagmanager.accounts.user_permissions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: user_permissions
      x-stackQL-verb: delete
  /tagmanager/v2/accounts/{accountsId}/user_permissions:
    post:
      description: Creates a user's Account & Container access.
      operationId: tagmanager.accounts.user_permissions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: user_permissions
      x-stackQL-verb: insert
    get:
      description: >-
        List all users that have access to the account along with Account and
        Container user access granted to each of them.
      operationId: tagmanager.accounts.user_permissions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: user_permissions
      x-stackQL-verb: select
