openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Tag Manager API
  description: >-
    This API allows clients to access and modify container and tag
    configuration.
  version: v1
  x-discovery-doc-revision: '20230621'
  x-generated-date: '2023-06-25'
servers:
  - url: https://tagmanager.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/tagmanager.publish: Publish your Google Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.edit.containers: >-
              Manage your Google Tag Manager container and its subcomponents,
              excluding versioning and publishing
            https://www.googleapis.com/auth/tagmanager.manage.users: >-
              Manage user permissions of your Google Tag Manager account and
              container
            https://www.googleapis.com/auth/tagmanager.manage.accounts: View and manage your Google Tag Manager accounts
            https://www.googleapis.com/auth/tagmanager.readonly: View your Google Tag Manager container and its subcomponents
            https://www.googleapis.com/auth/tagmanager.delete.containers: Delete your Google Tag Manager containers
            https://www.googleapis.com/auth/tagmanager.edit.containerversions: Manage your Google Tag Manager container versions
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /tagmanager/v1/accounts/{accountId}/permissions:
    post:
      description: Creates a user's Account & Container Permissions.
      operationId: tagmanager.accounts.permissions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: permissions
      x-stackQL-verb: insert
    get:
      description: >-
        List all users that have access to the account along with Account and
        Container Permissions granted to each of them.
      operationId: tagmanager.accounts.permissions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: permissions
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/permissions/{permissionId}:
    get:
      description: Gets a user's Account & Container Permissions.
      operationId: tagmanager.accounts.permissions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: permissions
      x-stackQL-verb: select
    put:
      description: Updates a user's Account & Container Permissions.
      operationId: tagmanager.accounts.permissions.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: permissions
      x-stackQL-verb: exec
    delete:
      description: >-
        Removes a user from the account, revoking access to it and all of its
        containers.
      operationId: tagmanager.accounts.permissions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.users
      x-stackQL-resource: permissions
      x-stackQL-verb: delete
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/move_folders/{folderId}:
    put:
      description: Moves entities to a GTM Folder.
      operationId: tagmanager.accounts.containers.move_folders.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: move_folders
      x-stackQL-verb: exec
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}:
    delete:
      description: Deletes a GTM Trigger.
      operationId: tagmanager.accounts.containers.triggers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: triggers
      x-stackQL-verb: delete
    get:
      description: Gets a GTM Trigger.
      operationId: tagmanager.accounts.containers.triggers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: triggers
      x-stackQL-verb: select
    put:
      description: Updates a GTM Trigger.
      operationId: tagmanager.accounts.containers.triggers.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: triggers
      x-stackQL-verb: exec
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers:
    get:
      description: Lists all GTM Triggers of a Container.
      operationId: tagmanager.accounts.containers.triggers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: triggers
      x-stackQL-verb: select
    post:
      description: Creates a GTM Trigger.
      operationId: tagmanager.accounts.containers.triggers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: triggers
      x-stackQL-verb: insert
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}:
    delete:
      description: Deletes a Container Version.
      operationId: tagmanager.accounts.containers.versions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: versions
      x-stackQL-verb: delete
    put:
      description: Updates a Container Version.
      operationId: tagmanager.accounts.containers.versions.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: versions
      x-stackQL-verb: exec
    get:
      description: Gets a Container Version.
      operationId: tagmanager.accounts.containers.versions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: versions
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete:
    post:
      description: Undeletes a Container Version.
      operationId: tagmanager.accounts.containers.versions.undelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: versions
      x-stackQL-verb: exec
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions:
    get:
      description: Lists all Container Versions of a GTM Container.
      operationId: tagmanager.accounts.containers.versions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: versions
      x-stackQL-verb: select
    post:
      description: Creates a Container Version.
      operationId: tagmanager.accounts.containers.versions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      x-stackQL-resource: versions
      x-stackQL-verb: insert
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish:
    post:
      description: Publishes a Container Version.
      operationId: tagmanager.accounts.containers.versions.publish
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.publish
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.publish
      x-stackQL-resource: versions
      x-stackQL-verb: exec
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore:
    post:
      description: >-
        Restores a Container Version. This will overwrite the container's
        current configuration (including its variables, triggers and tags). The
        operation will not have any effect on the version that is being served
        (i.e. the published version).
      operationId: tagmanager.accounts.containers.versions.restore
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: versions
      x-stackQL-verb: exec
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/reauthorize_environments/{environmentId}:
    put:
      description: Re-generates the authorization code for a GTM Environment.
      operationId: tagmanager.accounts.containers.reauthorize_environments.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.publish
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.publish
      x-stackQL-resource: reauthorize_environments
      x-stackQL-verb: exec
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables/{variableId}:
    get:
      description: Gets a GTM Variable.
      operationId: tagmanager.accounts.containers.variables.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: variables
      x-stackQL-verb: select
    delete:
      description: Deletes a GTM Variable.
      operationId: tagmanager.accounts.containers.variables.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: variables
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Variable.
      operationId: tagmanager.accounts.containers.variables.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: variables
      x-stackQL-verb: exec
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables:
    post:
      description: Creates a GTM Variable.
      operationId: tagmanager.accounts.containers.variables.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: variables
      x-stackQL-verb: insert
    get:
      description: Lists all GTM Variables of a Container.
      operationId: tagmanager.accounts.containers.variables.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: variables
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags/{tagId}:
    delete:
      description: Deletes a GTM Tag.
      operationId: tagmanager.accounts.containers.tags.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: tags
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Tag.
      operationId: tagmanager.accounts.containers.tags.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: tags
      x-stackQL-verb: exec
    get:
      description: Gets a GTM Tag.
      operationId: tagmanager.accounts.containers.tags.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: tags
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags:
    get:
      description: Lists all GTM Tags of a Container.
      operationId: tagmanager.accounts.containers.tags.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: tags
      x-stackQL-verb: select
    post:
      description: Creates a GTM Tag.
      operationId: tagmanager.accounts.containers.tags.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: tags
      x-stackQL-verb: insert
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments:
    post:
      description: Creates a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: environments
      x-stackQL-verb: insert
    get:
      description: Lists all GTM Environments of a GTM Container.
      operationId: tagmanager.accounts.containers.environments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: environments
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments/{environmentId}:
    get:
      description: Gets a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: environments
      x-stackQL-verb: select
    delete:
      description: Deletes a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: environments
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: environments
      x-stackQL-verb: exec
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}:
    delete:
      description: Deletes a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: folders
      x-stackQL-verb: delete
    put:
      description: Updates a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: folders
      x-stackQL-verb: exec
    get:
      description: Gets a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: folders
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders:
    post:
      description: Creates a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: folders
      x-stackQL-verb: insert
    get:
      description: Lists all GTM Folders of a Container.
      operationId: tagmanager.accounts.containers.folders.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: folders
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}/entities:
    get:
      description: List all entities in a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.entities.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: entities
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}:
    delete:
      description: Deletes a Container.
      operationId: tagmanager.accounts.containers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.delete.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.delete.containers
      x-stackQL-resource: containers
      x-stackQL-verb: delete
    put:
      description: Updates a Container.
      operationId: tagmanager.accounts.containers.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: containers
      x-stackQL-verb: exec
    get:
      description: Gets a Container.
      operationId: tagmanager.accounts.containers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: containers
      x-stackQL-verb: select
  /tagmanager/v1/accounts/{accountId}/containers:
    get:
      description: Lists all Containers that belongs to a GTM Account.
      operationId: tagmanager.accounts.containers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: containers
      x-stackQL-verb: select
    post:
      description: Creates a Container.
      operationId: tagmanager.accounts.containers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
      x-stackQL-resource: containers
      x-stackQL-verb: insert
  /tagmanager/v1/accounts/{accountId}:
    put:
      description: Updates a GTM Account.
      operationId: tagmanager.accounts.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
    get:
      description: Gets a GTM Account.
      operationId: tagmanager.accounts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
  /tagmanager/v1/accounts:
    get:
      description: Lists all GTM Accounts that a user has access to.
      operationId: tagmanager.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.edit.containers
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.manage.accounts
        - Oauth2:
            - https://www.googleapis.com/auth/tagmanager.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tagmanager.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
