openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Area120 Tables API
  description: ''
  version: v1alpha1
  x-discovery-doc-revision: '20230622'
  x-generated-date: '2023-06-25'
servers:
  - url: https://area120tables.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/spreadsheets.readonly: See all your Google Sheets spreadsheets
            https://www.googleapis.com/auth/spreadsheets: See, edit, create, and delete all your Google Sheets spreadsheets
            https://www.googleapis.com/auth/drive.file: >-
              See, edit, create, and delete only the specific Google Drive files
              you use with this app
            https://www.googleapis.com/auth/drive: See, edit, create, and delete all of your Google Drive files
            https://www.googleapis.com/auth/tables: See, edit, create, and delete your tables in Tables by Area 120
            https://www.googleapis.com/auth/drive.readonly: See and download all your Google Drive files
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1alpha1/workspaces:
    get:
      description: Lists workspaces for the user.
      operationId: area120tables.workspaces.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: workspaces
      x-stackQL-verb: select
  /v1alpha1/workspaces/{workspacesId}:
    get:
      description: Gets a workspace. Returns NOT_FOUND if the workspace does not exist.
      operationId: area120tables.workspaces.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: workspaces
      x-stackQL-verb: select
  /v1alpha1/tables/{tablesId}:
    get:
      description: Gets a table. Returns NOT_FOUND if the table does not exist.
      operationId: area120tables.tables.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: tables
      x-stackQL-verb: select
  /v1alpha1/tables:
    get:
      description: Lists tables for the user.
      operationId: area120tables.tables.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: tables
      x-stackQL-verb: select
  /v1alpha1/tables/{tablesId}/rows/{rowsId}:
    delete:
      description: Deletes a row.
      operationId: area120tables.tables.rows.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: rows
      x-stackQL-verb: delete
    get:
      description: Gets a row. Returns NOT_FOUND if the row does not exist in the table.
      operationId: area120tables.tables.rows.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: rows
      x-stackQL-verb: select
    patch:
      description: Updates a row.
      operationId: area120tables.tables.rows.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: rows
      x-stackQL-verb: exec
  /v1alpha1/tables/{tablesId}/rows:batchUpdate:
    post:
      description: Updates multiple rows.
      operationId: area120tables.tables.rows.batchUpdate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: rows
      x-stackQL-verb: exec
  /v1alpha1/tables/{tablesId}/rows:
    post:
      description: Creates a row.
      operationId: area120tables.tables.rows.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: rows
      x-stackQL-verb: insert
    get:
      description: Lists rows in a table. Returns NOT_FOUND if the table does not exist.
      operationId: area120tables.tables.rows.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: rows
      x-stackQL-verb: select
  /v1alpha1/tables/{tablesId}/rows:batchDelete:
    post:
      description: Deletes multiple rows.
      operationId: area120tables.tables.rows.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: rows
      x-stackQL-verb: delete
  /v1alpha1/tables/{tablesId}/rows:batchCreate:
    post:
      description: Creates multiple rows.
      operationId: area120tables.tables.rows.batchCreate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/tables
          Oauth2c:
            - https://www.googleapis.com/auth/tables
      x-stackQL-resource: rows
      x-stackQL-verb: insert
