openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Analytics API
  description: Views and manages your Google Analytics data.
  version: v3
  x-discovery-doc-revision: '20190807'
  x-generated-date: '2023-06-25'
servers:
  - url: https://analytics.googleapis.com/analytics/v3
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/analytics: View and manage your Google Analytics data
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.readonly: View your Google Analytics data
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
            https://www.googleapis.com/auth/analytics.user.deletion: Manage Google Analytics user deletion requests
            https://www.googleapis.com/auth/analytics.provision: >-
              Create a new Google Analytics account along with its default
              property and view
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /metadata/{reportType}/columns:
    get:
      description: Lists all columns for a report type
      operationId: analytics.metadata.columns.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: columns
      x-stackQL-verb: select
  /userDeletion/userDeletionRequests:upsert:
    post:
      description: Insert or update a user deletion requests.
      operationId: analytics.userDeletion.userDeletionRequest.upsert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.user.deletion
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.user.deletion
      x-stackQL-resource: user_deletion_request
      x-stackQL-verb: exec
  /data/ga:
    get:
      description: Returns Analytics data for a view (profile).
      operationId: analytics.data.ga.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: ga
      x-stackQL-verb: select
  /data/mcf:
    get:
      description: Returns Analytics Multi-Channel Funnels data for a view (profile).
      operationId: analytics.data.mcf.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: mcf
      x-stackQL-verb: select
  /data/realtime:
    get:
      description: Returns real time data for a view (profile).
      operationId: analytics.data.realtime.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: realtime
      x-stackQL-verb: select
  /provisioning/createAccountTree:
    post:
      description: Provision account.
      operationId: analytics.provisioning.createAccountTree
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.provision
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.provision
      x-stackQL-resource: provisioning__account_tree
      x-stackQL-verb: insert
  /provisioning/createAccountTicket:
    post:
      description: Creates an account ticket.
      operationId: analytics.provisioning.createAccountTicket
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.provision
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.provision
      x-stackQL-resource: provisioning__account_ticket
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks:
    get:
      description: Lists webProperty-user links for a given web property.
      operationId: analytics.management.webpropertyUserLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: webproperty_user_links
      x-stackQL-verb: select
    post:
      description: Adds a new user to the given web property.
      operationId: analytics.management.webpropertyUserLinks.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: webproperty_user_links
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}:
    delete:
      description: Removes a user from the given web property.
      operationId: analytics.management.webpropertyUserLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: webproperty_user_links
      x-stackQL-verb: delete
    put:
      description: Updates permissions for an existing user on the given web property.
      operationId: analytics.management.webpropertyUserLinks.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: webproperty_user_links
      x-stackQL-verb: exec
  /management/accounts/{accountId}/webproperties:
    get:
      description: Lists web properties to which the user has access.
      operationId: analytics.management.webproperties.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: webproperties
      x-stackQL-verb: select
    post:
      description: >-
        Create a new property if the account has fewer than 20 properties. Web
        properties are visible in the Google Analytics interface only if they
        have at least one profile.
      operationId: analytics.management.webproperties.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: webproperties
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}:
    patch:
      description: Updates an existing web property. This method supports patch semantics.
      operationId: analytics.management.webproperties.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: webproperties
      x-stackQL-verb: exec
    get:
      description: Gets a web property to which the user has access.
      operationId: analytics.management.webproperties.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: webproperties
      x-stackQL-verb: select
    put:
      description: Updates an existing web property.
      operationId: analytics.management.webproperties.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: webproperties
      x-stackQL-verb: exec
  /management/accounts:
    get:
      description: Lists all accounts to which the user has access.
      operationId: analytics.management.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments:
    get:
      description: Lists experiments to which the user has access.
      operationId: analytics.management.experiments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: experiments
      x-stackQL-verb: select
    post:
      description: Create a new experiment.
      operationId: analytics.management.experiments.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: experiments
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}:
    delete:
      description: Delete an experiment.
      operationId: analytics.management.experiments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: experiments
      x-stackQL-verb: delete
    get:
      description: Returns an experiment to which the user has access.
      operationId: analytics.management.experiments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: experiments
      x-stackQL-verb: select
    put:
      description: Update an existing experiment.
      operationId: analytics.management.experiments.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: experiments
      x-stackQL-verb: exec
    patch:
      description: Update an existing experiment. This method supports patch semantics.
      operationId: analytics.management.experiments.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: experiments
      x-stackQL-verb: exec
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics:
    post:
      description: Create a new custom metric.
      operationId: analytics.management.customMetrics.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: insert
    get:
      description: Lists custom metrics to which the user has access.
      operationId: analytics.management.customMetrics.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}:
    patch:
      description: Updates an existing custom metric. This method supports patch semantics.
      operationId: analytics.management.customMetrics.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: exec
    put:
      description: Updates an existing custom metric.
      operationId: analytics.management.customMetrics.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: exec
    get:
      description: Get a custom metric to which the user has access.
      operationId: analytics.management.customMetrics.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks:
    get:
      description: Lists profile-user links for a given view (profile).
      operationId: analytics.management.profileUserLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: profile_user_links
      x-stackQL-verb: select
    post:
      description: Adds a new user to the given view (profile).
      operationId: analytics.management.profileUserLinks.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: profile_user_links
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}:
    delete:
      description: Removes a user from the given view (profile).
      operationId: analytics.management.profileUserLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: profile_user_links
      x-stackQL-verb: delete
    put:
      description: Updates permissions for an existing user on the given view (profile).
      operationId: analytics.management.profileUserLinks.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: profile_user_links
      x-stackQL-verb: exec
  /management/accounts/{accountId}/filters/{filterId}:
    patch:
      description: Updates an existing filter. This method supports patch semantics.
      operationId: analytics.management.filters.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: filters
      x-stackQL-verb: exec
    put:
      description: Updates an existing filter.
      operationId: analytics.management.filters.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: filters
      x-stackQL-verb: exec
    delete:
      description: Delete a filter.
      operationId: analytics.management.filters.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: filters
      x-stackQL-verb: delete
    get:
      description: Returns filters to which the user has access.
      operationId: analytics.management.filters.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: filters
      x-stackQL-verb: select
  /management/accounts/{accountId}/filters:
    post:
      description: Create a new filter.
      operationId: analytics.management.filters.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: filters
      x-stackQL-verb: insert
    get:
      description: Lists all filters for an account
      operationId: analytics.management.filters.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: filters
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads:
    get:
      description: List uploads to which the user has access.
      operationId: analytics.management.uploads.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: uploads
      x-stackQL-verb: select
    post:
      description: Upload data for a custom data source.
      operationId: analytics.management.uploads.uploadData
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: uploads
      x-stackQL-verb: exec
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads/{uploadId}:
    get:
      description: List uploads to which the user has access.
      operationId: analytics.management.uploads.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: uploads
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/deleteUploadData:
    post:
      description: Delete data associated with a previous upload.
      operationId: analytics.management.uploads.deleteUploadData
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: uploads__upload_data
      x-stackQL-verb: delete
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}:
    get:
      description: Gets a goal to which the user has access.
      operationId: analytics.management.goals.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: goals
      x-stackQL-verb: select
    patch:
      description: Updates an existing goal. This method supports patch semantics.
      operationId: analytics.management.goals.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: goals
      x-stackQL-verb: exec
    put:
      description: Updates an existing goal.
      operationId: analytics.management.goals.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: goals
      x-stackQL-verb: exec
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals:
    get:
      description: Lists goals to which the user has access.
      operationId: analytics.management.goals.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: goals
      x-stackQL-verb: select
    post:
      description: Create a new goal.
      operationId: analytics.management.goals.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: goals
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions:
    post:
      description: Create a new custom dimension.
      operationId: analytics.management.customDimensions.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: insert
    get:
      description: Lists custom dimensions to which the user has access.
      operationId: analytics.management.customDimensions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}:
    put:
      description: Updates an existing custom dimension.
      operationId: analytics.management.customDimensions.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: exec
    patch:
      description: >-
        Updates an existing custom dimension. This method supports patch
        semantics.
      operationId: analytics.management.customDimensions.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: exec
    get:
      description: Get a custom dimension to which the user has access.
      operationId: analytics.management.customDimensions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: select
  /management/accounts/{accountId}/entityUserLinks/{linkId}:
    delete:
      description: Removes a user from the given account.
      operationId: analytics.management.accountUserLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: account_user_links
      x-stackQL-verb: delete
    put:
      description: Updates permissions for an existing user on the given account.
      operationId: analytics.management.accountUserLinks.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: account_user_links
      x-stackQL-verb: exec
  /management/accounts/{accountId}/entityUserLinks:
    get:
      description: Lists account-user links for a given account.
      operationId: analytics.management.accountUserLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: account_user_links
      x-stackQL-verb: select
    post:
      description: Adds a new user to the given account.
      operationId: analytics.management.accountUserLinks.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: account_user_links
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}:
    patch:
      description: >-
        Updates an existing remarketing audience. This method supports patch
        semantics.
      operationId: analytics.management.remarketingAudience.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: remarketing_audience
      x-stackQL-verb: exec
    delete:
      description: Delete a remarketing audience.
      operationId: analytics.management.remarketingAudience.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: remarketing_audience
      x-stackQL-verb: delete
    put:
      description: Updates an existing remarketing audience.
      operationId: analytics.management.remarketingAudience.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: remarketing_audience
      x-stackQL-verb: exec
    get:
      description: Gets a remarketing audience to which the user has access.
      operationId: analytics.management.remarketingAudience.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: remarketing_audience
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences:
    get:
      description: Lists remarketing audiences to which the user has access.
      operationId: analytics.management.remarketingAudience.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: remarketing_audience
      x-stackQL-verb: select
    post:
      description: Creates a new remarketing audience.
      operationId: analytics.management.remarketingAudience.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: remarketing_audience
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports:
    post:
      description: Create a new unsampled report.
      operationId: analytics.management.unsampledReports.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: unsampled_reports
      x-stackQL-verb: insert
    get:
      description: Lists unsampled reports to which the user has access.
      operationId: analytics.management.unsampledReports.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: unsampled_reports
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}:
    delete:
      description: Deletes an unsampled report.
      operationId: analytics.management.unsampledReports.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: unsampled_reports
      x-stackQL-verb: delete
    get:
      description: Returns a single unsampled report.
      operationId: analytics.management.unsampledReports.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: unsampled_reports
      x-stackQL-verb: select
  /management/segments:
    get:
      description: Lists segments to which the user has access.
      operationId: analytics.management.segments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: segments
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources:
    get:
      description: List custom data sources to which the user has access.
      operationId: analytics.management.customDataSources.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_data_sources
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}:
    patch:
      description: >-
        Update an existing profile filter link. This method supports patch
        semantics.
      operationId: analytics.management.profileFilterLinks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: profile_filter_links
      x-stackQL-verb: exec
    get:
      description: Returns a single profile filter link.
      operationId: analytics.management.profileFilterLinks.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: profile_filter_links
      x-stackQL-verb: select
    put:
      description: Update an existing profile filter link.
      operationId: analytics.management.profileFilterLinks.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: profile_filter_links
      x-stackQL-verb: exec
    delete:
      description: Delete a profile filter link.
      operationId: analytics.management.profileFilterLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: profile_filter_links
      x-stackQL-verb: delete
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks:
    get:
      description: Lists all profile filter links for a profile.
      operationId: analytics.management.profileFilterLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: profile_filter_links
      x-stackQL-verb: select
    post:
      description: Create a new profile filter link.
      operationId: analytics.management.profileFilterLinks.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: profile_filter_links
      x-stackQL-verb: insert
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}:
    put:
      description: Updates an existing view (profile).
      operationId: analytics.management.profiles.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: profiles
      x-stackQL-verb: exec
    delete:
      description: Deletes a view (profile).
      operationId: analytics.management.profiles.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: profiles
      x-stackQL-verb: delete
    get:
      description: Gets a view (profile) to which the user has access.
      operationId: analytics.management.profiles.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: profiles
      x-stackQL-verb: select
    patch:
      description: >-
        Updates an existing view (profile). This method supports patch
        semantics.
      operationId: analytics.management.profiles.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: profiles
      x-stackQL-verb: exec
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles:
    get:
      description: Lists views (profiles) to which the user has access.
      operationId: analytics.management.profiles.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: profiles
      x-stackQL-verb: select
    post:
      description: Create a new view (profile).
      operationId: analytics.management.profiles.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: profiles
      x-stackQL-verb: insert
  /management/accountSummaries:
    get:
      description: >-
        Lists account summaries (lightweight tree comprised of
        accounts/properties/profiles) to which the user has access.
      operationId: analytics.management.accountSummaries.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: account_summaries
      x-stackQL-verb: select
  /management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}:
    get:
      description: Returns a web property-Google Ads link to which the user has access.
      operationId: analytics.management.webPropertyAdWordsLinks.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: web_property_ad_words_links
      x-stackQL-verb: select
    delete:
      description: Deletes a web property-Google Ads link.
      operationId: analytics.management.webPropertyAdWordsLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: web_property_ad_words_links
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates an existing webProperty-Google Ads link. This method supports
        patch semantics.
      operationId: analytics.management.webPropertyAdWordsLinks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: web_property_ad_words_links
      x-stackQL-verb: exec
    put:
      description: Updates an existing webProperty-Google Ads link.
      operationId: analytics.management.webPropertyAdWordsLinks.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: web_property_ad_words_links
      x-stackQL-verb: exec
  /management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks:
    get:
      description: Lists webProperty-Google Ads links for a given web property.
      operationId: analytics.management.webPropertyAdWordsLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: web_property_ad_words_links
      x-stackQL-verb: select
    post:
      description: Creates a webProperty-Google Ads link.
      operationId: analytics.management.webPropertyAdWordsLinks.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: web_property_ad_words_links
      x-stackQL-verb: insert
  /management/clientId:hashClientId:
    post:
      description: Hashes the given Client ID.
      operationId: analytics.management.clientId.hashClientId
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: client_id
      x-stackQL-verb: exec
