openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Tasks API
  description: The Google Tasks API lets you manage your tasks and task lists.
  version: v1
  x-discovery-doc-revision: '20230620'
  x-generated-date: '2023-06-25'
servers:
  - url: https://tasks.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/tasks: Create, edit, organize, and delete all your tasks
            https://www.googleapis.com/auth/tasks.readonly: View your tasks
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /tasks/v1/users/@me/lists:
    post:
      description: >-
        Creates a new task list and adds it to the authenticated user's task
        lists.
      operationId: tasks.tasklists.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasklists
      x-stackQL-verb: insert
    get:
      description: Returns all the authenticated user's task lists.
      operationId: tasks.tasklists.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
        - Oauth2:
            - https://www.googleapis.com/auth/tasks.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tasks.readonly
      x-stackQL-resource: tasklists
      x-stackQL-verb: select
  /tasks/v1/users/@me/lists/{tasklist}:
    put:
      description: Updates the authenticated user's specified task list.
      operationId: tasks.tasklists.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasklists
      x-stackQL-verb: exec
    get:
      description: Returns the authenticated user's specified task list.
      operationId: tasks.tasklists.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
        - Oauth2:
            - https://www.googleapis.com/auth/tasks.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tasks.readonly
      x-stackQL-resource: tasklists
      x-stackQL-verb: select
    delete:
      description: Deletes the authenticated user's specified task list.
      operationId: tasks.tasklists.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasklists
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates the authenticated user's specified task list. This method
        supports patch semantics.
      operationId: tasks.tasklists.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasklists
      x-stackQL-verb: exec
  /tasks/v1/lists/{tasklist}/tasks/{task}/move:
    post:
      description: >-
        Moves the specified task to another position in the task list. This can
        include putting it as a child task under a new parent and/or move it to
        a different position among its sibling tasks.
      operationId: tasks.tasks.move
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasks
      x-stackQL-verb: exec
  /tasks/v1/lists/{tasklist}/tasks/{task}:
    delete:
      description: Deletes the specified task from the task list.
      operationId: tasks.tasks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasks
      x-stackQL-verb: delete
    get:
      description: Returns the specified task.
      operationId: tasks.tasks.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
        - Oauth2:
            - https://www.googleapis.com/auth/tasks.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tasks.readonly
      x-stackQL-resource: tasks
      x-stackQL-verb: select
    patch:
      description: Updates the specified task. This method supports patch semantics.
      operationId: tasks.tasks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasks
      x-stackQL-verb: exec
    put:
      description: Updates the specified task.
      operationId: tasks.tasks.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasks
      x-stackQL-verb: exec
  /tasks/v1/lists/{tasklist}/clear:
    post:
      description: >-
        Clears all completed tasks from the specified task list. The affected
        tasks will be marked as 'hidden' and no longer be returned by default
        when retrieving all tasks for a task list.
      operationId: tasks.tasks.clear
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasks
      x-stackQL-verb: exec
  /tasks/v1/lists/{tasklist}/tasks:
    get:
      description: Returns all tasks in the specified task list.
      operationId: tasks.tasks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
        - Oauth2:
            - https://www.googleapis.com/auth/tasks.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/tasks.readonly
      x-stackQL-resource: tasks
      x-stackQL-verb: select
    post:
      description: Creates a new task on the specified task list.
      operationId: tasks.tasks.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/tasks
          Oauth2c:
            - https://www.googleapis.com/auth/tasks
      x-stackQL-resource: tasks
      x-stackQL-verb: insert
