openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Classroom API
  description: Manages classes, rosters, and invitations in Google Classroom.
  version: v1
  x-discovery-doc-revision: '20230620'
  x-generated-date: '2023-06-25'
servers:
  - url: https://classroom.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/classroom.push-notifications: Receive notifications about your Google Classroom data
            https://www.googleapis.com/auth/classroom.courseworkmaterials: See, edit, and create classwork materials in Google Classroom
            https://www.googleapis.com/auth/classroom.topics.readonly: View topics in Google Classroom
            https://www.googleapis.com/auth/classroom.guardianlinks.students: >-
              View and manage guardians for students in your Google Classroom
              classes
            https://www.googleapis.com/auth/classroom.courses: >-
              See, edit, create, and permanently delete your Google Classroom
              classes
            https://www.googleapis.com/auth/classroom.coursework.students.readonly: >-
              View course work and grades for students in the Google Classroom
              classes you teach or administer
            https://www.googleapis.com/auth/classroom.student-submissions.me.readonly: View your course work and grades in Google Classroom
            https://www.googleapis.com/auth/classroom.announcements.readonly: View announcements in Google Classroom
            https://www.googleapis.com/auth/classroom.student-submissions.students.readonly: >-
              View course work and grades for students in the Google Classroom
              classes you teach or administer
            https://www.googleapis.com/auth/classroom.announcements: View and manage announcements in Google Classroom
            https://www.googleapis.com/auth/classroom.rosters.readonly: View your Google Classroom class rosters
            https://www.googleapis.com/auth/classroom.profile.photos: View the profile photos of people in your classes
            https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly: View your Google Classroom guardians
            https://www.googleapis.com/auth/classroom.rosters: Manage your Google Classroom class rosters
            https://www.googleapis.com/auth/classroom.coursework.me.readonly: View your course work and grades in Google Classroom
            https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly: See all classwork materials for your Google Classroom classes
            https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly: View guardians for students in your Google Classroom classes
            https://www.googleapis.com/auth/classroom.topics: See, create, and edit topics in Google Classroom
            https://www.googleapis.com/auth/classroom.profile.emails: View the email addresses of people in your classes
            https://www.googleapis.com/auth/classroom.coursework.me: >-
              See, create and edit coursework items including assignments,
              questions, and grades
            https://www.googleapis.com/auth/classroom.courses.readonly: View your Google Classroom classes
            https://www.googleapis.com/auth/classroom.coursework.students: >-
              Manage course work and grades for students in the Google Classroom
              classes you teach and view the course work and grades for classes
              you administer
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/registrations/{registrationId}:
    delete:
      description: >-
        Deletes a `Registration`, causing Classroom to stop sending
        notifications for that `Registration`.
      operationId: classroom.registrations.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.push-notifications
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.push-notifications
      x-stackQL-resource: registrations
      x-stackQL-verb: delete
  /v1/registrations:
    post:
      description: >-
        Creates a `Registration`, causing Classroom to start sending
        notifications from the provided `feed` to the destination provided in
        `cloudPubSubTopic`. Returns the created `Registration`. Currently, this
        will be the same as the argument, but with server-assigned fields such
        as `expiry_time` and `id` filled in. Note that any value specified for
        the `expiry_time` or `id` fields will be ignored. While Classroom may
        validate the `cloudPubSubTopic` and return errors on a best effort
        basis, it is the caller's responsibility to ensure that it exists and
        that Classroom has permission to publish to it. This method may return
        the following error codes: * `PERMISSION_DENIED` if: * the authenticated
        user does not have permission to receive notifications from the
        requested field; or * the current user has not granted access to the
        current Cloud project with the appropriate scope for the requested feed.
        Note that domain-wide delegation of authority is not currently supported
        for this purpose. If the request has the appropriate scope, but no grant
        exists, a Request Errors is returned. * another access error is
        encountered. * `INVALID_ARGUMENT` if: * no `cloudPubsubTopic` is
        specified, or the specified `cloudPubsubTopic` is not valid; or * no
        `feed` is specified, or the specified `feed` is not valid. * `NOT_FOUND`
        if: * the specified `feed` cannot be located, or the requesting user
        does not have permission to determine whether or not it exists; or * the
        specified `cloudPubsubTopic` cannot be located, or Classroom has not
        been granted permission to publish to it.
      operationId: classroom.registrations.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.push-notifications
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.push-notifications
      x-stackQL-resource: registrations
      x-stackQL-verb: insert
  /v1/userProfiles/{studentId}/guardianInvitations:
    get:
      description: >-
        Returns a list of guardian invitations that the requesting user is
        permitted to view, filtered by the parameters provided. This method
        returns the following error codes: * `PERMISSION_DENIED` if a
        `student_id` is specified, and the requesting user is not permitted to
        view guardian invitations for that student, if `"-"` is specified as the
        `student_id` and the user is not a domain administrator, if guardians
        are not enabled for the domain in question, or for other access errors.
        * `INVALID_ARGUMENT` if a `student_id` is specified, but its format
        cannot be recognized (it is not an email address, nor a `student_id`
        from the API, nor the literal string `me`). May also be returned if an
        invalid `page_token` or `state` is provided. * `NOT_FOUND` if a
        `student_id` is specified, and its format can be recognized, but
        Classroom has no record of that student.
      operationId: classroom.userProfiles.guardianInvitations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
      x-stackQL-resource: guardian_invitations
      x-stackQL-verb: select
    post:
      description: >-
        Creates a guardian invitation, and sends an email to the guardian asking
        them to confirm that they are the student's guardian. Once the guardian
        accepts the invitation, their `state` will change to `COMPLETED` and
        they will start receiving guardian notifications. A `Guardian` resource
        will also be created to represent the active guardian. The request
        object must have the `student_id` and `invited_email_address` fields
        set. Failing to set these fields, or setting any other fields in the
        request, will result in an error. This method returns the following
        error codes: * `PERMISSION_DENIED` if the current user does not have
        permission to manage guardians, if the guardian in question has already
        rejected too many requests for that student, if guardians are not
        enabled for the domain in question, or for other access errors. *
        `RESOURCE_EXHAUSTED` if the student or guardian has exceeded the
        guardian link limit. * `INVALID_ARGUMENT` if the guardian email address
        is not valid (for example, if it is too long), or if the format of the
        student ID provided cannot be recognized (it is not an email address,
        nor a `user_id` from this API). This error will also be returned if
        read-only fields are set, or if the `state` field is set to to a value
        other than `PENDING`. * `NOT_FOUND` if the student ID provided is a
        valid student ID, but Classroom has no record of that student. *
        `ALREADY_EXISTS` if there is already a pending guardian invitation for
        the student and `invited_email_address` provided, or if the provided
        `invited_email_address` matches the Google account of an existing
        `Guardian` for this user.
      operationId: classroom.userProfiles.guardianInvitations.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
      x-stackQL-resource: guardian_invitations
      x-stackQL-verb: insert
  /v1/userProfiles/{studentId}/guardianInvitations/{invitationId}:
    get:
      description: >-
        Returns a specific guardian invitation. This method returns the
        following error codes: * `PERMISSION_DENIED` if the requesting user is
        not permitted to view guardian invitations for the student identified by
        the `student_id`, if guardians are not enabled for the domain in
        question, or for other access errors. * `INVALID_ARGUMENT` if a
        `student_id` is specified, but its format cannot be recognized (it is
        not an email address, nor a `student_id` from the API, nor the literal
        string `me`). * `NOT_FOUND` if Classroom cannot find any record of the
        given student or `invitation_id`. May also be returned if the student
        exists, but the requesting user does not have access to see that
        student.
      operationId: classroom.userProfiles.guardianInvitations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
      x-stackQL-resource: guardian_invitations
      x-stackQL-verb: select
    patch:
      description: >-
        Modifies a guardian invitation. Currently, the only valid modification
        is to change the `state` from `PENDING` to `COMPLETE`. This has the
        effect of withdrawing the invitation. This method returns the following
        error codes: * `PERMISSION_DENIED` if the current user does not have
        permission to manage guardians, if guardians are not enabled for the
        domain in question or for other access errors. * `FAILED_PRECONDITION`
        if the guardian link is not in the `PENDING` state. * `INVALID_ARGUMENT`
        if the format of the student ID provided cannot be recognized (it is not
        an email address, nor a `user_id` from this API), or if the passed
        `GuardianInvitation` has a `state` other than `COMPLETE`, or if it
        modifies fields other than `state`. * `NOT_FOUND` if the student ID
        provided is a valid student ID, but Classroom has no record of that
        student, or if the `id` field does not refer to a guardian invitation
        known to Classroom.
      operationId: classroom.userProfiles.guardianInvitations.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
      x-stackQL-resource: guardian_invitations
      x-stackQL-verb: exec
  /v1/userProfiles/{studentId}/guardians/{guardianId}:
    delete:
      description: >-
        Deletes a guardian. The guardian will no longer receive guardian
        notifications and the guardian will no longer be accessible via the API.
        This method returns the following error codes: * `PERMISSION_DENIED` if
        no user that matches the provided `student_id` is visible to the
        requesting user, if the requesting user is not permitted to manage
        guardians for the student identified by the `student_id`, if guardians
        are not enabled for the domain in question, or for other access errors.
        * `INVALID_ARGUMENT` if a `student_id` is specified, but its format
        cannot be recognized (it is not an email address, nor a `student_id`
        from the API). * `NOT_FOUND` if the requesting user is permitted to
        modify guardians for the requested `student_id`, but no `Guardian`
        record exists for that student with the provided `guardian_id`.
      operationId: classroom.userProfiles.guardians.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
      x-stackQL-resource: guardians
      x-stackQL-verb: delete
    get:
      description: >-
        Returns a specific guardian. This method returns the following error
        codes: * `PERMISSION_DENIED` if no user that matches the provided
        `student_id` is visible to the requesting user, if the requesting user
        is not permitted to view guardian information for the student identified
        by the `student_id`, if guardians are not enabled for the domain in
        question, or for other access errors. * `INVALID_ARGUMENT` if a
        `student_id` is specified, but its format cannot be recognized (it is
        not an email address, nor a `student_id` from the API, nor the literal
        string `me`). * `NOT_FOUND` if the requesting user is permitted to view
        guardians for the requested `student_id`, but no `Guardian` record
        exists for that student that matches the provided `guardian_id`.
      operationId: classroom.userProfiles.guardians.get
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
      x-stackQL-resource: guardians
      x-stackQL-verb: select
  /v1/userProfiles/{studentId}/guardians:
    get:
      description: >-
        Returns a list of guardians that the requesting user is permitted to
        view, restricted to those that match the request. To list guardians for
        any student that the requesting user may view guardians for, use the
        literal character `-` for the student ID. This method returns the
        following error codes: * `PERMISSION_DENIED` if a `student_id` is
        specified, and the requesting user is not permitted to view guardian
        information for that student, if `"-"` is specified as the `student_id`
        and the user is not a domain administrator, if guardians are not enabled
        for the domain in question, if the `invited_email_address` filter is set
        by a user who is not a domain administrator, or for other access errors.
        * `INVALID_ARGUMENT` if a `student_id` is specified, but its format
        cannot be recognized (it is not an email address, nor a `student_id`
        from the API, nor the literal string `me`). May also be returned if an
        invalid `page_token` is provided. * `NOT_FOUND` if a `student_id` is
        specified, and its format can be recognized, but Classroom has no record
        of that student.
      operationId: classroom.userProfiles.guardians.list
      security:
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.guardianlinks.students
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
      x-stackQL-resource: guardians
      x-stackQL-verb: select
  /v1/userProfiles/{userId}:
    get:
      description: >-
        Returns a user profile. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to access
        this user profile, if no profile exists with the requested ID, or for
        access errors.
      operationId: classroom.userProfiles.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.emails
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.emails
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.photos
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.photos
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
      x-stackQL-resource: user_profiles
      x-stackQL-verb: select
  /v1/invitations/{id}:
    delete:
      description: >-
        Deletes an invitation. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to delete
        the requested invitation or for access errors. * `NOT_FOUND` if no
        invitation exists with the requested ID.
      operationId: classroom.invitations.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
      x-stackQL-resource: invitations
      x-stackQL-verb: delete
    get:
      description: >-
        Returns an invitation. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to view the
        requested invitation or for access errors. * `NOT_FOUND` if no
        invitation exists with the requested ID.
      operationId: classroom.invitations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
      x-stackQL-resource: invitations
      x-stackQL-verb: select
  /v1/invitations:
    get:
      description: >-
        Returns a list of invitations that the requesting user is permitted to
        view, restricted to those that match the list request. *Note:* At least
        one of `user_id` or `course_id` must be supplied. Both fields can be
        supplied. This method returns the following error codes: *
        `PERMISSION_DENIED` for access errors.
      operationId: classroom.invitations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
      x-stackQL-resource: invitations
      x-stackQL-verb: select
    post:
      description: >-
        Creates an invitation. Only one invitation for a user and course may
        exist at a time. Delete and re-create an invitation to make changes.
        This method returns the following error codes: * `PERMISSION_DENIED` if
        the requesting user is not permitted to create invitations for this
        course or for access errors. * `NOT_FOUND` if the course or the user
        does not exist. * `FAILED_PRECONDITION`: * if the requested user's
        account is disabled. * if the user already has this role or a role with
        greater permissions. * for the following request errors: *
        IneligibleOwner * `ALREADY_EXISTS` if an invitation for the specified
        user and course already exists.
      operationId: classroom.invitations.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
      x-stackQL-resource: invitations
      x-stackQL-verb: insert
  /v1/invitations/{id}:accept:
    post:
      description: >-
        Accepts an invitation, removing it and adding the invited user to the
        teachers or students (as appropriate) of the specified course. Only the
        invited user may accept an invitation. This method returns the following
        error codes: * `PERMISSION_DENIED` if the requesting user is not
        permitted to accept the requested invitation or for access errors. *
        `FAILED_PRECONDITION` for the following request errors: *
        CourseMemberLimitReached * CourseNotModifiable *
        CourseTeacherLimitReached * UserGroupsMembershipLimitReached *
        `NOT_FOUND` if no invitation exists with the requested ID.
      operationId: classroom.invitations.accept
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
      x-stackQL-resource: invitations
      x-stackQL-verb: exec
  /v1/courses/{courseId}/students/{userId}:
    delete:
      description: >-
        Deletes a student of a course. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        delete students of this course or for access errors. * `NOT_FOUND` if no
        student of this course has the requested ID or if the course does not
        exist.
      operationId: classroom.courses.students.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
      x-stackQL-resource: students
      x-stackQL-verb: delete
    get:
      description: >-
        Returns a student of a course. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        view students of this course or for access errors. * `NOT_FOUND` if no
        student of this course has the requested ID or if the course does not
        exist.
      operationId: classroom.courses.students.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.emails
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.emails
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.photos
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.photos
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
      x-stackQL-resource: students
      x-stackQL-verb: select
  /v1/courses/{courseId}/students:
    get:
      description: >-
        Returns a list of students of this course that the requester is
        permitted to view. This method returns the following error codes: *
        `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for
        access errors.
      operationId: classroom.courses.students.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.emails
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.emails
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.photos
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.photos
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
      x-stackQL-resource: students
      x-stackQL-verb: select
    post:
      description: >-
        Adds a user as a student of a course. Domain administrators are
        permitted to [directly
        add](https://developers.google.com/classroom/guides/manage-users) users
        within their domain as students to courses within their domain. Students
        are permitted to add themselves to a course using an enrollment code.
        This method returns the following error codes: * `PERMISSION_DENIED` if
        the requesting user is not permitted to create students in this course
        or for access errors. * `NOT_FOUND` if the requested course ID does not
        exist. * `FAILED_PRECONDITION` if the requested user's account is
        disabled, for the following request errors: * CourseMemberLimitReached *
        CourseNotModifiable * UserGroupsMembershipLimitReached *
        InactiveCourseOwner * `ALREADY_EXISTS` if the user is already a student
        or teacher in the course.
      operationId: classroom.courses.students.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.emails
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.emails
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.photos
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.photos
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
      x-stackQL-resource: students
      x-stackQL-verb: insert
  /v1/courses/{courseId}/teachers/{userId}:
    get:
      description: >-
        Returns a teacher of a course. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        view teachers of this course or for access errors. * `NOT_FOUND` if no
        teacher of this course has the requested ID or if the course does not
        exist.
      operationId: classroom.courses.teachers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.emails
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.emails
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.photos
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.photos
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
      x-stackQL-resource: teachers
      x-stackQL-verb: select
    delete:
      description: >-
        Removes the specified teacher from the specified course. This method
        returns the following error codes: * `PERMISSION_DENIED` if the
        requesting user is not permitted to delete teachers of this course or
        for access errors. * `NOT_FOUND` if no teacher of this course has the
        requested ID or if the course does not exist. * `FAILED_PRECONDITION` if
        the requested ID belongs to the primary teacher of this course. *
        `FAILED_PRECONDITION` if the requested ID belongs to the owner of the
        course Drive folder. * `FAILED_PRECONDITION` if the course no longer has
        an active owner.
      operationId: classroom.courses.teachers.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
      x-stackQL-resource: teachers
      x-stackQL-verb: delete
  /v1/courses/{courseId}/teachers:
    get:
      description: >-
        Returns a list of teachers of this course that the requester is
        permitted to view. This method returns the following error codes: *
        `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for
        access errors.
      operationId: classroom.courses.teachers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.emails
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.emails
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.photos
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.photos
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters.readonly
      x-stackQL-resource: teachers
      x-stackQL-verb: select
    post:
      description: >-
        Creates a teacher of a course. Domain administrators are permitted to
        [directly
        add](https://developers.google.com/classroom/guides/manage-users) users
        within their domain as teachers to courses within their domain.
        Non-admin users should send an Invitation instead. This method returns
        the following error codes: * `PERMISSION_DENIED` if the requesting user
        is not permitted to create teachers in this course or for access errors.
        * `NOT_FOUND` if the requested course ID does not exist. *
        `FAILED_PRECONDITION` if the requested user's account is disabled, for
        the following request errors: * CourseMemberLimitReached *
        CourseNotModifiable * CourseTeacherLimitReached *
        UserGroupsMembershipLimitReached * InactiveCourseOwner *
        `ALREADY_EXISTS` if the user is already a teacher or student in the
        course.
      operationId: classroom.courses.teachers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.emails
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.emails
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.profile.photos
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.profile.photos
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.rosters
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.rosters
      x-stackQL-resource: teachers
      x-stackQL-verb: insert
  /v1/courses/{courseId}/courseWorkMaterials:
    post:
      description: >-
        Creates a course work material. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        access the requested course, create course work material in the
        requested course, share a Drive attachment, or for access errors. *
        `INVALID_ARGUMENT` if the request is malformed or if more than 20 *
        materials are provided. * `NOT_FOUND` if the requested course does not
        exist. * `FAILED_PRECONDITION` for the following request error: *
        AttachmentNotVisible
      operationId: classroom.courses.courseWorkMaterials.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
      x-stackQL-resource: course_work_materials
      x-stackQL-verb: insert
    get:
      description: >-
        Returns a list of course work material that the requester is permitted
        to view. Course students may only view `PUBLISHED` course work material.
        Course teachers and domain administrators may view all course work
        material. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to access
        the requested course or for access errors. * `INVALID_ARGUMENT` if the
        request is malformed. * `NOT_FOUND` if the requested course does not
        exist.
      operationId: classroom.courses.courseWorkMaterials.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly
      x-stackQL-resource: course_work_materials
      x-stackQL-verb: select
  /v1/courses/{courseId}/courseWorkMaterials/{id}:
    get:
      description: >-
        Returns a course work material. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        access the requested course or course work material, or for access
        errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND`
        if the requested course or course work material does not exist.
      operationId: classroom.courses.courseWorkMaterials.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly
      x-stackQL-resource: course_work_materials
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a course work material. This request must be made by the
        Developer Console project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding course work material item. This method returns the
        following error codes: * `PERMISSION_DENIED` if the requesting developer
        project did not create the corresponding course work material, if the
        requesting user is not permitted to delete the requested course or for
        access errors. * `FAILED_PRECONDITION` if the requested course work
        material has already been deleted. * `NOT_FOUND` if no course exists
        with the requested ID.
      operationId: classroom.courses.courseWorkMaterials.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
      x-stackQL-resource: course_work_materials
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates one or more fields of a course work material. This method
        returns the following error codes: * `PERMISSION_DENIED` if the
        requesting developer project for access errors. * `INVALID_ARGUMENT` if
        the request is malformed. * `FAILED_PRECONDITION` if the requested
        course work material has already been deleted. * `NOT_FOUND` if the
        requested course or course work material does not exist
      operationId: classroom.courses.courseWorkMaterials.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courseworkmaterials
      x-stackQL-resource: course_work_materials
      x-stackQL-verb: exec
  /v1/courses/{courseId}/announcements:
    get:
      description: >-
        Returns a list of announcements that the requester is permitted to view.
        Course students may only view `PUBLISHED` announcements. Course teachers
        and domain administrators may view all announcements. This method
        returns the following error codes: * `PERMISSION_DENIED` if the
        requesting user is not permitted to access the requested course or for
        access errors. * `INVALID_ARGUMENT` if the request is malformed. *
        `NOT_FOUND` if the requested course does not exist.
      operationId: classroom.courses.announcements.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.announcements
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.announcements
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.announcements.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.announcements.readonly
      x-stackQL-resource: announcements
      x-stackQL-verb: select
    post:
      description: >-
        Creates an announcement. This method returns the following error codes:
        * `PERMISSION_DENIED` if the requesting user is not permitted to access
        the requested course, create announcements in the requested course,
        share a Drive attachment, or for access errors. * `INVALID_ARGUMENT` if
        the request is malformed. * `NOT_FOUND` if the requested course does not
        exist. * `FAILED_PRECONDITION` for the following request error: *
        AttachmentNotVisible
      operationId: classroom.courses.announcements.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.announcements
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.announcements
      x-stackQL-resource: announcements
      x-stackQL-verb: insert
  /v1/courses/{courseId}/announcements/{id}:
    delete:
      description: >-
        Deletes an announcement. This request must be made by the Developer
        Console project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding announcement item. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting developer project did not
        create the corresponding announcement, if the requesting user is not
        permitted to delete the requested course or for access errors. *
        `FAILED_PRECONDITION` if the requested announcement has already been
        deleted. * `NOT_FOUND` if no course exists with the requested ID.
      operationId: classroom.courses.announcements.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.announcements
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.announcements
      x-stackQL-resource: announcements
      x-stackQL-verb: delete
    get:
      description: >-
        Returns an announcement. This method returns the following error codes:
        * `PERMISSION_DENIED` if the requesting user is not permitted to access
        the requested course or announcement, or for access errors. *
        `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the
        requested course or announcement does not exist.
      operationId: classroom.courses.announcements.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.announcements
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.announcements
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.announcements.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.announcements.readonly
      x-stackQL-resource: announcements
      x-stackQL-verb: select
    patch:
      description: >-
        Updates one or more fields of an announcement. This method returns the
        following error codes: * `PERMISSION_DENIED` if the requesting developer
        project did not create the corresponding announcement or for access
        errors. * `INVALID_ARGUMENT` if the request is malformed. *
        `FAILED_PRECONDITION` if the requested announcement has already been
        deleted. * `NOT_FOUND` if the requested course or announcement does not
        exist
      operationId: classroom.courses.announcements.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.announcements
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.announcements
      x-stackQL-resource: announcements
      x-stackQL-verb: exec
  /v1/courses/{courseId}/announcements/{id}:modifyAssignees:
    post:
      description: >-
        Modifies assignee mode and options of an announcement. Only a teacher of
        the course that contains the announcement may call this method. This
        method returns the following error codes: * `PERMISSION_DENIED` if the
        requesting user is not permitted to access the requested course or
        course work or for access errors. * `INVALID_ARGUMENT` if the request is
        malformed. * `NOT_FOUND` if the requested course or course work does not
        exist.
      operationId: classroom.courses.announcements.modifyAssignees
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.announcements
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.announcements
      x-stackQL-resource: announcements
      x-stackQL-verb: exec
  /v1/courses/{courseId}/courseWork/{id}:
    patch:
      description: >-
        Updates one or more fields of a course work. See
        google.classroom.v1.CourseWork for details of which fields may be
        updated and who may change them. This request must be made by the
        Developer Console project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding course work item. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting developer project did not
        create the corresponding course work, if the user is not permitted to
        make the requested modification to the student submission, or for access
        errors. * `INVALID_ARGUMENT` if the request is malformed. *
        `FAILED_PRECONDITION` if the requested course work has already been
        deleted. * `NOT_FOUND` if the requested course, course work, or student
        submission does not exist.
      operationId: classroom.courses.courseWork.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
      x-stackQL-resource: course_work
      x-stackQL-verb: exec
    get:
      description: >-
        Returns course work. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to access
        the requested course or course work, or for access errors. *
        `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the
        requested course or course work does not exist.
      operationId: classroom.courses.courseWork.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.coursework.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.coursework.students.readonly
      x-stackQL-resource: course_work
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a course work. This request must be made by the Developer
        Console project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding course work item. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting developer project did not
        create the corresponding course work, if the requesting user is not
        permitted to delete the requested course or for access errors. *
        `FAILED_PRECONDITION` if the requested course work has already been
        deleted. * `NOT_FOUND` if no course exists with the requested ID.
      operationId: classroom.courses.courseWork.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
      x-stackQL-resource: course_work
      x-stackQL-verb: delete
  /v1/courses/{courseId}/courseWork:
    post:
      description: >-
        Creates course work. The resulting course work (and corresponding
        student submissions) are associated with the Developer Console project
        of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to make the
        request. Classroom API requests to modify course work and student
        submissions must be made with an OAuth client ID from the associated
        Developer Console project. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        access the requested course, create course work in the requested course,
        share a Drive attachment, or for access errors. * `INVALID_ARGUMENT` if
        the request is malformed. * `NOT_FOUND` if the requested course does not
        exist. * `FAILED_PRECONDITION` for the following request error: *
        AttachmentNotVisible
      operationId: classroom.courses.courseWork.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
      x-stackQL-resource: course_work
      x-stackQL-verb: insert
    get:
      description: >-
        Returns a list of course work that the requester is permitted to view.
        Course students may only view `PUBLISHED` course work. Course teachers
        and domain administrators may view all course work. This method returns
        the following error codes: * `PERMISSION_DENIED` if the requesting user
        is not permitted to access the requested course or for access errors. *
        `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the
        requested course does not exist.
      operationId: classroom.courses.courseWork.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.coursework.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.coursework.students.readonly
      x-stackQL-resource: course_work
      x-stackQL-verb: select
  /v1/courses/{courseId}/courseWork/{id}:modifyAssignees:
    post:
      description: >-
        Modifies assignee mode and options of a coursework. Only a teacher of
        the course that contains the coursework may call this method. This
        method returns the following error codes: * `PERMISSION_DENIED` if the
        requesting user is not permitted to access the requested course or
        course work or for access errors. * `INVALID_ARGUMENT` if the request is
        malformed. * `NOT_FOUND` if the requested course or course work does not
        exist.
      operationId: classroom.courses.courseWork.modifyAssignees
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
      x-stackQL-resource: course_work
      x-stackQL-verb: exec
  /v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:modifyAttachments:
    post:
      description: >-
        Modifies attachments of student submission. Attachments may only be
        added to student submissions belonging to course work objects with a
        `workType` of `ASSIGNMENT`. This request must be made by the Developer
        Console project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding course work item. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        access the requested course or course work, if the user is not permitted
        to modify attachments on the requested student submission, or for access
        errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND`
        if the requested course, course work, or student submission does not
        exist.
      operationId: classroom.courses.courseWork.studentSubmissions.modifyAttachments
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
      x-stackQL-resource: student_submissions
      x-stackQL-verb: exec
  /v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:turnIn:
    post:
      description: >-
        Turns in a student submission. Turning in a student submission transfers
        ownership of attached Drive files to the teacher and may also update the
        submission state. This may only be called by the student that owns the
        specified student submission. This request must be made by the Developer
        Console project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding course work item. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        access the requested course or course work, turn in the requested
        student submission, or for access errors. * `INVALID_ARGUMENT` if the
        request is malformed. * `NOT_FOUND` if the requested course, course
        work, or student submission does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.turnIn
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me
      x-stackQL-resource: student_submissions
      x-stackQL-verb: exec
  /v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:return:
    post:
      description: >-
        Returns a student submission. Returning a student submission transfers
        ownership of attached Drive files to the student and may also update the
        submission state. Unlike the Classroom application, returning a student
        submission does not set assignedGrade to the draftGrade value. Only a
        teacher of the course that contains the requested student submission may
        call this method. This request must be made by the Developer Console
        project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding course work item. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        access the requested course or course work, return the requested student
        submission, or for access errors. * `INVALID_ARGUMENT` if the request is
        malformed. * `NOT_FOUND` if the requested course, course work, or
        student submission does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.return
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
      x-stackQL-resource: student_submissions
      x-stackQL-verb: exec
  /v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:
    get:
      description: >-
        Returns a student submission. * `PERMISSION_DENIED` if the requesting
        user is not permitted to access the requested course, course work, or
        student submission or for access errors. * `INVALID_ARGUMENT` if the
        request is malformed. * `NOT_FOUND` if the requested course, course
        work, or student submission does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.coursework.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.coursework.students.readonly
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.student-submissions.me.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.student-submissions.me.readonly
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.student-submissions.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.student-submissions.students.readonly
      x-stackQL-resource: student_submissions
      x-stackQL-verb: select
    patch:
      description: >-
        Updates one or more fields of a student submission. See
        google.classroom.v1.StudentSubmission for details of which fields may be
        updated and who may change them. This request must be made by the
        Developer Console project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding course work item. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting developer project did not
        create the corresponding course work, if the user is not permitted to
        make the requested modification to the student submission, or for access
        errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND`
        if the requested course, course work, or student submission does not
        exist.
      operationId: classroom.courses.courseWork.studentSubmissions.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
      x-stackQL-resource: student_submissions
      x-stackQL-verb: exec
  /v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions:
    get:
      description: >-
        Returns a list of student submissions that the requester is permitted to
        view, factoring in the OAuth scopes of the request. `-` may be specified
        as the `course_work_id` to include student submissions for multiple
        course work items. Course students may only view their own work. Course
        teachers and domain administrators may view all student submissions.
        This method returns the following error codes: * `PERMISSION_DENIED` if
        the requesting user is not permitted to access the requested course or
        course work, or for access errors. * `INVALID_ARGUMENT` if the request
        is malformed. * `NOT_FOUND` if the requested course does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.students
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.students
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.coursework.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.coursework.students.readonly
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.student-submissions.me.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.student-submissions.me.readonly
        - Oauth2:
            - >-
              https://www.googleapis.com/auth/classroom.student-submissions.students.readonly
          Oauth2c:
            - >-
              https://www.googleapis.com/auth/classroom.student-submissions.students.readonly
      x-stackQL-resource: student_submissions
      x-stackQL-verb: select
  /v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:reclaim:
    post:
      description: >-
        Reclaims a student submission on behalf of the student that owns it.
        Reclaiming a student submission transfers ownership of attached Drive
        files to the student and updates the submission state. Only the student
        that owns the requested student submission may call this method, and
        only for a student submission that has been turned in. This request must
        be made by the Developer Console project of the [OAuth client
        ID](https://support.google.com/cloud/answer/6158849) used to create the
        corresponding course work item. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        access the requested course or course work, unsubmit the requested
        student submission, or for access errors. * `FAILED_PRECONDITION` if the
        student submission has not been turned in. * `INVALID_ARGUMENT` if the
        request is malformed. * `NOT_FOUND` if the requested course, course
        work, or student submission does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.reclaim
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.coursework.me
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.coursework.me
      x-stackQL-resource: student_submissions
      x-stackQL-verb: exec
  /v1/courses/{courseId}/topics:
    get:
      description: >-
        Returns the list of topics that the requester is permitted to view. This
        method returns the following error codes: * `PERMISSION_DENIED` if the
        requesting user is not permitted to access the requested course or for
        access errors. * `INVALID_ARGUMENT` if the request is malformed. *
        `NOT_FOUND` if the requested course does not exist.
      operationId: classroom.courses.topics.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.topics
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.topics
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.topics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.topics.readonly
      x-stackQL-resource: topics
      x-stackQL-verb: select
    post:
      description: >-
        Creates a topic. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to access
        the requested course, create a topic in the requested course, or for
        access errors. * `INVALID_ARGUMENT` if the request is malformed. *
        `NOT_FOUND` if the requested course does not exist.
      operationId: classroom.courses.topics.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.topics
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.topics
      x-stackQL-resource: topics
      x-stackQL-verb: insert
  /v1/courses/{courseId}/topics/{id}:
    patch:
      description: >-
        Updates one or more fields of a topic. This method returns the following
        error codes: * `PERMISSION_DENIED` if the requesting developer project
        did not create the corresponding topic or for access errors. *
        `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the
        requested course or topic does not exist
      operationId: classroom.courses.topics.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.topics
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.topics
      x-stackQL-resource: topics
      x-stackQL-verb: exec
    get:
      description: >-
        Returns a topic. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to access
        the requested course or topic, or for access errors. *
        `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the
        requested course or topic does not exist.
      operationId: classroom.courses.topics.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.topics
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.topics
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.topics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.topics.readonly
      x-stackQL-resource: topics
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a topic. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not allowed to delete the
        requested topic or for access errors. * `FAILED_PRECONDITION` if the
        requested topic has already been deleted. * `NOT_FOUND` if no course or
        topic exists with the requested ID.
      operationId: classroom.courses.topics.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.topics
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.topics
      x-stackQL-resource: topics
      x-stackQL-verb: delete
  /v1/courses/{courseId}/aliases:
    post:
      description: >-
        Creates an alias for a course. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        create the alias or for access errors. * `NOT_FOUND` if the course does
        not exist. * `ALREADY_EXISTS` if the alias already exists. *
        `FAILED_PRECONDITION` if the alias requested does not make sense for the
        requesting user or course (for example, if a user not in a domain
        attempts to access a domain-scoped alias).
      operationId: classroom.courses.aliases.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
      x-stackQL-resource: aliases
      x-stackQL-verb: insert
    get:
      description: >-
        Returns a list of aliases for a course. This method returns the
        following error codes: * `PERMISSION_DENIED` if the requesting user is
        not permitted to access the course or for access errors. * `NOT_FOUND`
        if the course does not exist.
      operationId: classroom.courses.aliases.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses.readonly
      x-stackQL-resource: aliases
      x-stackQL-verb: select
  /v1/courses/{courseId}/aliases/{alias}:
    delete:
      description: >-
        Deletes an alias of a course. This method returns the following error
        codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
        remove the alias or for access errors. * `NOT_FOUND` if the alias does
        not exist. * `FAILED_PRECONDITION` if the alias requested does not make
        sense for the requesting user or course (for example, if a user not in a
        domain attempts to delete a domain-scoped alias).
      operationId: classroom.courses.aliases.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
      x-stackQL-resource: aliases
      x-stackQL-verb: delete
  /v1/courses/{id}:
    delete:
      description: >-
        Deletes a course. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to delete
        the requested course or for access errors. * `NOT_FOUND` if no course
        exists with the requested ID.
      operationId: classroom.courses.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
      x-stackQL-resource: courses
      x-stackQL-verb: delete
    patch:
      description: >-
        Updates one or more fields in a course. This method returns the
        following error codes: * `PERMISSION_DENIED` if the requesting user is
        not permitted to modify the requested course or for access errors. *
        `NOT_FOUND` if no course exists with the requested ID. *
        `INVALID_ARGUMENT` if invalid fields are specified in the update mask or
        if no update mask is supplied. * `FAILED_PRECONDITION` for the following
        request errors: * CourseNotModifiable * InactiveCourseOwner *
        IneligibleOwner
      operationId: classroom.courses.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
      x-stackQL-resource: courses
      x-stackQL-verb: exec
    get:
      description: >-
        Returns a course. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to access
        the requested course or for access errors. * `NOT_FOUND` if no course
        exists with the requested ID.
      operationId: classroom.courses.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses.readonly
      x-stackQL-resource: courses
      x-stackQL-verb: select
    put:
      description: >-
        Updates a course. This method returns the following error codes: *
        `PERMISSION_DENIED` if the requesting user is not permitted to modify
        the requested course or for access errors. * `NOT_FOUND` if no course
        exists with the requested ID. * `FAILED_PRECONDITION` for the following
        request errors: * CourseNotModifiable
      operationId: classroom.courses.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
      x-stackQL-resource: courses
      x-stackQL-verb: exec
  /v1/courses:
    get:
      description: >-
        Returns a list of courses that the requesting user is permitted to view,
        restricted to those that match the request. Returned courses are ordered
        by creation time, with the most recently created coming first. This
        method returns the following error codes: * `PERMISSION_DENIED` for
        access errors. * `INVALID_ARGUMENT` if the query argument is malformed.
        * `NOT_FOUND` if any users specified in the query arguments do not
        exist.
      operationId: classroom.courses.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses.readonly
      x-stackQL-resource: courses
      x-stackQL-verb: select
    post:
      description: >-
        Creates a course. The user specified in `ownerId` is the owner of the
        created course and added as a teacher. A non-admin requesting user can
        only create a course with themselves as the owner. Domain admins can
        create courses owned by any user within their domain. This method
        returns the following error codes: * `PERMISSION_DENIED` if the
        requesting user is not permitted to create courses or for access errors.
        * `NOT_FOUND` if the primary teacher is not a valid user. *
        `FAILED_PRECONDITION` if the course owner's account is disabled or for
        the following request errors: * UserCannotOwnCourse *
        UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if an alias was
        specified in the `id` and already exists.
      operationId: classroom.courses.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/classroom.courses
          Oauth2c:
            - https://www.googleapis.com/auth/classroom.courses
      x-stackQL-resource: courses
      x-stackQL-verb: insert
