openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: AdSense Management API
  description: >-
    The AdSense Management API allows publishers to access their inventory and
    run earnings and performance reports.
  version: v2
  x-discovery-doc-revision: '20230622'
  x-generated-date: '2023-06-25'
servers:
  - url: https://adsense.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/adsense: View and manage your AdSense data
            https://www.googleapis.com/auth/adsense.readonly: View your AdSense data
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v2/accounts/{accountsId}/alerts:
    get:
      description: Lists all the alerts available in an account.
      operationId: adsense.accounts.alerts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: alerts
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}:
    get:
      description: Gets the ad client from the given resource name.
      operationId: adsense.accounts.adclients.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: adclients
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients:
    get:
      description: Lists all the ad clients available in an account.
      operationId: adsense.accounts.adclients.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: adclients
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}/adcode:
    get:
      description: >-
        Gets the AdSense code for a given ad client. This returns what was
        previously known as the 'auto ad code'. This is only supported for ad
        clients with a product_code of AFC. For more information, see [About the
        AdSense code](https://support.google.com/adsense/answer/9274634).
      operationId: adsense.accounts.adclients.getAdcode
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: adclients__adcode
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}:
    patch:
      description: >-
        Updates an ad unit. This method can only be used by projects enabled for
        the [AdSense for
        Platforms](https://developers.google.com/adsense/platforms/) product.
        For now, this method can only be used to update `DISPLAY` ad units. See:
        https://support.google.com/adsense/answer/9183566
      operationId: adsense.accounts.adclients.adunits.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      x-stackQL-resource: adunits
      x-stackQL-verb: exec
    get:
      description: Gets an ad unit from a specified account and ad client.
      operationId: adsense.accounts.adclients.adunits.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: adunits
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}/adcode:
    get:
      description: >-
        Gets the ad unit code for a given ad unit. For more information, see
        [About the AdSense
        code](https://support.google.com/adsense/answer/9274634) and [Where to
        place the ad code in your
        HTML](https://support.google.com/adsense/answer/9190028).
      operationId: adsense.accounts.adclients.adunits.getAdcode
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: adunits__adcode
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}:listLinkedCustomChannels:
    get:
      description: Lists all the custom channels available for an ad unit.
      operationId: adsense.accounts.adclients.adunits.listLinkedCustomChannels
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: adunits__linked_custom_channels
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}/adunits:
    post:
      description: >-
        Creates an ad unit. This method can only be used by projects enabled for
        the [AdSense for
        Platforms](https://developers.google.com/adsense/platforms/) product.
        Note that ad units can only be created for ad clients with an "AFC"
        product code. For more info see the [AdClient
        resource](/adsense/management/reference/rest/v2/accounts.adclients). For
        now, this method can only be used to create `DISPLAY` ad units. See:
        https://support.google.com/adsense/answer/9183566
      operationId: adsense.accounts.adclients.adunits.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      x-stackQL-resource: adunits
      x-stackQL-verb: insert
    get:
      description: Lists all ad units under a specified account and ad client.
      operationId: adsense.accounts.adclients.adunits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: adunits
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}:
    get:
      description: Gets information about the selected custom channel.
      operationId: adsense.accounts.adclients.customchannels.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: customchannels
      x-stackQL-verb: select
    patch:
      description: >-
        Updates a custom channel. This method can only be used by projects
        enabled for the [AdSense for
        Platforms](https://developers.google.com/adsense/platforms/) product.
      operationId: adsense.accounts.adclients.customchannels.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      x-stackQL-resource: customchannels
      x-stackQL-verb: exec
    delete:
      description: >-
        Deletes a custom channel. This method can only be used by projects
        enabled for the [AdSense for
        Platforms](https://developers.google.com/adsense/platforms/) product.
      operationId: adsense.accounts.adclients.customchannels.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      x-stackQL-resource: customchannels
      x-stackQL-verb: delete
  /v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}:listLinkedAdUnits:
    get:
      description: Lists all the ad units available for a custom channel.
      operationId: adsense.accounts.adclients.customchannels.listLinkedAdUnits
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: customchannels__linked_ad_units
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels:
    get:
      description: Lists all the custom channels available in an ad client.
      operationId: adsense.accounts.adclients.customchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: customchannels
      x-stackQL-verb: select
    post:
      description: >-
        Creates a custom channel. This method can only be used by projects
        enabled for the [AdSense for
        Platforms](https://developers.google.com/adsense/platforms/) product.
      operationId: adsense.accounts.adclients.customchannels.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      x-stackQL-resource: customchannels
      x-stackQL-verb: insert
  /v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels/{urlchannelsId}:
    get:
      description: Gets information about the selected url channel.
      operationId: adsense.accounts.adclients.urlchannels.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: urlchannels
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels:
    get:
      description: Lists active url channels.
      operationId: adsense.accounts.adclients.urlchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: urlchannels
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/payments:
    get:
      description: Lists all the payments available for an account.
      operationId: adsense.accounts.payments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: payments
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/reports/{reportsId}/saved:generateCsv:
    get:
      description: Generates a csv formatted saved report.
      operationId: adsense.accounts.reports.saved.generateCsv
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: saved
      x-stackQL-verb: exec
  /v2/accounts/{accountsId}/reports/{reportsId}/saved:generate:
    get:
      description: Generates a saved report.
      operationId: adsense.accounts.reports.saved.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: saved
      x-stackQL-verb: exec
  /v2/accounts/{accountsId}/reports/saved:
    get:
      description: Lists saved reports.
      operationId: adsense.accounts.reports.saved.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: saved
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/reports:generateCsv:
    get:
      description: Generates a csv formatted ad hoc report.
      operationId: adsense.accounts.reports.generateCsv
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v2/accounts/{accountsId}/reports/{reportsId}/saved:
    get:
      description: Gets the saved report from the given resource name.
      operationId: adsense.accounts.reports.getSaved
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: reports__saved
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/reports:generate:
    get:
      description: Generates an ad hoc report.
      operationId: adsense.accounts.reports.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: exec
  /v2/accounts/{accountsId}/sites:
    get:
      description: Lists all the sites available in an account.
      operationId: adsense.accounts.sites.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: sites
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/sites/{sitesId}:
    get:
      description: Gets information about the selected site.
      operationId: adsense.accounts.sites.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: sites
      x-stackQL-verb: select
  /v2/accounts/{accountsId}/adBlockingRecoveryTag:
    get:
      description: Gets the ad blocking recovery tag of an account.
      operationId: adsense.accounts.getAdBlockingRecoveryTag
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: accounts__ad_blocking_recovery_tag
      x-stackQL-verb: select
  /v2/accounts/{accountsId}:
    get:
      description: Gets information about the selected AdSense account.
      operationId: adsense.accounts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
  /v2/accounts/{accountsId}:listChildAccounts:
    get:
      description: Lists all accounts directly managed by the given AdSense account.
      operationId: adsense.accounts.listChildAccounts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: accounts__child_accounts
      x-stackQL-verb: select
  /v2/accounts:
    get:
      description: Lists all accounts available to this user.
      operationId: adsense.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
