openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Calendar API
  description: Manipulates events and other calendar data.
  version: v3
  x-discovery-doc-revision: '20230616'
  x-generated-date: '2023-06-25'
servers:
  - url: https://www.googleapis.com/calendar/v3
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/calendar: >-
              See, edit, share, and permanently delete all the calendars you can
              access using Google Calendar
            https://www.googleapis.com/auth/calendar.events: View and edit events on all your calendars
            https://www.googleapis.com/auth/calendar.events.readonly: View events on all your calendars
            https://www.googleapis.com/auth/calendar.settings.readonly: View your Calendar settings
            https://www.googleapis.com/auth/calendar.readonly: >-
              See and download any calendar you can access using your Google
              Calendar
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /colors:
    get:
      description: Returns the color definitions for calendars and events.
      operationId: calendar.colors.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: colors
      x-stackQL-verb: select
  /calendars/{calendarId}/clear:
    post:
      description: >-
        Clears a primary calendar. This operation deletes all events associated
        with the primary calendar of an account.
      operationId: calendar.calendars.clear
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: exec
  /calendars/{calendarId}:
    get:
      description: Returns metadata for a calendar.
      operationId: calendar.calendars.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: calendars
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a secondary calendar. Use calendars.clear for clearing all
        events on primary calendars.
      operationId: calendar.calendars.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: delete
    patch:
      description: Updates metadata for a calendar. This method supports patch semantics.
      operationId: calendar.calendars.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: exec
    put:
      description: Updates metadata for a calendar.
      operationId: calendar.calendars.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: exec
  /calendars:
    post:
      description: Creates a secondary calendar.
      operationId: calendar.calendars.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendars
      x-stackQL-verb: insert
  /channels/stop:
    post:
      description: Stop watching resources through this channel
      operationId: calendar.channels.stop
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.settings.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.settings.readonly
      x-stackQL-resource: channels
      x-stackQL-verb: exec
  /freeBusy:
    post:
      description: Returns free/busy information for a set of calendars.
      operationId: calendar.freebusy.query
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: freebusy
      x-stackQL-verb: exec
  /users/me/settings:
    get:
      description: Returns all user settings for the authenticated user.
      operationId: calendar.settings.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.settings.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.settings.readonly
      x-stackQL-resource: settings
      x-stackQL-verb: select
  /users/me/settings/{setting}:
    get:
      description: Returns a single user setting.
      operationId: calendar.settings.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.settings.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.settings.readonly
      x-stackQL-resource: settings
      x-stackQL-verb: select
  /users/me/settings/watch:
    post:
      description: Watch for changes to Settings resources.
      operationId: calendar.settings.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.settings.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.settings.readonly
      x-stackQL-resource: settings
      x-stackQL-verb: exec
  /users/me/calendarList/{calendarId}:
    patch:
      description: >-
        Updates an existing calendar on the user's calendar list. This method
        supports patch semantics.
      operationId: calendar.calendarList.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendar_list
      x-stackQL-verb: exec
    put:
      description: Updates an existing calendar on the user's calendar list.
      operationId: calendar.calendarList.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendar_list
      x-stackQL-verb: exec
    delete:
      description: Removes a calendar from the user's calendar list.
      operationId: calendar.calendarList.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendar_list
      x-stackQL-verb: delete
    get:
      description: Returns a calendar from the user's calendar list.
      operationId: calendar.calendarList.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: calendar_list
      x-stackQL-verb: select
  /users/me/calendarList:
    post:
      description: Inserts an existing calendar into the user's calendar list.
      operationId: calendar.calendarList.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: calendar_list
      x-stackQL-verb: insert
    get:
      description: Returns the calendars on the user's calendar list.
      operationId: calendar.calendarList.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: calendar_list
      x-stackQL-verb: select
  /users/me/calendarList/watch:
    post:
      description: Watch for changes to CalendarList resources.
      operationId: calendar.calendarList.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: calendar_list
      x-stackQL-verb: exec
  /calendars/{calendarId}/acl:
    post:
      description: Creates an access control rule.
      operationId: calendar.acl.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: acl
      x-stackQL-verb: insert
    get:
      description: Returns the rules in the access control list for the calendar.
      operationId: calendar.acl.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: acl
      x-stackQL-verb: select
  /calendars/{calendarId}/acl/{ruleId}:
    delete:
      description: Deletes an access control rule.
      operationId: calendar.acl.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: acl
      x-stackQL-verb: delete
    put:
      description: Updates an access control rule.
      operationId: calendar.acl.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: acl
      x-stackQL-verb: exec
    get:
      description: Returns an access control rule.
      operationId: calendar.acl.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: acl
      x-stackQL-verb: select
    patch:
      description: Updates an access control rule. This method supports patch semantics.
      operationId: calendar.acl.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: acl
      x-stackQL-verb: exec
  /calendars/{calendarId}/acl/watch:
    post:
      description: Watch for changes to ACL resources.
      operationId: calendar.acl.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
      x-stackQL-resource: acl
      x-stackQL-verb: exec
  /calendars/{calendarId}/events/watch:
    post:
      description: Watch for changes to Events resources.
      operationId: calendar.events.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: events
      x-stackQL-verb: exec
  /calendars/{calendarId}/events/{eventId}/instances:
    get:
      description: Returns instances of the specified recurring event.
      operationId: calendar.events.instances
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: events
      x-stackQL-verb: exec
  /calendars/{calendarId}/events:
    post:
      description: Creates an event.
      operationId: calendar.events.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
      x-stackQL-resource: events
      x-stackQL-verb: insert
    get:
      description: Returns events on the specified calendar.
      operationId: calendar.events.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: events
      x-stackQL-verb: select
  /calendars/{calendarId}/events/{eventId}:
    put:
      description: Updates an event.
      operationId: calendar.events.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
      x-stackQL-resource: events
      x-stackQL-verb: exec
    delete:
      description: Deletes an event.
      operationId: calendar.events.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
      x-stackQL-resource: events
      x-stackQL-verb: delete
    patch:
      description: Updates an event. This method supports patch semantics.
      operationId: calendar.events.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
      x-stackQL-resource: events
      x-stackQL-verb: exec
    get:
      description: >-
        Returns an event based on its Google Calendar ID. To retrieve an event
        using its iCalendar ID, call the events.list method using the iCalUID
        parameter.
      operationId: calendar.events.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.readonly
      x-stackQL-resource: events
      x-stackQL-verb: select
  /calendars/{calendarId}/events/{eventId}/move:
    post:
      description: Moves an event to another calendar, i.e. changes an event's organizer.
      operationId: calendar.events.move
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
      x-stackQL-resource: events
      x-stackQL-verb: exec
  /calendars/{calendarId}/events/quickAdd:
    post:
      description: Creates an event based on a simple text string.
      operationId: calendar.events.quickAdd
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
      x-stackQL-resource: events
      x-stackQL-verb: exec
  /calendars/{calendarId}/events/import:
    post:
      description: >-
        Imports an event. This operation is used to add a private copy of an
        existing event to a calendar.
      operationId: calendar.events.import
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/calendar
          Oauth2c:
            - https://www.googleapis.com/auth/calendar
        - Oauth2:
            - https://www.googleapis.com/auth/calendar.events
          Oauth2c:
            - https://www.googleapis.com/auth/calendar.events
      x-stackQL-resource: events
      x-stackQL-verb: exec
