openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Analytics Admin API
  description: ''
  version: v1alpha
  x-discovery-doc-revision: '20230622'
  x-generated-date: '2023-06-25'
servers:
  - url: https://analyticsadmin.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
            https://www.googleapis.com/auth/analytics.readonly: See and download your Google Analytics data
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google Analytics Account users by email address
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1alpha/accounts/{accountsId}/accessBindings:
    get:
      description: Lists all access bindings on an account or property.
      operationId: analyticsadmin.accounts.accessBindings.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: access_bindings
      x-stackQL-verb: select
    post:
      description: Creates an access binding on an account or property.
      operationId: analyticsadmin.accounts.accessBindings.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: insert
  /v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}:
    get:
      description: Gets information about an access binding.
      operationId: analyticsadmin.accounts.accessBindings.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: access_bindings
      x-stackQL-verb: select
    patch:
      description: Updates an access binding on an account or property.
      operationId: analyticsadmin.accounts.accessBindings.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: exec
    delete:
      description: Deletes an access binding on an account or property.
      operationId: analyticsadmin.accounts.accessBindings.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: delete
  /v1alpha/accounts/{accountsId}/accessBindings:batchGet:
    get:
      description: >-
        Gets information about multiple access bindings to an account or
        property.
      operationId: analyticsadmin.accounts.accessBindings.batchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: access_bindings
      x-stackQL-verb: select
  /v1alpha/accounts/{accountsId}/accessBindings:batchCreate:
    post:
      description: >-
        Creates information about multiple access bindings to an account or
        property. This method is transactional. If any AccessBinding cannot be
        created, none of the AccessBindings will be created.
      operationId: analyticsadmin.accounts.accessBindings.batchCreate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: insert
  /v1alpha/accounts/{accountsId}/accessBindings:batchDelete:
    post:
      description: >-
        Deletes information about multiple users' links to an account or
        property.
      operationId: analyticsadmin.accounts.accessBindings.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: delete
  /v1alpha/accounts/{accountsId}/accessBindings:batchUpdate:
    post:
      description: >-
        Updates information about multiple access bindings to an account or
        property.
      operationId: analyticsadmin.accounts.accessBindings.batchUpdate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: exec
  /v1alpha/accounts/{accountsId}/userLinks/{userLinksId}:
    patch:
      description: Updates a user link on an account or property.
      operationId: analyticsadmin.accounts.userLinks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: exec
    delete:
      description: Deletes a user link on an account or property.
      operationId: analyticsadmin.accounts.userLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: delete
    get:
      description: Gets information about a user's link to an account or property.
      operationId: analyticsadmin.accounts.userLinks.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: user_links
      x-stackQL-verb: select
  /v1alpha/accounts/{accountsId}/userLinks:batchGet:
    get:
      description: Gets information about multiple users' links to an account or property.
      operationId: analyticsadmin.accounts.userLinks.batchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: user_links
      x-stackQL-verb: select
  /v1alpha/accounts/{accountsId}/userLinks:batchCreate:
    post:
      description: >-
        Creates information about multiple users' links to an account or
        property. This method is transactional. If any UserLink cannot be
        created, none of the UserLinks will be created.
      operationId: analyticsadmin.accounts.userLinks.batchCreate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: insert
  /v1alpha/accounts/{accountsId}/userLinks:
    post:
      description: >-
        Creates a user link on an account or property. If the user with the
        specified email already has permissions on the account or property, then
        the user's existing permissions will be unioned with the permissions
        specified in the new UserLink.
      operationId: analyticsadmin.accounts.userLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: insert
    get:
      description: Lists all user links on an account or property.
      operationId: analyticsadmin.accounts.userLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: user_links
      x-stackQL-verb: select
  /v1alpha/accounts/{accountsId}/userLinks:audit:
    post:
      description: >-
        Lists all user links on an account or property, including implicit ones
        that come from effective permissions granted by groups or organization
        admin roles. If a returned user link does not have direct permissions,
        they cannot be removed from the account or property directly with the
        DeleteUserLink command. They have to be removed from the group/etc that
        gives them permissions, which is currently only usable/discoverable in
        the GA or GMP UIs.
      operationId: analyticsadmin.accounts.userLinks.audit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: user_links
      x-stackQL-verb: exec
  /v1alpha/accounts/{accountsId}/userLinks:batchDelete:
    post:
      description: >-
        Deletes information about multiple users' links to an account or
        property.
      operationId: analyticsadmin.accounts.userLinks.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: delete
  /v1alpha/accounts/{accountsId}/userLinks:batchUpdate:
    post:
      description: >-
        Updates information about multiple users' links to an account or
        property.
      operationId: analyticsadmin.accounts.userLinks.batchUpdate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: exec
  /v1alpha/accounts/{accountsId}:searchChangeHistoryEvents:
    post:
      description: >-
        Searches through all changes to an account or its children given the
        specified set of filters.
      operationId: analyticsadmin.accounts.searchChangeHistoryEvents
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1alpha/accounts:
    get:
      description: >-
        Returns all accounts accessible by the caller. Note that these accounts
        might not currently have GA4 properties. Soft-deleted (ie: "trashed")
        accounts are excluded by default. Returns an empty list if no relevant
        accounts are found.
      operationId: analyticsadmin.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
  /v1alpha/accounts/{accountsId}:
    delete:
      description: >-
        Marks target Account as soft-deleted (ie: "trashed") and returns it.
        This API does not have a method to restore soft-deleted accounts.
        However, they can be restored using the Trash Can UI. If the accounts
        are not restored before the expiration time, the account and all child
        resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be
        permanently purged. https://support.google.com/analytics/answer/6154772
        Returns an error if the target is not found.
      operationId: analyticsadmin.accounts.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: accounts
      x-stackQL-verb: delete
    patch:
      description: Updates an account.
      operationId: analyticsadmin.accounts.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
    get:
      description: Lookup for a single Account.
      operationId: analyticsadmin.accounts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
  /v1alpha/accounts/{accountsId}:runAccessReport:
    post:
      description: >-
        Returns a customized report of data access records. The report provides
        records of each time a user reads Google Analytics reporting data.
        Access records are retained for up to 2 years. Data Access Reports can
        be requested for a property. The property must be in Google Analytics
        360. This method is only available to Administrators. These data access
        records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and
        other products like Firebase & Admob that can retrieve data from Google
        Analytics through a linkage. These records don't include property
        configuration changes like adding a stream or changing a property's time
        zone. For configuration change history, see
        [searchChangeHistoryEvents](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/searchChangeHistoryEvents).
      operationId: analyticsadmin.accounts.runAccessReport
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1alpha/accounts:provisionAccountTicket:
    post:
      description: Requests a ticket for creating an account.
      operationId: analyticsadmin.accounts.provisionAccountTicket
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1alpha/accounts/{accountsId}/dataSharingSettings:
    get:
      description: >-
        Get data sharing settings on an account. Data sharing settings are
        singletons.
      operationId: analyticsadmin.accounts.getDataSharingSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts__data_sharing_settings
      x-stackQL-verb: select
  /v1alpha/accountSummaries:
    get:
      description: Returns summaries of all accounts accessible by the caller.
      operationId: analyticsadmin.accountSummaries.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: account_summaries
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/firebaseLinks:
    get:
      description: >-
        Lists FirebaseLinks on a property. Properties can have at most one
        FirebaseLink.
      operationId: analyticsadmin.properties.firebaseLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: firebase_links
      x-stackQL-verb: select
    post:
      description: Creates a FirebaseLink. Properties can have at most one FirebaseLink.
      operationId: analyticsadmin.properties.firebaseLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: firebase_links
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}:
    delete:
      description: Deletes a FirebaseLink on a property
      operationId: analyticsadmin.properties.firebaseLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: firebase_links
      x-stackQL-verb: delete
  /v1alpha/properties/{propertiesId}/googleAdsLinks:
    post:
      description: Creates a GoogleAdsLink.
      operationId: analyticsadmin.properties.googleAdsLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: google_ads_links
      x-stackQL-verb: insert
    get:
      description: Lists GoogleAdsLinks on a property.
      operationId: analyticsadmin.properties.googleAdsLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: google_ads_links
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}:
    delete:
      description: Deletes a GoogleAdsLink on a property
      operationId: analyticsadmin.properties.googleAdsLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: google_ads_links
      x-stackQL-verb: delete
    patch:
      description: Updates a GoogleAdsLink on a property
      operationId: analyticsadmin.properties.googleAdsLinks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: google_ads_links
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}:
    get:
      description: Looks up a single AdSenseLink.
      operationId: analyticsadmin.properties.adSenseLinks.get
      security: []
      x-stackQL-resource: ad_sense_links
      x-stackQL-verb: select
    delete:
      description: Deletes an AdSenseLink.
      operationId: analyticsadmin.properties.adSenseLinks.delete
      security: []
      x-stackQL-resource: ad_sense_links
      x-stackQL-verb: delete
  /v1alpha/properties/{propertiesId}/adSenseLinks:
    post:
      description: Creates an AdSenseLink.
      operationId: analyticsadmin.properties.adSenseLinks.create
      security: []
      x-stackQL-resource: ad_sense_links
      x-stackQL-verb: insert
    get:
      description: Lists AdSenseLinks on a property.
      operationId: analyticsadmin.properties.adSenseLinks.list
      security: []
      x-stackQL-resource: ad_sense_links
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}:
    delete:
      description: Deletes a DisplayVideo360AdvertiserLink on a property.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: display_video360_advertiser_links
      x-stackQL-verb: delete
    patch:
      description: Updates a DisplayVideo360AdvertiserLink on a property.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: display_video360_advertiser_links
      x-stackQL-verb: exec
    get:
      description: Look up a single DisplayVideo360AdvertiserLink
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinks.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: display_video360_advertiser_links
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks:
    get:
      description: Lists all DisplayVideo360AdvertiserLinks on a property.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: display_video360_advertiser_links
      x-stackQL-verb: select
    post:
      description: >-
        Creates a DisplayVideo360AdvertiserLink. This can only be utilized by
        users who have proper authorization both on the Google Analytics
        property and on the Display & Video 360 advertiser. Users who do not
        have access to the Display & Video 360 advertiser should instead seek to
        create a DisplayVideo360LinkProposal.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: display_video360_advertiser_links
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/searchAds360Links:
    post:
      description: Creates a SearchAds360Link.
      operationId: analyticsadmin.properties.searchAds360Links.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: search_ads360_links
      x-stackQL-verb: insert
    get:
      description: Lists all SearchAds360Links on a property.
      operationId: analyticsadmin.properties.searchAds360Links.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: search_ads360_links
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}:
    patch:
      description: Updates a SearchAds360Link on a property.
      operationId: analyticsadmin.properties.searchAds360Links.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: search_ads360_links
      x-stackQL-verb: exec
    delete:
      description: Deletes a SearchAds360Link on a property.
      operationId: analyticsadmin.properties.searchAds360Links.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: search_ads360_links
      x-stackQL-verb: delete
    get:
      description: Look up a single SearchAds360Link
      operationId: analyticsadmin.properties.searchAds360Links.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: search_ads360_links
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:
    get:
      description: Lookup for a single DisplayVideo360AdvertiserLinkProposal.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: display_video360_advertiser_link_proposals
      x-stackQL-verb: select
    delete:
      description: >-
        Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can
        only be used on cancelled proposals.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: display_video360_advertiser_link_proposals
      x-stackQL-verb: delete
  /v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals:
    post:
      description: Creates a DisplayVideo360AdvertiserLinkProposal.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: display_video360_advertiser_link_proposals
      x-stackQL-verb: insert
    get:
      description: Lists DisplayVideo360AdvertiserLinkProposals on a property.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: display_video360_advertiser_link_proposals
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve:
    post:
      description: >-
        Approves a DisplayVideo360AdvertiserLinkProposal. The
        DisplayVideo360AdvertiserLinkProposal will be deleted and a new
        DisplayVideo360AdvertiserLink will be created.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: display_video360_advertiser_link_proposals
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel:
    post:
      description: >-
        Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean
        either: - Declining a proposal initiated from Display & Video 360 -
        Withdrawing a proposal initiated from Google Analytics After being
        cancelled, a proposal will eventually be deleted automatically.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: display_video360_advertiser_link_proposals
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}:
    patch:
      description: Updates a ExpandedDataSet on a property.
      operationId: analyticsadmin.properties.expandedDataSets.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: expanded_data_sets
      x-stackQL-verb: exec
    delete:
      description: Deletes a ExpandedDataSet on a property.
      operationId: analyticsadmin.properties.expandedDataSets.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: expanded_data_sets
      x-stackQL-verb: delete
    get:
      description: Lookup for a single ExpandedDataSet.
      operationId: analyticsadmin.properties.expandedDataSets.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: expanded_data_sets
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/expandedDataSets:
    post:
      description: Creates a ExpandedDataSet.
      operationId: analyticsadmin.properties.expandedDataSets.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: expanded_data_sets
      x-stackQL-verb: insert
    get:
      description: Lists ExpandedDataSets on a property.
      operationId: analyticsadmin.properties.expandedDataSets.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: expanded_data_sets
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/audiences/{audiencesId}:
    get:
      description: >-
        Lookup for a single Audience. Audiences created before 2020 may not be
        supported. Default audiences will not show filter definitions.
      operationId: analyticsadmin.properties.audiences.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: audiences
      x-stackQL-verb: select
    patch:
      description: Updates an Audience on a property.
      operationId: analyticsadmin.properties.audiences.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: audiences
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/audiences:
    get:
      description: >-
        Lists Audiences on a property. Audiences created before 2020 may not be
        supported. Default audiences will not show filter definitions.
      operationId: analyticsadmin.properties.audiences.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: audiences
      x-stackQL-verb: select
    post:
      description: Creates an Audience.
      operationId: analyticsadmin.properties.audiences.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: audiences
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive:
    post:
      description: Archives an Audience on a property.
      operationId: analyticsadmin.properties.audiences.archive
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: audiences
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets:
    post:
      description: Creates a measurement protocol secret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: insert
    get:
      description: >-
        Returns child MeasurementProtocolSecrets under the specified parent
        Property.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}:
    get:
      description: Lookup for a single "GA4" MeasurementProtocolSecret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: select
    patch:
      description: Updates a measurement protocol secret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: exec
    delete:
      description: Deletes target MeasurementProtocolSecret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: delete
  /v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}:
    delete:
      description: Deletes an EventCreateRule.
      operationId: analyticsadmin.properties.dataStreams.eventCreateRules.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: event_create_rules
      x-stackQL-verb: delete
    get:
      description: Lookup for a single EventCreateRule.
      operationId: analyticsadmin.properties.dataStreams.eventCreateRules.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: event_create_rules
      x-stackQL-verb: select
    patch:
      description: Updates an EventCreateRule.
      operationId: analyticsadmin.properties.dataStreams.eventCreateRules.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: event_create_rules
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules:
    get:
      description: Lists EventCreateRules on a web data stream.
      operationId: analyticsadmin.properties.dataStreams.eventCreateRules.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: event_create_rules
      x-stackQL-verb: select
    post:
      description: Creates an EventCreateRule.
      operationId: analyticsadmin.properties.dataStreams.eventCreateRules.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: event_create_rules
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings:
    get:
      description: >-
        Returns the enhanced measurement settings for this data stream. Note
        that the stream must enable enhanced measurement for these settings to
        take effect.
      operationId: analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: data_streams__enhanced_measurement_settings
      x-stackQL-verb: select
    patch:
      description: >-
        Updates the enhanced measurement settings for this data stream. Note
        that the stream must enable enhanced measurement for these settings to
        take effect.
      operationId: analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: data_streams
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}:
    patch:
      description: Updates a DataStream on a property.
      operationId: analyticsadmin.properties.dataStreams.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: data_streams
      x-stackQL-verb: exec
    get:
      description: Lookup for a single DataStream.
      operationId: analyticsadmin.properties.dataStreams.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: data_streams
      x-stackQL-verb: select
    delete:
      description: Deletes a DataStream on a property.
      operationId: analyticsadmin.properties.dataStreams.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: data_streams
      x-stackQL-verb: delete
  /v1alpha/properties/{propertiesId}/dataStreams:
    get:
      description: Lists DataStreams on a property.
      operationId: analyticsadmin.properties.dataStreams.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: data_streams
      x-stackQL-verb: select
    post:
      description: Creates a DataStream.
      operationId: analyticsadmin.properties.dataStreams.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: data_streams
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag:
    get:
      description: >-
        Returns the Site Tag for the specified web stream. Site Tags are
        immutable singletons.
      operationId: analyticsadmin.properties.dataStreams.getGlobalSiteTag
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: data_streams__global_site_tag
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:
    patch:
      description: Updates a CustomMetric on a property.
      operationId: analyticsadmin.properties.customMetrics.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: exec
    get:
      description: Lookup for a single CustomMetric.
      operationId: analyticsadmin.properties.customMetrics.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/customMetrics:
    get:
      description: Lists CustomMetrics on a property.
      operationId: analyticsadmin.properties.customMetrics.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: select
    post:
      description: Creates a CustomMetric.
      operationId: analyticsadmin.properties.customMetrics.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive:
    post:
      description: Archives a CustomMetric on a property.
      operationId: analyticsadmin.properties.customMetrics.archive
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/userLinks/{userLinksId}:
    delete:
      description: Deletes a user link on an account or property.
      operationId: analyticsadmin.properties.userLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: delete
    get:
      description: Gets information about a user's link to an account or property.
      operationId: analyticsadmin.properties.userLinks.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: user_links
      x-stackQL-verb: select
    patch:
      description: Updates a user link on an account or property.
      operationId: analyticsadmin.properties.userLinks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/userLinks:batchCreate:
    post:
      description: >-
        Creates information about multiple users' links to an account or
        property. This method is transactional. If any UserLink cannot be
        created, none of the UserLinks will be created.
      operationId: analyticsadmin.properties.userLinks.batchCreate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/userLinks:
    get:
      description: Lists all user links on an account or property.
      operationId: analyticsadmin.properties.userLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: user_links
      x-stackQL-verb: select
    post:
      description: >-
        Creates a user link on an account or property. If the user with the
        specified email already has permissions on the account or property, then
        the user's existing permissions will be unioned with the permissions
        specified in the new UserLink.
      operationId: analyticsadmin.properties.userLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/userLinks:audit:
    post:
      description: >-
        Lists all user links on an account or property, including implicit ones
        that come from effective permissions granted by groups or organization
        admin roles. If a returned user link does not have direct permissions,
        they cannot be removed from the account or property directly with the
        DeleteUserLink command. They have to be removed from the group/etc that
        gives them permissions, which is currently only usable/discoverable in
        the GA or GMP UIs.
      operationId: analyticsadmin.properties.userLinks.audit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: user_links
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/userLinks:batchGet:
    get:
      description: Gets information about multiple users' links to an account or property.
      operationId: analyticsadmin.properties.userLinks.batchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: user_links
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/userLinks:batchDelete:
    post:
      description: >-
        Deletes information about multiple users' links to an account or
        property.
      operationId: analyticsadmin.properties.userLinks.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: delete
  /v1alpha/properties/{propertiesId}/userLinks:batchUpdate:
    post:
      description: >-
        Updates information about multiple users' links to an account or
        property.
      operationId: analyticsadmin.properties.userLinks.batchUpdate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: user_links
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:
    patch:
      description: Updates a CustomDimension on a property.
      operationId: analyticsadmin.properties.customDimensions.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: exec
    get:
      description: Lookup for a single CustomDimension.
      operationId: analyticsadmin.properties.customDimensions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/customDimensions:
    get:
      description: Lists CustomDimensions on a property.
      operationId: analyticsadmin.properties.customDimensions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: select
    post:
      description: Creates a CustomDimension.
      operationId: analyticsadmin.properties.customDimensions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive:
    post:
      description: Archives a CustomDimension on a property.
      operationId: analyticsadmin.properties.customDimensions.archive
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}:
    get:
      description: Lookup for a single BigQuery Link.
      operationId: analyticsadmin.properties.bigQueryLinks.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: big_query_links
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/bigQueryLinks:
    get:
      description: Lists BigQuery Links on a property.
      operationId: analyticsadmin.properties.bigQueryLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: big_query_links
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}:
    delete:
      description: Deletes a ChannelGroup on a property.
      operationId: analyticsadmin.properties.channelGroups.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: channel_groups
      x-stackQL-verb: delete
    get:
      description: Lookup for a single ChannelGroup.
      operationId: analyticsadmin.properties.channelGroups.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: channel_groups
      x-stackQL-verb: select
    patch:
      description: Updates a ChannelGroup.
      operationId: analyticsadmin.properties.channelGroups.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: channel_groups
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}/channelGroups:
    post:
      description: Creates a ChannelGroup.
      operationId: analyticsadmin.properties.channelGroups.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: channel_groups
      x-stackQL-verb: insert
    get:
      description: Lists ChannelGroups on a property.
      operationId: analyticsadmin.properties.channelGroups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: channel_groups
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}:
    get:
      description: Retrieve a single conversion event.
      operationId: analyticsadmin.properties.conversionEvents.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: conversion_events
      x-stackQL-verb: select
    delete:
      description: Deletes a conversion event in a property.
      operationId: analyticsadmin.properties.conversionEvents.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: conversion_events
      x-stackQL-verb: delete
  /v1alpha/properties/{propertiesId}/conversionEvents:
    get:
      description: >-
        Returns a list of conversion events in the specified parent property.
        Returns an empty list if no conversion events are found.
      operationId: analyticsadmin.properties.conversionEvents.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: conversion_events
      x-stackQL-verb: select
    post:
      description: Creates a conversion event with the specified attributes.
      operationId: analyticsadmin.properties.conversionEvents.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: conversion_events
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/accessBindings:batchDelete:
    post:
      description: >-
        Deletes information about multiple users' links to an account or
        property.
      operationId: analyticsadmin.properties.accessBindings.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: delete
  /v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}:
    delete:
      description: Deletes an access binding on an account or property.
      operationId: analyticsadmin.properties.accessBindings.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: delete
    patch:
      description: Updates an access binding on an account or property.
      operationId: analyticsadmin.properties.accessBindings.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: exec
    get:
      description: Gets information about an access binding.
      operationId: analyticsadmin.properties.accessBindings.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: access_bindings
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/accessBindings:batchCreate:
    post:
      description: >-
        Creates information about multiple access bindings to an account or
        property. This method is transactional. If any AccessBinding cannot be
        created, none of the AccessBindings will be created.
      operationId: analyticsadmin.properties.accessBindings.batchCreate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/accessBindings:
    get:
      description: Lists all access bindings on an account or property.
      operationId: analyticsadmin.properties.accessBindings.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: access_bindings
      x-stackQL-verb: select
    post:
      description: Creates an access binding on an account or property.
      operationId: analyticsadmin.properties.accessBindings.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}/accessBindings:batchGet:
    get:
      description: >-
        Gets information about multiple access bindings to an account or
        property.
      operationId: analyticsadmin.properties.accessBindings.batchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      x-stackQL-resource: access_bindings
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/accessBindings:batchUpdate:
    post:
      description: >-
        Updates information about multiple access bindings to an account or
        property.
      operationId: analyticsadmin.properties.accessBindings.batchUpdate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      x-stackQL-resource: access_bindings
      x-stackQL-verb: exec
  /v1alpha/properties:listConnectedSiteTags:
    post:
      description: >-
        Lists the connected site tags for a Universal Analytics property. A
        maximum of 20 connected site tags will be returned. Note: this has no
        effect on GA4 property.
      operationId: analyticsadmin.properties.listConnectedSiteTags
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties__connected_site_tags
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/dataRetentionSettings:
    get:
      description: Returns the singleton data retention settings for this property.
      operationId: analyticsadmin.properties.getDataRetentionSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties__data_retention_settings
      x-stackQL-verb: select
    patch:
      description: Updates the singleton data retention settings for this property.
      operationId: analyticsadmin.properties.updateDataRetentionSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1alpha/properties:fetchConnectedGa4Property:
    get:
      description: >-
        Given a specified UA property, looks up the GA4 property connected to
        it. Note: this cannot be used with GA4 properties.
      operationId: analyticsadmin.properties.fetchConnectedGa4Property
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties__connected_ga4_property
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}:
    patch:
      description: Updates a property.
      operationId: analyticsadmin.properties.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
    get:
      description: Lookup for a single "GA4" Property.
      operationId: analyticsadmin.properties.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: select
    delete:
      description: >-
        Marks target Property as soft-deleted (ie: "trashed") and returns it.
        This API does not have a method to restore soft-deleted properties.
        However, they can be restored using the Trash Can UI. If the properties
        are not restored before the expiration time, the Property and all child
        resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently
        purged. https://support.google.com/analytics/answer/6154772 Returns an
        error if the target is not found, or is not a GA4 Property.
      operationId: analyticsadmin.properties.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: delete
  /v1alpha/properties:setAutomatedGa4ConfigurationOptOut:
    post:
      description: >-
        Sets the opt out status for the automated GA4 setup process for a UA
        property. Note: this has no effect on GA4 property.
      operationId: analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1alpha/properties:
    get:
      description: >-
        Returns child Properties under the specified parent Account. Only "GA4"
        properties will be returned. Properties will be excluded if the caller
        does not have access. Soft-deleted (ie: "trashed") properties are
        excluded by default. Returns an empty list if no relevant properties are
        found.
      operationId: analyticsadmin.properties.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: select
    post:
      description: Creates an "GA4" property with the specified location and attributes.
      operationId: analyticsadmin.properties.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: insert
  /v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut:
    post:
      description: >-
        Fetches the opt out status for the automated GA4 setup process for a UA
        property. Note: this has no effect on GA4 property.
      operationId: analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties__automated_ga4_configuration_opt_out
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/attributionSettings:
    patch:
      description: Updates attribution settings on a property.
      operationId: analyticsadmin.properties.updateAttributionSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
    get:
      description: Lookup for a AttributionSettings singleton.
      operationId: analyticsadmin.properties.getAttributionSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties__attribution_settings
      x-stackQL-verb: select
  /v1alpha/properties/{propertiesId}/googleSignalsSettings:
    get:
      description: Lookup for Google Signals settings for a property.
      operationId: analyticsadmin.properties.getGoogleSignalsSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties__google_signals_settings
      x-stackQL-verb: select
    patch:
      description: Updates Google Signals settings for a property.
      operationId: analyticsadmin.properties.updateGoogleSignalsSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection:
    post:
      description: >-
        Acknowledges the terms of user data collection for the specified
        property. This acknowledgement must be completed (either in the Google
        Analytics UI or through this API) before MeasurementProtocolSecret
        resources may be created.
      operationId: analyticsadmin.properties.acknowledgeUserDataCollection
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1alpha/properties:createConnectedSiteTag:
    post:
      description: >-
        Creates a connected site tag for a Universal Analytics property. You can
        create a maximum of 20 connected site tags per property. Note: This API
        cannot be used on GA4 properties.
      operationId: analyticsadmin.properties.createConnectedSiteTag
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties__connected_site_tag
      x-stackQL-verb: insert
  /v1alpha/properties/{propertiesId}:runAccessReport:
    post:
      description: >-
        Returns a customized report of data access records. The report provides
        records of each time a user reads Google Analytics reporting data.
        Access records are retained for up to 2 years. Data Access Reports can
        be requested for a property. The property must be in Google Analytics
        360. This method is only available to Administrators. These data access
        records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and
        other products like Firebase & Admob that can retrieve data from Google
        Analytics through a linkage. These records don't include property
        configuration changes like adding a stream or changing a property's time
        zone. For configuration change history, see
        [searchChangeHistoryEvents](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/searchChangeHistoryEvents).
      operationId: analyticsadmin.properties.runAccessReport
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1alpha/properties:deleteConnectedSiteTag:
    post:
      description: >-
        Deletes a connected site tag for a Universal Analytics property. Note:
        this has no effect on GA4 properties.
      operationId: analyticsadmin.properties.deleteConnectedSiteTag
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties__connected_site_tag
      x-stackQL-verb: delete
