openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Analytics Admin API
  description: ''
  version: v1beta
  x-discovery-doc-revision: '20230622'
  x-generated-date: '2023-06-25'
servers:
  - url: https://analyticsadmin.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/analytics.readonly: See and download your Google Analytics data
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}:
    get:
      description: Lookup for a single DataStream.
      operationId: analyticsadmin.properties.dataStreams.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: data_streams
      x-stackQL-verb: select
    patch:
      description: Updates a DataStream on a property.
      operationId: analyticsadmin.properties.dataStreams.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: data_streams
      x-stackQL-verb: exec
    delete:
      description: Deletes a DataStream on a property.
      operationId: analyticsadmin.properties.dataStreams.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: data_streams
      x-stackQL-verb: delete
  /v1beta/properties/{propertiesId}/dataStreams:
    post:
      description: Creates a DataStream.
      operationId: analyticsadmin.properties.dataStreams.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: data_streams
      x-stackQL-verb: insert
    get:
      description: Lists DataStreams on a property.
      operationId: analyticsadmin.properties.dataStreams.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: data_streams
      x-stackQL-verb: select
  /v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}:
    get:
      description: Lookup for a single "GA4" MeasurementProtocolSecret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: select
    patch:
      description: Updates a measurement protocol secret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: exec
    delete:
      description: Deletes target MeasurementProtocolSecret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: delete
  /v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets:
    post:
      description: Creates a measurement protocol secret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: insert
    get:
      description: >-
        Returns child MeasurementProtocolSecrets under the specified parent
        Property.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: measurement_protocol_secrets
      x-stackQL-verb: select
  /v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:
    patch:
      description: Updates a CustomDimension on a property.
      operationId: analyticsadmin.properties.customDimensions.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: exec
    get:
      description: Lookup for a single CustomDimension.
      operationId: analyticsadmin.properties.customDimensions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: select
  /v1beta/properties/{propertiesId}/customDimensions:
    post:
      description: Creates a CustomDimension.
      operationId: analyticsadmin.properties.customDimensions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: insert
    get:
      description: Lists CustomDimensions on a property.
      operationId: analyticsadmin.properties.customDimensions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: select
  /v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive:
    post:
      description: Archives a CustomDimension on a property.
      operationId: analyticsadmin.properties.customDimensions.archive
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_dimensions
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}/googleAdsLinks:
    post:
      description: Creates a GoogleAdsLink.
      operationId: analyticsadmin.properties.googleAdsLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: google_ads_links
      x-stackQL-verb: insert
    get:
      description: Lists GoogleAdsLinks on a property.
      operationId: analyticsadmin.properties.googleAdsLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: google_ads_links
      x-stackQL-verb: select
  /v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}:
    delete:
      description: Deletes a GoogleAdsLink on a property
      operationId: analyticsadmin.properties.googleAdsLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: google_ads_links
      x-stackQL-verb: delete
    patch:
      description: Updates a GoogleAdsLink on a property
      operationId: analyticsadmin.properties.googleAdsLinks.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: google_ads_links
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}:
    delete:
      description: Deletes a FirebaseLink on a property
      operationId: analyticsadmin.properties.firebaseLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: firebase_links
      x-stackQL-verb: delete
  /v1beta/properties/{propertiesId}/firebaseLinks:
    get:
      description: >-
        Lists FirebaseLinks on a property. Properties can have at most one
        FirebaseLink.
      operationId: analyticsadmin.properties.firebaseLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: firebase_links
      x-stackQL-verb: select
    post:
      description: Creates a FirebaseLink. Properties can have at most one FirebaseLink.
      operationId: analyticsadmin.properties.firebaseLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: firebase_links
      x-stackQL-verb: insert
  /v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:
    get:
      description: Lookup for a single CustomMetric.
      operationId: analyticsadmin.properties.customMetrics.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: select
    patch:
      description: Updates a CustomMetric on a property.
      operationId: analyticsadmin.properties.customMetrics.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}/customMetrics:
    get:
      description: Lists CustomMetrics on a property.
      operationId: analyticsadmin.properties.customMetrics.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: select
    post:
      description: Creates a CustomMetric.
      operationId: analyticsadmin.properties.customMetrics.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: insert
  /v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive:
    post:
      description: Archives a CustomMetric on a property.
      operationId: analyticsadmin.properties.customMetrics.archive
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: custom_metrics
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}/conversionEvents:
    post:
      description: Creates a conversion event with the specified attributes.
      operationId: analyticsadmin.properties.conversionEvents.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: conversion_events
      x-stackQL-verb: insert
    get:
      description: >-
        Returns a list of conversion events in the specified parent property.
        Returns an empty list if no conversion events are found.
      operationId: analyticsadmin.properties.conversionEvents.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: conversion_events
      x-stackQL-verb: select
  /v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}:
    get:
      description: Retrieve a single conversion event.
      operationId: analyticsadmin.properties.conversionEvents.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: conversion_events
      x-stackQL-verb: select
    delete:
      description: Deletes a conversion event in a property.
      operationId: analyticsadmin.properties.conversionEvents.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: conversion_events
      x-stackQL-verb: delete
  /v1beta/properties/{propertiesId}:runAccessReport:
    post:
      description: >-
        Returns a customized report of data access records. The report provides
        records of each time a user reads Google Analytics reporting data.
        Access records are retained for up to 2 years. Data Access Reports can
        be requested for a property. The property must be in Google Analytics
        360. This method is only available to Administrators. These data access
        records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and
        other products like Firebase & Admob that can retrieve data from Google
        Analytics through a linkage. These records don't include property
        configuration changes like adding a stream or changing a property's time
        zone. For configuration change history, see
        [searchChangeHistoryEvents](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/searchChangeHistoryEvents).
      operationId: analyticsadmin.properties.runAccessReport
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}:acknowledgeUserDataCollection:
    post:
      description: >-
        Acknowledges the terms of user data collection for the specified
        property. This acknowledgement must be completed (either in the Google
        Analytics UI or through this API) before MeasurementProtocolSecret
        resources may be created.
      operationId: analyticsadmin.properties.acknowledgeUserDataCollection
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}:
    get:
      description: Lookup for a single "GA4" Property.
      operationId: analyticsadmin.properties.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: select
    patch:
      description: Updates a property.
      operationId: analyticsadmin.properties.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
    delete:
      description: >-
        Marks target Property as soft-deleted (ie: "trashed") and returns it.
        This API does not have a method to restore soft-deleted properties.
        However, they can be restored using the Trash Can UI. If the properties
        are not restored before the expiration time, the Property and all child
        resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently
        purged. https://support.google.com/analytics/answer/6154772 Returns an
        error if the target is not found, or is not a GA4 Property.
      operationId: analyticsadmin.properties.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: delete
  /v1beta/properties/{propertiesId}/dataRetentionSettings:
    patch:
      description: Updates the singleton data retention settings for this property.
      operationId: analyticsadmin.properties.updateDataRetentionSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: exec
    get:
      description: Returns the singleton data retention settings for this property.
      operationId: analyticsadmin.properties.getDataRetentionSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties__data_retention_settings
      x-stackQL-verb: select
  /v1beta/properties:
    post:
      description: Creates an "GA4" property with the specified location and attributes.
      operationId: analyticsadmin.properties.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: properties
      x-stackQL-verb: insert
    get:
      description: >-
        Returns child Properties under the specified parent Account. Only "GA4"
        properties will be returned. Properties will be excluded if the caller
        does not have access. Soft-deleted (ie: "trashed") properties are
        excluded by default. Returns an empty list if no relevant properties are
        found.
      operationId: analyticsadmin.properties.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: select
  /v1beta/accountSummaries:
    get:
      description: Returns summaries of all accounts accessible by the caller.
      operationId: analyticsadmin.accountSummaries.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: account_summaries
      x-stackQL-verb: select
  /v1beta/accounts/{accountsId}/dataSharingSettings:
    get:
      description: >-
        Get data sharing settings on an account. Data sharing settings are
        singletons.
      operationId: analyticsadmin.accounts.getDataSharingSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts__data_sharing_settings
      x-stackQL-verb: select
  /v1beta/accounts/{accountsId}:
    get:
      description: Lookup for a single Account.
      operationId: analyticsadmin.accounts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
    delete:
      description: >-
        Marks target Account as soft-deleted (ie: "trashed") and returns it.
        This API does not have a method to restore soft-deleted accounts.
        However, they can be restored using the Trash Can UI. If the accounts
        are not restored before the expiration time, the account and all child
        resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be
        permanently purged. https://support.google.com/analytics/answer/6154772
        Returns an error if the target is not found.
      operationId: analyticsadmin.accounts.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: accounts
      x-stackQL-verb: delete
    patch:
      description: Updates an account.
      operationId: analyticsadmin.accounts.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1beta/accounts:
    get:
      description: >-
        Returns all accounts accessible by the caller. Note that these accounts
        might not currently have GA4 properties. Soft-deleted (ie: "trashed")
        accounts are excluded by default. Returns an empty list if no relevant
        accounts are found.
      operationId: analyticsadmin.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: select
  /v1beta/accounts:provisionAccountTicket:
    post:
      description: Requests a ticket for creating an account.
      operationId: analyticsadmin.accounts.provisionAccountTicket
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1beta/accounts/{accountsId}:searchChangeHistoryEvents:
    post:
      description: >-
        Searches through all changes to an account or its children given the
        specified set of filters.
      operationId: analyticsadmin.accounts.searchChangeHistoryEvents
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
  /v1beta/accounts/{accountsId}:runAccessReport:
    post:
      description: >-
        Returns a customized report of data access records. The report provides
        records of each time a user reads Google Analytics reporting data.
        Access records are retained for up to 2 years. Data Access Reports can
        be requested for a property. The property must be in Google Analytics
        360. This method is only available to Administrators. These data access
        records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and
        other products like Firebase & Admob that can retrieve data from Google
        Analytics through a linkage. These records don't include property
        configuration changes like adding a stream or changing a property's time
        zone. For configuration change history, see
        [searchChangeHistoryEvents](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/searchChangeHistoryEvents).
      operationId: analyticsadmin.accounts.runAccessReport
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
