openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Analytics Data API
  description: Accesses report data in Google Analytics.
  version: v1beta
  x-discovery-doc-revision: '20230621'
  x-generated-date: '2023-06-25'
servers:
  - url: https://analyticsdata.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/analytics.readonly: See and download your Google Analytics data
            https://www.googleapis.com/auth/analytics: View and manage your Google Analytics data
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1beta/properties/{propertiesId}:runPivotReport:
    post:
      description: >-
        Returns a customized pivot report of your Google Analytics event data.
        Pivot reports are more advanced and expressive formats than regular
        reports. In a pivot report, dimensions are only visible if they are
        included in a pivot. Multiple pivots can be specified to further dissect
        your data.
      operationId: analyticsdata.properties.runPivotReport
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}:batchRunReports:
    post:
      description: >-
        Returns multiple reports in a batch. All reports must be for the same
        GA4 Property.
      operationId: analyticsdata.properties.batchRunReports
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}:runReport:
    post:
      description: >-
        Returns a customized report of your Google Analytics event data. Reports
        contain statistics derived from data collected by the Google Analytics
        tracking code. The data returned from the API is as a table with columns
        for the requested dimensions and metrics. Metrics are individual
        measurements of user activity on your property, such as active users or
        event count. Dimensions break down metrics across some common criteria,
        such as country or event name. For a guide to constructing requests &
        understanding responses, see [Creating a
        Report](https://developers.google.com/analytics/devguides/reporting/data/v1/basics).
      operationId: analyticsdata.properties.runReport
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}/metadata:
    get:
      description: >-
        Returns metadata for dimensions and metrics available in reporting
        methods. Used to explore the dimensions and metrics. In this method, a
        Google Analytics GA4 Property Identifier is specified in the request,
        and the metadata response includes Custom dimensions and metrics as well
        as Universal metadata. For example if a custom metric with parameter
        name `levels_unlocked` is registered to a property, the Metadata
        response will contain `customEvent:levels_unlocked`. Universal metadata
        are dimensions and metrics applicable to any property such as `country`
        and `totalUsers`.
      operationId: analyticsdata.properties.getMetadata
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties__metadata
      x-stackQL-verb: select
  /v1beta/properties/{propertiesId}:batchRunPivotReports:
    post:
      description: >-
        Returns multiple pivot reports in a batch. All reports must be for the
        same GA4 Property.
      operationId: analyticsdata.properties.batchRunPivotReports
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}:checkCompatibility:
    post:
      description: >-
        This compatibility method lists dimensions and metrics that can be added
        to a report request and maintain compatibility. This method fails if the
        request's dimensions and metrics are incompatible. In Google Analytics,
        reports fail if they request incompatible dimensions and/or metrics; in
        that case, you will need to remove dimensions and/or metrics from the
        incompatible report until the report is compatible. The Realtime and
        Core reports have different compatibility rules. This method checks
        compatibility for Core reports.
      operationId: analyticsdata.properties.checkCompatibility
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: exec
  /v1beta/properties/{propertiesId}:runRealtimeReport:
    post:
      description: >-
        Returns a customized report of realtime event data for your property.
        Events appear in realtime reports seconds after they have been sent to
        the Google Analytics. Realtime reports show events and usage data for
        the periods of time ranging from the present moment to 30 minutes ago
        (up to 60 minutes for Google Analytics 360 properties). For a guide to
        constructing realtime requests & understanding responses, see [Creating
        a Realtime
        Report](https://developers.google.com/analytics/devguides/reporting/data/v1/realtime-basics).
      operationId: analyticsdata.properties.runRealtimeReport
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics
          Oauth2c:
            - https://www.googleapis.com/auth/analytics
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      x-stackQL-resource: properties
      x-stackQL-verb: exec
