openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Blogger API
  description: >-
    The Blogger API provides access to posts, comments and pages of a Blogger
    blog.
  version: v3
  x-discovery-doc-revision: '20230622'
  x-generated-date: '2023-06-25'
servers:
  - url: https://blogger.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/blogger: Manage your Blogger account
            https://www.googleapis.com/auth/blogger.readonly: View your Blogger account
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v3/blogs/{blogId}/pageviews:
    get:
      description: Gets page views by blog id.
      operationId: blogger.pageViews.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: page_views
      x-stackQL-verb: select
  /v3/blogs/{blogId}/posts/{postId}/comments:
    get:
      description: Lists comments.
      operationId: blogger.comments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: comments
      x-stackQL-verb: select
  /v3/blogs/{blogId}/posts/{postId}/comments/{commentId}:
    delete:
      description: Deletes a comment by blog id, post id and comment id.
      operationId: blogger.comments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: comments
      x-stackQL-verb: delete
    get:
      description: Gets a comment by id.
      operationId: blogger.comments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: comments
      x-stackQL-verb: select
  /v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve:
    post:
      description: Marks a comment as not spam by blog id, post id and comment id.
      operationId: blogger.comments.approve
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: comments
      x-stackQL-verb: exec
  /v3/blogs/{blogId}/comments:
    get:
      description: Lists comments by blog.
      operationId: blogger.comments.listByBlog
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: comments__by_blog
      x-stackQL-verb: select
  /v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam:
    post:
      description: Marks a comment as spam by blog id, post id and comment id.
      operationId: blogger.comments.markAsSpam
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: comments
      x-stackQL-verb: exec
  /v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent:
    post:
      description: Removes the content of a comment by blog id, post id and comment id.
      operationId: blogger.comments.removeContent
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: comments__content
      x-stackQL-verb: delete
  /v3/blogs/{blogId}/posts/{postId}:
    patch:
      description: Patches a post.
      operationId: blogger.posts.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: posts
      x-stackQL-verb: exec
    put:
      description: Updates a post by blog id and post id.
      operationId: blogger.posts.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: posts
      x-stackQL-verb: exec
    get:
      description: Gets a post by blog id and post id
      operationId: blogger.posts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: posts
      x-stackQL-verb: select
    delete:
      description: Deletes a post by blog id and post id.
      operationId: blogger.posts.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: posts
      x-stackQL-verb: delete
  /v3/blogs/{blogId}/posts/{postId}/publish:
    post:
      description: Publishes a post.
      operationId: blogger.posts.publish
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: posts
      x-stackQL-verb: exec
  /v3/blogs/{blogId}/posts/{postId}/revert:
    post:
      description: Reverts a published or scheduled post to draft state.
      operationId: blogger.posts.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: posts
      x-stackQL-verb: exec
  /v3/blogs/{blogId}/posts:
    get:
      description: Lists posts.
      operationId: blogger.posts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: posts
      x-stackQL-verb: select
    post:
      description: Inserts a post.
      operationId: blogger.posts.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: posts
      x-stackQL-verb: insert
  /v3/blogs/{blogId}/posts/bypath:
    get:
      description: Gets a post by path.
      operationId: blogger.posts.getByPath
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: posts__by_path
      x-stackQL-verb: select
  /v3/blogs/{blogId}/posts/search:
    get:
      description: Searches for posts matching given query terms in the specified blog.
      operationId: blogger.posts.search
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: posts
      x-stackQL-verb: exec
  /v3/blogs/{blogId}:
    get:
      description: Gets a blog by id.
      operationId: blogger.blogs.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: blogs
      x-stackQL-verb: select
  /v3/blogs/byurl:
    get:
      description: Gets a blog by url.
      operationId: blogger.blogs.getByUrl
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: blogs__by_url
      x-stackQL-verb: select
  /v3/users/{userId}/blogs:
    get:
      description: Lists blogs by user.
      operationId: blogger.blogs.listByUser
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: blogs__by_user
      x-stackQL-verb: select
  /v3/blogs/{blogId}/pages/{pageId}:
    patch:
      description: Patches a page.
      operationId: blogger.pages.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: pages
      x-stackQL-verb: exec
    get:
      description: Gets a page by blog id and page id.
      operationId: blogger.pages.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: pages
      x-stackQL-verb: select
    delete:
      description: Deletes a page by blog id and page id.
      operationId: blogger.pages.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: pages
      x-stackQL-verb: delete
    put:
      description: Updates a page by blog id and page id.
      operationId: blogger.pages.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: pages
      x-stackQL-verb: exec
  /v3/blogs/{blogId}/pages/{pageId}/publish:
    post:
      description: Publishes a page.
      operationId: blogger.pages.publish
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: pages
      x-stackQL-verb: exec
  /v3/blogs/{blogId}/pages:
    post:
      description: Inserts a page.
      operationId: blogger.pages.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: pages
      x-stackQL-verb: insert
    get:
      description: Lists pages.
      operationId: blogger.pages.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: pages
      x-stackQL-verb: select
  /v3/blogs/{blogId}/pages/{pageId}/revert:
    post:
      description: Reverts a published or scheduled page to draft state.
      operationId: blogger.pages.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      x-stackQL-resource: pages
      x-stackQL-verb: exec
  /v3/users/{userId}/blogs/{blogId}/posts/{postId}:
    get:
      description: Gets one post and user info pair, by post_id and user_id.
      operationId: blogger.postUserInfos.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: post_user_infos
      x-stackQL-verb: select
  /v3/users/{userId}/blogs/{blogId}/posts:
    get:
      description: Lists post and user info pairs.
      operationId: blogger.postUserInfos.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: post_user_infos
      x-stackQL-verb: select
  /v3/users/{userId}/blogs/{blogId}:
    get:
      description: Gets one blog and user info pair by blog id and user id.
      operationId: blogger.blogUserInfos.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: blog_user_infos
      x-stackQL-verb: select
  /v3/users/{userId}:
    get:
      description: Gets one user by user_id.
      operationId: blogger.users.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      x-stackQL-resource: users
      x-stackQL-verb: select
