openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: YouTube Reporting API
  description: >-
    Schedules reporting jobs containing your YouTube Analytics data and
    downloads the resulting bulk data reports in the form of CSV files.
  version: v1
  x-discovery-doc-revision: '20230621'
  x-generated-date: '2023-06-25'
servers:
  - url: https://youtubereporting.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/yt-analytics.readonly: View YouTube Analytics reports for your YouTube content
            https://www.googleapis.com/auth/yt-analytics-monetary.readonly: >-
              View monetary and non-monetary YouTube Analytics reports for your
              YouTube content
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v1/jobs:
    post:
      description: Creates a job and returns it.
      operationId: youtubereporting.jobs.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
      x-stackQL-resource: jobs
      x-stackQL-verb: insert
    get:
      description: Lists jobs.
      operationId: youtubereporting.jobs.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
      x-stackQL-resource: jobs
      x-stackQL-verb: select
  /v1/jobs/{jobId}:
    get:
      description: Gets a job.
      operationId: youtubereporting.jobs.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
      x-stackQL-resource: jobs
      x-stackQL-verb: select
    delete:
      description: Deletes a job.
      operationId: youtubereporting.jobs.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
      x-stackQL-resource: jobs
      x-stackQL-verb: delete
  /v1/jobs/{jobId}/reports/{reportId}:
    get:
      description: Gets the metadata of a specific report.
      operationId: youtubereporting.jobs.reports.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: select
  /v1/jobs/{jobId}/reports:
    get:
      description: >-
        Lists reports created by a specific job. Returns NOT_FOUND if the job
        does not exist.
      operationId: youtubereporting.jobs.reports.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
      x-stackQL-resource: reports
      x-stackQL-verb: select
  /v1/reportTypes:
    get:
      description: Lists report types.
      operationId: youtubereporting.reportTypes.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
      x-stackQL-resource: report_types
      x-stackQL-verb: select
  /v1/media/{mediaId}:
    get:
      description: >-
        Method for media download. Download is supported on the URI
        `/v1/media/{+name}?alt=media`.
      operationId: youtubereporting.media.download
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
      x-stackQL-resource: media
      x-stackQL-verb: exec
